### ISSUE TITLE
issuerCertificateId is not described

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-stats#100]
https://w3c.github.io/webrtc-stats/#dom-rtccertificatestats-issuercertificateid does not have a description. I assume that it is a pointer to the RTCCertificateStats of the certificate next in the chain.
How can I recognize the root here? Missing issuercertificateid (which might be pretty common for self-signed certificates)

**Comment by fippo** [comment]
the other descriptions in that sections are not very clear either. I can make a PR if we agree on this bit

**Comment by alvestrand** [comment]
Our intention was that top-of-tree is "no issuer" - and self-signed certs have no issuer.
A PR is welcome!

**Comment by martinthomson** [comment]
I'm not sure that we need the field at all.  Self-signed certificates are the order of the day.  Anything else only encourages bad behaviour.

**Comment by fippo** [comment]
@martinthomson walking the certificate chain without being able to print out details about the issuer is boring indeed. Unless we assume people bring their own DER parsers in Javascript.

Another argument for removing this is that it would (afaics) the only case where somethingSomethingId would intentionally be empty.

**Comment by alvestrand** [comment]
@fippo it wouldn't be empty, it would be missing.
We do the same thing for rtcpTransport in the rtpTransport stats object.

Grabbing certs from a chain and sending them to a log server is a very reasonable thing to do. The only reason one cares about cert chains (after the browser has vouched for them) is for forensics.

**Comment by martinthomson** [comment]
My point is a different one: if you have more than one certificate in the chain, you are doing something wrong. The DTLS-SRTP security model treats certificates as glorified public key holders.

That is why I think that including fields to support reporting on issuers is a waste of time.

**Comment by alvestrand** [comment]
@pthatcherg I think you implemented cert chains for the Chrome implementation. What do you think about whether we need them or not?
