### ISSUE TITLE
Move to continuous publication

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#101]
The editors wish to move to continuous publication (publish to github.io whenever something is pushed to master).

@vivienlacourba your advice is sought.

@stefhak in your chair hat - please tell us if this is OK with you

**Comment by vivienlacourba** [comment]
+1 it would make your life as editor easier and ensure that what people see if the most recent version of your work.

Regarding implementing that change, we simply need to change the source under `Settings / Options / GitHub Pages` from `gh-pages branch` to `master branch`.

**Comment by vr000m** [comment]
What was the status of this? @dontcallmedom @vivienlacourba?

**Comment by alvestrand** [comment]
I tried switching, but it produced a weirdly formatted draft at the webrtc-stats.
May have to change the symlink at index.html to point to webrtc-stats.html.

**Comment by alvestrand** [comment]
Switched the symlink, switched the branch, reloaded a dozen times, and now it looks correct. Closing.
