### ISSUE TITLE
Make tidy has stopped working again

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#103]
Tagging @vivienlacourba @dontcallmedom 

Same symptom as seen a year ago: support/build.mk and support/repos.mk are stored with escaped newline and tab characters.

**Comment by alvestrand** [comment]
There were patches done to the gh-pages branch, which I've nuked, since the release scripting depends on gh-pages being a clone of the master branch.

Note that the webrtc-stats repo uses master as its working branch.

**Comment by vivienlacourba** [comment]
Hi @alvestrand 

I discussed this with @dontcallmedom but we don't have any recollection of this issue.
I can run `make setup; make clean; make update; make tidy` just fine on my computer (Ubuntu 16.10).

Could that be a makefile syntax issue that only affects Mac OS ?

**Comment by alvestrand** [comment]
Are you on the master branch of the webrtc-stats repo?

My computer is Ubuntu 14.04.

**Comment by alvestrand** [comment]
hta@hta-hippo:~/webrtc/webrtc-specs/webrtc-stats$ git status
# On branch master
# Your branch is up-to-date with 'origin/master'.
#
nothing to commit, working directory clean
hta@hta-hippo:~/webrtc/webrtc-specs/webrtc-stats$ make setup
support/repos.mk:1: *** target pattern contains no `%'.  Stop.

**Comment by vivienlacourba** [comment]
Yes I'm on the master branch.

Can you check your make setup with the above commands ?
```bash
$ which make
/usr/bin/make
$ ls -l /usr/bin/make
-rwxr-xr-x 1 root root 222792 avril 27  2016 /usr/bin/make
$ make --version
GNU Make 4.1
```

I believe your make version should be 3.81 as the package from Ubuntu 14.04 is [version 3.81-8.2ubuntu3](http://packages.ubuntu.com/trusty/make).

One thing to try first: edit `support/repos.mk` and `support/build.mk` and remove the leading space character at the start of each rule names (eg in front of `support/respec:`)

If that does not fix the issue install a newer make version from the [Ubuntu 16.04 make package](http://packages.ubuntu.com/xenial/amd64/make/download). The dependencies look fine, so you likely only need to run the following commands:
```bash
cd /tmp
wget http://no.archive.ubuntu.com/ubuntu/pool/main/m/make-dfsg/make_4.1-6_amd64.deb
dpkg -i make_4.1-6_amd64.deb
```

**Comment by alvestrand** [comment]
<pre>
hta@hta-hippo:~/ietf/nomcom16$ which make
/usr/bin/make
hta@hta-hippo:~/ietf/nomcom16$ make --version
GNU Make 3.81
</pre>

I'm a bit afraid of upgrading make on my corp buildhost. I suspect the issue is with the process used to install the files in "support" - and I can't find the command that does that.

**Comment by alvestrand** [comment]
Found the reference. The problem is with the "echo" command. You seem to be running on a system where "echo -e" is default behavior; I run on a system where "echo -e" has to be explicitly specified.
 
Patch attached.
[xyzzy-patch.txt](https://github.com/w3c/webrtc-stats/files/651919/xyzzy-patch.txt)

**Comment by alvestrand** [comment]
Better patch - use printf not echo; it's portable.
[xyzzy-patch.txt](https://github.com/w3c/webrtc-stats/files/651929/xyzzy-patch.txt)

**Comment by vivienlacourba** [comment]
@alvestrand I integrated your patch, can you now run the following without issues ?
`make update; make clean; make tidy`

**Comment by alvestrand** [comment]
This now works.
