### ISSUE TITLE
Why is ssrc a DOMString?

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-stats#105]
Every instance of `ssrc` in webrtc is an `unsigned long`. Is there a reason for it to be a DOMString in webrtc-stats? If so, a brief explanation would be helpful, with a description of what non-numeric values can be expected.

**Comment by jesup** [comment]
SSRCs by definition in RTP are 32-bit unsigned values.  While you could translate them into hex (upper or lower?  What if people compare against SDP, and the case is different?  etc), that's kinda silly.

They should be 32 bits, unsigned.

**Comment by alvestrand** [comment]
We should convert it in the spec to 32 bit unsigned integers.

**Comment by alvestrand** [comment]
All the comments seem to indicate consensus here.

**Comment by alvestrand** [comment]
Changed to unsigned int.
