### ISSUE TITLE
mediaTrackId field missing a description

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-stats#106]
It's clear what this field means, but it's missing the boilerplate "It is a unique identifier that is associated to the object that was inspected to produce the RTCMediaStreamTrackStats associated with this RTP stream".

As a sidenote, I'm not very fond of this boilerplate text in the first place. Could we change it to "A unique identifier of the MediaSteamTrack being sent by this RTP stream. Equal to the `id` of that MediaStreamTrack's corresponding RTCMediaStreamTrackStats object."

**Comment by alvestrand** [comment]
has been renamed and described.
