### ISSUE TITLE
Should document what RTCRTPStreamStats metrics are valid when `isRemote` is true.

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-stats#108]
For example:

- `targetBitrate` isn't something that's communicated via RTCP (to my knowledge), so I imagine it's only valid when `isRemote` is false.
- `roundTripTime`, though it uses RTCP RRs for its calculation, is a property of sent streams and thus only valid when `isRemote` is false.

Also: it would be helpful to have a small summary of how `RTCOutboundRTPStreamStats`, `RTCInboundRTPStreamStats`, `isRemote` and `associateStatsId` relate to each other. As I understand, each sent stream will provide an `RTCOutboundRTPStreamStats` where `isRemote` is false and an `RTCInboundRTPStreamStats` where `isRemote` is true. And each received stream will provide an `RTCInboundRTPStreamStats` where `isRemote` is false, and an `RTCOutboundRTPStreamStats` where `isRemote` is true. Which makes me realize: why do we have separate inbound/outbound stats objects that are associated by ID, instead of just putting everything in one object?

**Comment by alvestrand** [comment]
The reason why the local sender & remote receiver aren't bundled into one object is that the timestamps will be different (one is from local variables, the other is from the RTCP report reception).

**Comment by vr000m** [comment]
I believe the changes in #191 fixes this? @jan-ivar @taylor-b WDYT?

**Comment by taylor-b** [comment]
Agreed, closing.
