### ISSUE TITLE
RTCCodecStats needs `transportId` and `isRemote` to give it context

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-stats#109]
An `RTCCodecStats` by itself (if not being actively used to send/receive a stream) doesn't have enough context to be useful. I'd suggest adding:

- `transportId` - a payload type only makes sense in the context of an RTP session, and there's one RTP session per media transport so I think this works.
- `isRemote` - is this a codec we're prepared to encode, or decode?

**Comment by alvestrand** [comment]
My thinking when I wrote this was that one codec would be referenced from multiple RTPStreams, and that this was the important way to find them. The RTPStreams do have a transport link (and it needs to be the same for all of them, or, as you say, PT will be meaningless).

The case I can see is for negotiated codecs (such as CN) which are not currently actively used by any RTPStream (much like the case for candidates that are not in a candidate pair). It seems logical to have the link for that case, with a note that it needs to be consistent with RTPStreams' transport links.

isRemote is not a good name, but I agree that it seems reasonable to differentiate between encode-only, encode-decode and decode-only codecs. This property isn't inferrable from the SDP description, but is knowable from the local implementation.

**Comment by taylor-b** [comment]
You're right, "encode-only"/"decode-only"/"encode-decode" is better than "isRemote", since it would be redundant to have two identical codecs with only an "isRemote" bit flipped.

I think it would be nice to have the ability to use the codec stats in this way; for example, to see what codecs a PeerConnection is *prepared* to receive, even if not actively receiving.

**Comment by alvestrand** [comment]
I agree that figuring out which codecs are in use seems like a desirable goal.
We already buckled the "static object" nature of CodecStats when we added payloadType, so I guess adding transportId will not really cause more damage - with pt in there, we can't depend on reusing codec objects between transports anyway.
This still doesn't give us the relevant media section - can we avoid supporting that?

**Comment by taylor-b** [comment]
You can get from media section to transport with RTCRTPStreamStats (almost). The missing part is, when multiple RTCRtpSenders are using the same track, I don't see anything that identifies the sender.

**Comment by alvestrand** [comment]
Taylor, you understand this better than most. Can you do a PR on it?

**Comment by taylor-b** [comment]
Sure. Reminder to myself: we're going with an enum (or equivalent) with "encode-only"/"decode-only"/"encode-decode" values, rather than "isRemote".
