### ISSUE TITLE
Naming inconsistency

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-stats#11]
Looking at RTCStats desendants:
* RTCRTPStreamStats : RTCStats
* **RTCCodec** : RTCStats
* RTCPeerConnectionStats : RTCStats
* RTCMediaStreamStats : RTCStats
* RTCMediaStreamTrackStats : RTCStats
* RTCDataChannelStats : RTCStats
* RTCTransportStats : RTCStats
* **RTCIceCandidateAttributes** : RTCStats
* RTCIceCandidatePairStats : RTCStats
* RTCCertificateStats : RTCStats

They're all "*Stats" except two. Not that it matters terribly since these are dictionaries, but shouldn't we be consistent?

**Comment by vr000m** [comment]
Perhaps adding *Info instead of *Stats seems more appropriate as these dictionaries do not contain any metrics or statistics.
* RTCCodecInfo
* RTCIceCandidateAttributeInfo 

OTOH, RTCCertificateStats could be RTCCertificateInfo for the same reason. I do not feel strongly about it.

**Comment by jan-ivar** [comment]
@vr000m I follow your reasoning, however, anything returned from `getStats` is stats IMHO, not attributes, info or attribute-info). Dictionaries may grow over time and add more data, so I for one would rather see our types here reflect inheritance (RTCStats).

**Comment by alvestrand** [comment]
My personal leaning would be towards "info" - if one wants to know the inheritance hierarchy, one should walk the prototype chain, not try to parse names.
Names need to be 1) unique and 2) memorable. But I can't bring myself to feel strongly about this.

**Comment by jan-ivar** [comment]
@alvestrand dictionaries don't have prototypes. Since there's very little enforcement of this inheritance in JS, I would recommend name consistency here. See also https://github.com/w3c/webrtc-pc/issues/275

**Comment by alvestrand** [comment]
If we want to make this a principle, the document needs to state that it is.
I think we should accept the principle.

**Comment by alvestrand** [comment]
Principle seems to be that *Attribute and *Info should go, and *Stats should be added.

**Comment by alvestrand** [comment]
RTCIceCandidateAttributes -> RTCIceCandidateStats is done in #32

**Comment by vr000m** [comment]
Closing this issue, since both inconsistencies are now resolved.
