### ISSUE TITLE
What should `availableOutgoingBitrate`/`availableOutgoingBitrate` be for candidate pairs not in use?

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-stats#112]
If a candidate pair isn't currently selected by ICE, it's not clear what `availableOutgoingBitrate`/`availableIncomingBitrate` should be. Should they be the previous estimates, if the pair was used in the past? Or should they be left undefined? If it's the latter, then maybe these should be moved up to `RTCIceTransportStats`.

Also... What if audio/video use different DSCP values and have different bandwidth estimates? Which one should go in `availableOutgoingBitrate`?

**Comment by alvestrand** [comment]
When I added this for candidate pairs, I was thinking that we could use this to detect the case where a low-bandwidth connection is used when a high-bandwidth connection was previously used. The only way I can think of where this makes sense is to have the last estimated bitrate when it was used in the past, and have the stat be absent for pairs that never were used for live traffic.

**Comment by vr000m** [comment]
I agree with @alvestrand's suggestion for the updating the last estimate with candidate-pairs that were previously used. And the key missing for the pairs that were never used.

About the DSCP,  I think it is more important to know the overall estimate, hence, adding all the media estimates together would make sense. The tracks have relative priorities, and an implementation can compare the outgoing bitrates of the individual streams with the 

Although, I think we should expose the markings (codepoint value) in the appropriate inbound/outbound track.

**Comment by alvestrand** [comment]
Commentary in offline discussion is that the bandwidth data can go stale pretty quickly (walk-out-the-door problem), so it may be wiser / less misleading to just omit the bandwidth estimate on pairs that aren't in use.

**Comment by taylor-b** [comment]
In that case let's revisit the question: Should these move to RTCIceTransportStats, since there will only be one value per transport?
