### ISSUE TITLE
RTCRTPStreamStats.mediaTrackId, RTCMediaStreamStats.trackIds

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#113]
We have two members referring to RTCMediaStreamTrackStats objects by ID, RTCRTPStreamStats.mediaTrackId and RTCMediaStreamStats.trackIds.

Do we want to be consistent (mediaTrackId + mediaTrackIds OR trackId + trackIds OR mediaStreamTrackId + mediaStreamTrackIds) or keep these names?

Doesn't matter much what we call these but it would be nice to avoid renaming after Chromium unflags getStats (https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/bG-3TFOZC3s).

**Comment by alvestrand** [comment]
Sounds like "trackId(s)" is shorter. I'll make a PR.
