### ISSUE TITLE
Where is the API?

### ISSUE THREAD

**Issue by annevk** [w3c/webrtc-stats#115]
https://w3c.github.io/webrtc-stats/ suggests the document defines a set of APIs, but no entry point is to be found. It sounds like some other document might define an API that ends up returning the objects described in this document, but it's all rather unclear.

**Comment by alvestrand** [comment]
The introduction to section 4 goes as follows:

<blockquote>
4. Basic concepts

This section is non-normative.

The stats API is defined in [WEBRTC]. It is defined to return a set of objects that are a subclass of the RTCStats dictionary. This is normatively defined in [WEBRTC], but is reproduced here for ease of reference.

</blockquote>
Suggestions on how to make the wording more clear are welcome.

**Comment by annevk** [comment]
I think mainly the main introduction should point out this simply defines some objects, not an API. Although it's not immediately obvious how that works without hook, since the data needs to come from somewhere too.
