### ISSUE TITLE
getStats example is outdated and redundant.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-stats#117]
The https://w3c.github.io/webrtc-stats/#example-of-a-stats-application example is outdated.

I started writing a PR to fix it when I got deja vu.

Turns out we already have http://w3c.github.io/webrtc-pc/#getstats-example and it's up to date.

We should decide where we want the good one to live and axe the other.

**Comment by vr000m** [comment]
maybe fixed by #192

**Comment by jan-ivar** [comment]
Maybe, if we're ok with the example living in two places.
