### ISSUE TITLE
serverUrl for RTCIceCandidate?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-stats#12]
@alvestrand just noticed that serverUrl as described in https://lists.w3.org/Archives/Public/public-webrtc/2014May/0115.html is not part of the spec.

It's still more useful than just being able to figure out the type of the connection from the local type preference / priority.

**Comment by fippo** [comment]
that seems to have been renamed to addressSourceUrl? See http://w3c.github.io/webrtc-stats/#widl-RTCIceCandidateAttributes-addressSourceUrl

**Comment by vr000m** [comment]
Marking this as invalid, and closing the issue as the name has changed. Unless serverUrl is preferred over addressSourceUrl.

**Comment by juberti** [comment]
This is not lined up with RTCIceCandidateEvent.url. We should use consistent terminology.
