### ISSUE TITLE
Make sure timing and responsibility for stat object creation is clear

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-stats#120]
From web perf group review [1]
"t does not appear that this specification clearly defines when the various Stat objects are created and what is responsible for emitting the various Stat objects. Is another specification responsible for that?

It would be useful to link to that as it seems critical to ensuring cross-browser compat."

[1] https://lists.w3.org/Archives/Public/public-web-perf/2016Dec/0014.html

**Comment by alvestrand** [comment]
Does PR #114 answer that question for the creation case?

@toddreifsteck was the source of the comment, it seems.

**Comment by alvestrand** [comment]
Answering #115 should also help answering this one.

**Comment by toddreifsteck** [comment]
I think #114 helps with the creation. Solving #115 also helps but in a slightly different aspect. I also just opened #136 as it is the other lifetime issue that didn't seem to clear me.

**Comment by alvestrand** [comment]
I think all the subsidiary bugs have been addressed now. Closing; feel free to add new comments if you think something was not resolved.
