### ISSUE TITLE
Clarify if stat object's members can change after having been returned

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-stats#121]
From web perf group review [1]:

"Some pieces of the text hint that a Stat object’s members can be changed after it is returned. But an example shows 2 objects being compared to see how a baseline compares to a later “report”. Can stat object’s values be changed after they are returned?

http://www.w3.org/TR/2016/WD-webrtc-stats-20161214/#lifetime-of-stats-objects hints that an object that has been returned to JavaScript may change between accesses, but I could be misreading it."

[1] https://lists.w3.org/Archives/Public/public-web-perf/2016Dec/0014.html

**Comment by alvestrand** [comment]
Any such hint should be exterminated with extreme prejudice.
The intention of the stats object is that it is const after being created.

**Comment by dontcallmedom** [comment]
This was also reported by the original commenter in #136

**Comment by alvestrand** [comment]
Closing this as dup of #136, which is being addressed.
