### ISSUE TITLE
Travis appears to be borked by a ReSpec change

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#124]
Running this command:

node support/respec/tools/respec2html.js -e --src file://`pwd`/webrtc-stats.html --out build/output.html

will produce the output:

🚨 ReSpec warn: No <dfn> for timestamp in RTCStats.
🚨 ReSpec warn: No <dfn> for type in RTCStats.
🚨 ReSpec warn: No <dfn> for id in RTCStats.
🚨 ReSpec warn: No <dfn> for RTCStats.
🚨 ReSpec warn: No <dfn> for RTCCertificateStats.
undefined

In Travis, this causes failure.
"make update" gave no improvement.

Help sought - tagging @vivienlacourba @dontcallmedom

**Comment by dontcallmedom** [comment]
latest respec fixed it
