### ISSUE TITLE
Bitrate should have a definition

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#13]
http://w3c.github.io/webrtc-stats/#dictionary-rtcoutboundrtpstreamstats-members has "targetBitrate" without a definition.

This needs to call on some definition - preferably a preexisting one. At least we should be able to tell whether it's with or without RTP headers, and it would also be nice to say what measurement interval is expected to produce this bitrate. Not sure one exists.

**Comment by vr000m** [comment]
I should dig up the notes, I think we had this resolved at the 2014 TPAC. IIRC, it was 1s interval and excludes any headers to be consistent with the other definition.

**Comment by alvestrand** [comment]
Suggest adding a reference to TIAS from RFC 3890, with an 1-second conformance interval.

**Comment by stefhak** [comment]
Would that work also for webrtc-pc (maxBitrate)? Would be good to adopt the same definition in both places.
