### ISSUE TITLE
Consistent marker for "non-active" object?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#131]
We have a number of objects where stats go into a "frozen" mode once it's detached, deleted, no longer used or somethign like that.

Should there be a toplevel marker ("active default true" or something like that) so that we can filter all "inactive" stats consistently?

**Comment by alvestrand** [comment]
Note that the renaming problem touches on this one. #174.

**Comment by vr000m** [comment]
@alvestrand you mind taking a stab at this?

**Comment by henbos** [comment]
SGTM, it makes filtering easier.
