### ISSUE TITLE
Need DSCP information for outgoing RTP streams

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#133]
Need to know what DSCP is currently sent on the outgoing RTP stream.
Complication: Video currently is specced to have two DSCPs for certain priorities.

**Comment by vr000m** [comment]
may need them for the incoming streams as well.

**Comment by vr000m** [comment]
should use the hex values for the DSCP codepoints.

**Comment by lennart-csio** [comment]
IMHO this would require 9 counters to be added, one for each possible value (CS1, DF, EF, AF11, AF21, AF41, AF42, AF43, ) and an 'other'?

**Comment by taylor-b** [comment]
Since the receiver could receive _any_ codepoint, I don't think having 9 counters will scale. I'd suggest just having a map of DSCP codepoints to "packets received" counters. For example:

```
{ 
  34: 120, // I-frame packets, AF41
  36: 749  // P-frame packets, AF42
}
```

WebIDL has a "record type" for this purpose, apparently: https://heycam.github.io/webidl/#idl-record

But it's not in WebIDL 1.0...

**Comment by vr000m** [comment]
@fluffy wrote (July 28): 
> Just as a stab in the dark on how to do this ...
>
> Perhaps a table that had many packet where received for each DSCP that had been received in the last second. And a separate table for sent packets.
>
> Would something like that work ?

**Comment by lennart-csio** [comment]
i can make a proposal on this.
the record type idea would be preferred, imho. should we go with it, now that it is merged to webIDL https://github.com/heycam/webidl/pull/317 or should i use separate counters?

**Comment by alvestrand** [comment]
The record type sounds fascinating, and probably fit-for-purpose.
You can get an answer to "what's currently coming in" by querying twice and seeing what changed.
Adding a new type of stats value will probably break some generic code that traverses stats values, but you know what they say about omelets.
Please make a proposal using record<USVString, Integer> - seems we can't have integer keys in WebIDL :-(

**Comment by alvestrand** [comment]
TPAC result: Use "record" to implement Taylor's suggestion. @jan-ivar to check something and confirm to bug.

**Comment by vr000m** [comment]
TPAC17: @jan-ivar could you confirm if records can be used here. Otherwise we will go with Taylor's suggestion.

**Comment by jan-ivar** [comment]
Sorry for not getting back sooner, record seems fine.
