### ISSUE TITLE
Timestamp in the getStats

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-stats#134]
Do we need to clarify somewhere in the document that the timestamps in the objects are when the stats are generated and not the time when the getStats was called.

**Comment by fippo** [comment]
its probably worth mentioning along with how to calculate differences from counts.
Otherwise there will be a lot of divide-by-zero

**Comment by henbos** [comment]
Somewhat related: #174

**Comment by alvestrand** [comment]
Should be in the timestamp definition (which is in webrtc-pc)

**Comment by henbos** [comment]
We should have a discussion about caching. If you add a track and getStats you would expect it to contain stats for that track, but in general if you getStats it's OK to get cached stats.

**Comment by alvestrand** [comment]
Filed the caching issue as #177

**Comment by alvestrand** [comment]
PR for timestamp is https://github.com/w3c/webrtc-pc/pull/1039
