### ISSUE TITLE
Need DSCP information for incoming RTP streams

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#135]
This is different than for outgoing ( #133) , because it's observing the result of network mangling rather than observing what the application tries to set.

Both are interesting, and could go into the same field in stats.

**Comment by taylor-b** [comment]
I'm not sure if it's possible for the application to actually get this information though. Is there any OS that gives you received DSCP values in user mode? I'm not finding anything.

**Comment by alvestrand** [comment]
I think that on Linux, you can get it using recvmsg(2) on an UDP socket and inspecting the msghdr structure for a TOS byte, which you will have to enable with setsockopt(IP_RECVTOS). But this is from searching stackoverflow, not from writing code, so YMMV.

**Comment by taylor-b** [comment]
That's definitely what [the documentation](http://man7.org/linux/man-pages/man7/ip.7.html) indicates; don't know how I missed that. Ok, so this issue is still valid.

**Comment by alvestrand** [comment]
See #133 for details on how to solve.
