### ISSUE TITLE
RTCCodecStats.implementation... per-codec, per-stream?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#143]
Which codecs are supported and negotiated give one set of RTCCodecStats.

In practice there may be multiple implementations, e.g. hardware and software, for the same codec. Which implementation is used may even change during the call, e.g. there's problem with the hardware encoder so we fall back on the software one. It's conceivable that one stream uses one implementation and another stream uses another implementation of the same codec if there is only hardware problems on one of the streams.

Do we create one RTCCodecStats per implementation and update the RTCRTPStreamStats.codecId to point to the one with the implementation used, or do we move the codec implementation to RTCRTPStreamStats?

**Comment by alvestrand** [comment]
The "implementation" is meaningless without knowing the codec, I think. We will also find that different implementations have different parameters (for instance, most Mac hardware H.264 codecs support HIgh Profile, which will be indicated in codec.parameters).

So it belongs with the codec stats, conceptually.
I'd create a codec stat for every used implementation, and make the RTCRTPStreamStats.codecId point to the corresponding codec stat as of the time of the call.

Moving it to streamStats might be easier, but doesn't pass the "smell test" for me.

**Comment by henbos** [comment]
But we should also have one RTCCodecStats for each codec listed in the SDP? Including ones where the implementation used has not been decided yet.

If we want to avoid creating every encoder/decoder to find out if they have an implementation name, or refactor so that this information is known before creation, we could have the implementation member not specified until the first time an implementation is known and update it, then subsequently if a new implementation is used for the same codec we create a new RTCCodecStats with a new ID.

**Comment by henbos** [comment]
Considering you don't have control over the implementation used when negotiating/invoking webrtc APIs (correct?), we shouldn't go out of our way to list every possible implementation before usage unless that is easy to do?

**Comment by henbos** [comment]
Implementation details (about "implementation") aside, it belongs to RTCCodecStats, so closing this issue.

**Comment by CapOM** [comment]
See 'implementation' below: 

7.2.  RTCCodecStats dictionary
    dictionary RTCCodecStats : RTCStats {
      unsigned long payloadType;
      RTCCodecType  codecType;
      DOMString     transportId;
      DOMString     mimeType;
      unsigned long clockRate;
      unsigned long channels;
      DOMString     sdpFmtpLine;
      DOMString     implementation;
    };
