### ISSUE TITLE
Difference between 'Id' and 'Identifier' fields

### ISSUE THREAD

**Issue by na-g** [w3c/webrtc-stats#147]
It seems that the difference between fields ending in 'Id' and fields ending in 'Identifier', is that former refers to other stats objects, and the later refers to the objects described by stats.  Does 'Identifier' need a nomenclature definition like 'Id' has in section 4.1, "Guidelines for design of stats objects"?

**Comment by alvestrand** [comment]
It may deserve a note in the description of "id". It's not intended to be magical, just a good name when "id" is occupied by its special meaning.

**Comment by vr000m** [comment]
Explains why we have trackIdentifier, ssrcIdentifier, and datachannelIdentifier

**Comment by henbos** [comment]
"Id" and "Ids" are reserved for stats objects identifiers (stats dictionary objects) and are mentioned in the stats guidelines.
"Identifier" and "Identifiers" are used for object identifiers (non-stats dictionaries). We could add a paragraph in the guidelines sections about this.

**Comment by alvestrand** [comment]
#264 filed.
