### ISSUE TITLE
Stat for how much time it takes to encode video

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#150]
The non-standardized Chromium getStats contains the following stats:
```
// The average encode time in ms (video).
ssrc.googAvgEncodeMs

ssrc.googEncodeUsagePercent
```
These can be used to estimate "how fast the fan is spinning" and be used as an indicator that you might want to to lower capture resolution.

Is this useful? Should we standardize it or something similar?
Averages are discouraged, and time is typically expressed as double seconds. How about a `double totalEncodingTime` in RTCMediaStreamTrackStats that is the total time, in seconds, that has been spent on encoding video for that track?

**Comment by henbos** [comment]
Speaking of "how fast is the fan spinning", there is also ssrc.googCpuLimitedResolution with nothing similar in the spec.

**Comment by vr000m** [comment]
I assume, totalEncodingTime / totalFramesEncoded would give the averageEncodingTime.

**Comment by vr000m** [comment]
Related to the other metrics, `googEncodeUsagePercent` and `googCpuLimitedResolution` are not well defined. If they were definitions that we could point to, it would be much easier. Absent that the definitions need to be very well articulated, so that they cannot be misinterpreted.

**Comment by henbos** [comment]
Yes, you can calculate average encode time yourself using `totalEncodingTime` and `framesEncoded`. Hang on, should `totalEncodingTime` belong to `RTCOutboundRTPStreamStats` (where `framesEncoded` lives) and not `RTCMediaStreamTrackStats`? I think so.

Whenever the answer to the question "is there encoding going on at this moment?" is yes the `totalEncodingTime` should be increasing with time passing. You resume the clock when the pipeline hands over an image buffer to the encoder and you pause the clock when the encoder hands over the encoded data to the rest of the pipeline.

**Comment by henbos** [comment]
I'm assuming an encoder only works with one frame at a time.

**Comment by henbos** [comment]
@stefanholmer How is `googAvgEncodeMs` calculated? Can we say that `totalEncodingTime` starts increasing when an image is handed to the encoder and paused when the encoder spits out data for that frame? Or do we have to take other things into account like queuing of buffers or something.

**Comment by stefanholmer** [comment]
Talk to asapersson@.

**Comment by henbos** [comment]
OK, so googAvgEncodeMs is measured starting from a frame entering the encoder and stopping after packetization, over a sliding window.

For a standardized version of this stat I think it makes more sense to start and stop the clock around the encoding of each frame, this is more straight-forward and clear what it means.

**Comment by alvestrand** [comment]
This should be "sum of encoder time", to be divided by frame count.
Can encoding be parallel in such a way that the sum of encoder time is > real time?

**Comment by alvestrand** [comment]
Important to be clear about: When the timer starts and when the timer stops (current Chrome implementation includes packetization in the process).
