### ISSUE TITLE
Stat for audio playout delay

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#151]
The non-standardized Chromium getStats contains the following stats:
```
// The total audio playout delay, including algorithmic, jitter buffer,
// and soundcard delay, in milliseconds.
ssrc.googCurrentDelayMs
```
Is this useful? Should we standardize it or something similar? Double seconds is the preferred unit.
Should we add `double audioDelay` to RTCMediaStreamTrackStats?

**Comment by alvestrand** [comment]
This is related to the need that was the basis for https://github.com/alvestrand/webrtc-framelog
The critical part of a definition here are the measurement points: At what point do we start the clock running, and at what point do we say "the delay is completed"?

Side point: If we can't get exact values (such as delays in the audio subsystem after the samples have been handed over), should we add an estimate into the delay, or use the last time at which we were able to measure time?

**Comment by vr000m** [comment]
I agree with @alvestrand that the delay measurements need exact details on when the clock starts and when the clock stops. There are several components in this calculation: the more difficult one is soundcard delay, although the algorithmic and jitter buffer can be measured very accurately. 

I would start with something that defines the sum of the playout algorithm+jitter buffer. Both the current (which could be the last played sample or the delay if there were a current sample to play) and a long-term total (based on each frame).

**Comment by henbos** [comment]
This may or may not be related to #158 which discusses timestamps for the playout of audio and video.

**Comment by henbos** [comment]
+@hlundin

Is this right?
+ **Jitter buffer delay**: The currently expected delay due to jitter buffer, which is the difference between the timestamp of the latest audio sample coming out of the jitter buffer and the timestamp it had when it was inserted into the jitter buffer.
+ **Sound card delay**: This has to do with the size of the buffer we feed to the sound card, since the entire buffer has to be filled up before fed to the sound card. The delay is (_number of samples that fit into the buffer_ - 1) * (_the time it takes to play one sample_).
+ **Algorithmic delay**: _???_

If we get these right we can define `RTCMediaStreamTrackStats.audioDelay` as the sum of these delays.

**Comment by henbos** [comment]
Do we want?
- Jitter buffer delay
- Decode buffer delay
- Sound card buffer delay

**Comment by vr000m** [comment]
Jitter buffer delay: is the delay between the first packet belonging to an audio/video frame entering the jitter buffer and the complete frame exiting the jitter buffer. 

Decode buffer delay: is the delay between a compressed audio/video frame entering the decoder and a complete uncompressed signal corresponding to the compressed frame exiting the decoder.

Does  the above make sense?

**Comment by hlundin** [comment]
The terms "jitter buffer delay" and "decode buffer delay" can be interpreted differently depending on implementation details. For instance, given the implementation in NetEq (webrtc.org), I would not define decode buffer delay like @vr000m above, and the two are very tightly coupled.

I would suggest to have one jitter buffer delay, defined as the delay between the first packet belonging to an audio/video frame entering the jitter buffer and the complete frame being sent for rendering.

**Comment by hlundin** [comment]
Picking up the discussion deferred here from #146.

_What did the non-standard accelerate and pre-emptive expand rates try to quantify?_ Possibly audible stretching and compression (in the time domain). The underlying reason for the signal operation is probably less interesting, but usual cases are A/V syncing and meeting target buffer level (i.e., when high or low water marks are passed).

We need separate metrics for increase and decrease, since a net zero doesn't mean that no potentially audible operations were performed.

This does _not_ capture any delay changes resulting from the packet-loss concealment operation (see #152).

**Comment by aboba** [comment]
Is it possible to separate out the JItterBuffer delay?
