### ISSUE TITLE
Stat for how many audio stream packets are expanded when packets are lost (and lost and the user is speaking)

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#152]
The non-standardized Chromium getStats contains the following stat:
```
// Fraction of packets that are expanded (synthesized) when we detect
// that the user is speaking.
ssrc.googSpeechExpandRate
```
What exactly does this mean? Is this useful? Should we standardize it or something similar? Sums and counters are preferred over rates.
RTCInboundRTPStreamStats already have various packet counters. Should we add another `unsigned long packetsSpeechExpanded`?

**Comment by henbos** [comment]
There is also
```
// Fraction of data out of secondary decoding, including FEC (Forward
// Error Correction) and RED (Redundant Encoding).
ssrc.googSecondaryDecodedRate
```
Is this related?

**Comment by henbos** [comment]
And
```
// Fraction of audio samples preemptively expanded (synthesized by
// slowing down) when the jitter buffer size increases.
ssrc.googPreemptiveExpandRate
```
-> `unsigned long packetsPreemptivelyExpanded`?

**Comment by henbos** [comment]
+@hlundin
If I understand correctly, Chromium has `googExpandRate` which is the fraction of audio filled to conceal packet-loss and `googSpeachExpandRate` which is the same but only applicable when there is something audible to play. Meaning if we stop receiving any packets `googExpandRate` might be 100% whereas `googSpeachExpandRate` is not applicable (0%) after we have no audio.

How about?

> **RTCInboundRTPStreamStats._packetsExpanded_**
> The number of packets that have been inserted to conceal packet-loss.
> 
> **RTCInboundRTPStreamStats._packetsAudibleExpanded_**
> The number of packets that have been inserted to conceal packet-loss while there is something audible to play. If our buffers are emptied _packetsExpanded_ will keep increasing, but not _packetsAudibleExpanded_.

Rates can be calculated from `packets[Audible]Expanded / (packetsReceived + packetsLost)` (see other packets members that already [exist in spec](http://rawgit.com/w3c/webrtc-stats/master/webrtc-stats.html#dom-rtcinboundrtpstreamstats)). This is assuming `packetsLost` keeps increasing for muted streams, @vr000m do you know?

**Comment by vr000m** [comment]
There are hopefully no packets being sent for muted streams.

**Comment by vr000m** [comment]
+ number of audible samples concealed (could be in ms, could be events... anyway the concealment is extrapolated based on speech audio --> audible/speech needs to be defined some where. )
+ number of samples concealed (same as above. This concealed includes speech audio, noise generator, comfort sound,  silence, or anything)
+ number of concealment events.

The ratio of samples concealed/number of concealed events may give the idea if there was a large concealment event.

Is it interesting if the concealed packets were recovered. The issue is that the samples lost might affect the decoding of the next few samples (depending if the lost packet impacts the decoder state).

**Comment by hlundin** [comment]
I think I like the three bullets that @vr000m suggests above.

However, I think the "concealed packets were recovered" is quite vague. If we are interested in quantifying state-faults in the decoder, we should probably define something more direct for that. It is easy to know if the decoder was fed with continuous packets, or if there were any holes in the stream (causing state fault). This could be a counter: num non-continuous decode events.

**Comment by alvestrand** [comment]
Suggestion: Add the counts to MediaStreamTrackStats, with the comment that it only makes sense on inbound audio tracks.

We have to have a totalSamples count so that we have something to compare concealedSamples to.
