### ISSUE TITLE
Stat for target and actual encoding bitrate

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#155]
The non-standardized Chromium getStats contains the following stats:
```
// The actual bitrate the encoder is sending.
VideoBwe.googActualEncBitrate
// The configured target bitrate for the encoder.
VideoBwe.googTargetEncBitrate
```
Is this useful? Should we standardize this or something similar? I'm not sure if this is per-track or the sum of all tracks.

The RTCMediaStreamTrackStats already has configured framerate (framesPerSecond) and actual framerate (calculated from multiple framesSent or framesRecieved).
Should we add `double encodedBytesPerSecond` and `unsigned long long encodedBytes`?

**Comment by alvestrand** [comment]
The actualEncBitrate should be computable from RTCRTPStreamStats.bytesSent.

The googTargetEncBitrate should either be the same as RTCIceCandidatePairStats.availableOutgoingBitrate or the same as sum(RTCOutboundRTPStreamStats.targetBitrate) for all (video?) tracks, depending on how it's defined.

In either case, it should be computable from existing values, so I don't see a reason to add them.

(Once we have all the stats mentioned above wired up, we could write a test to run old and new stats against each other, checking that the stats (or the stats we can compute from them) are ~equal. If they aren't, we have the definitions wrong.)

**Comment by henbos** [comment]
SGTM. Closing this issue and flagging that googActualEncBitrate and googTargetEncBitrate will be removed unless this is re-opened.
