### ISSUE TITLE
Stat for camera input framerate of local video tracks

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#159]
RTCMediaStreamTrackStats.framesPerSecond, frames[Sent/Received] and RTC[In/Out]boundRTPStreamStats.frames[Encoded/Decoded] are available to find out the configures and actual (degraded) framerates.

However, there is no stat for the actual camera input framerate. This can heavily vary due to lighting conditions, and it's useful to distinguish between degradation due to device/environment and due to the rest of the pipeline/network.

Should we add `unsigned long framesCaptured` to local (`isRemote=false`) `RTCMediaStreamTrackStats`?

**Comment by alvestrand** [comment]
Since this is only valid for camera-sourced tracks, and framesReceived is only valid for remote-sourced tracks, perhaps we should reuse framesReceived?
Both metrics seem to be "frames entering the pipeline", so we could define it as that.

**Comment by henbos** [comment]
SGTM

**Comment by vr000m** [comment]
framesReceived for both cases would be a bit confusing. We would rename it to framesCaptured in our UI, because it would be recurring explanation that the two metrics are measured at the beginning of the media pipeline, one from the device (at the sender) and the other from the network (at the receiver).

**Comment by henbos** [comment]
Sidenote: It would be worth clarifying that framesReceived is number of frames after the jitter buffer when updating the description for framesReceived.

**Comment by henbos** [comment]
This relates to #141 (but counter for averages rather than current rate).
