### ISSUE TITLE
Definitions from MSE need re-targeting

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#161]
The following stats:

- framesDecoded
- framesDropped
- framesCorrupted

are defined with reference to section 5 of [MEDIA-SOURCE], which is said to be https://www.w3.org/TR/media-source/

However, section 5 of that document doesn't have any such counters.

There was an earlier set of metrics in the 20160705 version, as part fo the VideoPlaybackQuality object, but this has disappeared in later versions:

https://www.w3.org/TR/2016/CR-media-source-20160705/#videoplaybackquality

These definitions need retargeting.

**Comment by alvestrand** [comment]
According to Appendix A of the spec, tehse are now in [MEDIA-PLAYBACK-QUALITY], which is a WICG proposal: https://wicg.github.io/media-playback-quality/

Definitions at https://wicg.github.io/media-playback-quality/#videoplaybackquality-interface

The stability of this reference needs considering.

**Comment by vr000m** [comment]
AFAIR, there was not enough agreement on the metrics in the related WG. I know FF implements the above metrics (were part of MSE spec): @jan-ivar could you shed some light on this?

**Comment by jan-ivar** [comment]
@vr000m  We only implement `droppedFrames` at the moment [AFAIK](https://jsfiddle.net/jib1/moz71L7h/). Note the spelling is different, though we are in the process of [updating names](https://bugzil.la/1335967). Cc @na-g

**Comment by jan-ivar** [comment]
Talking about stats. I don't know about MSE.

**Comment by alvestrand** [comment]
@mounirlamouri can you comment on this one?
Current WICG draft has corruptedVideoFrames, totalVideoFrames and droppedVideoFrames.

**Comment by alvestrand** [comment]
pinging @mounirlamouri again.
This is about the stability of section 4 of the media-playback-quality spec, VideoPlaybackQuality counter definitions.

**Comment by alvestrand** [comment]
After editors discussion: It seems we can carry our own definitiosn (and be RTP-aligned) rather than referring to the MSE ones.

**Comment by vr000m** [comment]
related to #278
