### ISSUE TITLE
Add stat to RTCTransportStats for ICE role (controlling or controlled)

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-stats#162]
Seems like it could be a useful piece of information.

**Comment by vr000m** [comment]
Can the role change after an ICE restart?

**Comment by taylor-b** [comment]
Yes; RFC5245 says that ICE roles are re-determined after an ICE restart, meaning ICE roles will switch if the offer/answer direction is reversed. Though this was removed in ICEbis.

Also, it's possible to have a role conflict in third-party call control scenarios (for example, when both endpoints think they're the offerer). This is a resolved by a tiebreaker attribute, and results in one of the endpoints switching to the necessary role.
