### ISSUE TITLE
RTCIceCandidatePairStats.writable/readable: redundant?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#163]
`writable` is "Has gotten ACK to an ICE request."
Isn't this the same as `responsesReceived > 0`? `responsesReceived` is "Represents the total number of connectivity check responses received."

`readable` is "Has gotten a valid incoming ICE request."
Isn't this the same as `requestsReceived > 0`? `requestsReceived` is "Represents the total number of connectivity check requests received (including retransmissions)."

If so I propose we remove `writable` and `readable`.

**Comment by henbos** [comment]
Though writable/readable are mandatory to implement, responsesReceived/requestsReceived are not. If so maybe they should become mandatory instead.

**Comment by alvestrand** [comment]
If writable and readable are defined as above, it means that they can never become false. This seems contrary to being useful - in Real Life, connectivity can be lost after initial success.

**Comment by alvestrand** [comment]
Should point to the definition of "it's usable" in the ICE spec (if there is one).

**Comment by alvestrand** [comment]
@taylor-b please advise.

**Comment by vr000m** [comment]
Probably, the app needs to know if the connectivity is still available. the non-zero suggest that the connectivity was available at some point.

**Comment by taylor-b** [comment]
@alvestrand Maybe `writable` should be defined as "has received a binding response, *and* consent has not expired"? It would be odd if `writable` were `true` after consent expires.

Though we could also just add a `consentExpired` field.
