### ISSUE TITLE
RTCRTPStreamStats: associateStatsId vs remoteId

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-stats#17]
http://w3c.github.io/webrtc-stats/#streamstats-dict*
defines associateStatsId, example 1 uses (and Firefox implements)
```
remoteNow = currentReport[now.remoteId];
```
@jan-ivar @alvestrand?

**Comment by alvestrand** [comment]
This was changed to associateStatsId because it wants to be symmetrical; currentReport[currentReport[now.associateStatsId].associateStatsId] === now.

It looks weird to take the remoteId of a remote track and have it be the local ID.

Suggest keeping the new name.

**Comment by fippo** [comment]
yeah, I came up with a similar rationale, 'remote' has too many implications. Will file bugs (or make PRs if I figure out the w3c IPR policy) for -pc

**Comment by alvestrand** [comment]
fippo, do you need "invited expert" status? The IPR policy is "if you're a WG member, you've agreed to the IPR rules for this specific technology, so we're happy to take your contribution".

Closing this issue; the name may not be perfect, but it's better than "remote".
