### ISSUE TITLE
Packets or frames discarded on send?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#178]
Chromium's non-spec compliant getStats returns `googCandidatePair.packetsDiscardedOnSend` which are the "number of outgoing packets discarded due to socket errors" (a bit vague).

`RTCIceCandidatePairStats` has bytesSent and #172 discusses adding packetsSent (#173 similar discussion for `RTCTransportStats`). Should we also add `packetsDiscardedOnSend`?

If this makes sense as a per-frame counter instead, `RTCMediaStreamTrackStats` already has `framesDropped`on receive-side, it or similar could be used on the send-side.

**Comment by vr000m** [comment]
The question would be why they were discarded?
+ because the local socket buffer was full?
+ because the congestion control realised that the available bandwidth (or bits that get be sent in the target window) is lower than the current encoded frame size?
+ or something else?

cc: @lennart-csio

**Comment by alvestrand** [comment]
Probably means "we had a packet we wanted to send, but we did not send it". Discarded frames wouldn't increment the counter, UDP send() failure and "buffer is full / token bucket is empty" would cause the counter to increment.
