### ISSUE TITLE
Stats report for RTCRtpContributingSource objects

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-stats#183]
I'd like to propose adding a stats object that mirrors the `RTCRtpContributingSource` object in the RTP media API. At minimum, it could have the same information as `RTCRtpContributingSource` does, with an ID to relate it to the inbound stream stats:

```
dictionary RTCRTPContributingSourceStats {
    DOMString           rtpStreamStatsId;
    DOMHighResTimeStamp timestamp;
    unsigned long       source;
    byte                audioLevel;
    boolean             voiceActivityFlag;
};
```

It may also be useful to also add packet counts, to tell how often a source contributed to the stream.

@vr000m, @alvestrand: thoughts? If you don't see any issue with this, I can write a PR.

**Comment by vr000m** [comment]
same definition for audioLevel as in RTCMediaStreamTrackStats? 
source is csrcId?

**Comment by alvestrand** [comment]
Hm. Not sure of the great value, but it makes sense to snapshot it.

The packet counts seems like the most valuable information - number of packets that had this SSRC in its CSRC list.
"source" should be "contributorSsrc" or something.
"timestamp" should be covered by inheriting from RTCStats.
I think the "audioLevel" should be decoded into the same representation as used elsewhere in the stats (linear double).

Implementation would be optional, so it'sworth adding to see if anyone adds it.
