### ISSUE TITLE
Reuse of "inbound-rtp" and "outbound-rtp" for RTCP is confusing.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-stats#189]
The `isRemote` overload of `"inbound-rtp"` and `"outbound-rtp"` is just confusing. It invites surprise and bugs to anyone trying to enumerate stats (scripts end up reading wrong data without knowing it!)

I can't think of a single use-case where enumerating by type alone is not wrong.

It's also false symmetry: both dictionaries have members which existence depend on `isRemote`:
 * [RTCOutboundRTPStreamStats](http://rawgit.com/w3c/webrtc-stats/master/webrtc-stats.html#outboundrtpstats-dict*) has `framesEncoded` (local-only), `remoteTimestamp` (remote-only),
 * [RTCInboundRTPStreamStats](http://rawgit.com/w3c/webrtc-stats/master/webrtc-stats.html#inboundrtpstats-dict*) has `framesDecoded` (local-only), `roundTripTime` (remote-only).

These absences break down easily by type, i.e. *never* appear in subsequent calls where missing.

## Proposal

(***Edited*** *to include feedback in comments below. Thanks Harald!*)

Remove `isRemote`, and round out the two rtp types with two more for rtcp instead:
 * "outbound-rtp"
 * "inbound-rtp"
 *  **"remote-inbound-rtp"** (formerly "inbound-rtp" with `isRemote == true`)
 *  **"remote-outbound-rtp"** (formerly "outbound-rtp" with `isRemote == true`)

Define discrete dictionaries for the four types (in inheritance rather than corrresponding order):
```js
dictionary RTCSentRTPStreamStats : RTCRTPStreamStats {
    unsigned long       packetsSent;
    unsigned long long  bytesSent;
};

dictionary RTCOutboundRTPStreamStats : RTCSentRTPStreamStats {
    double              targetBitrate;
    unsigned long       framesEncoded;
};

dictionary RTCRemoteOutboundRTPStreamStats : RTCSentRTPStreamStats {
    DOMHighResTimeStamp remoteTimestamp;
};
```

```js
dictionary RTCReceivedRTPStreamStats : RTCRTPStreamStats {
    unsigned long      packetsReceived;
    unsigned long long bytesReceived;
    unsigned long      packetsLost;
    double             jitter;
    double             fractionLost;
    unsigned long      packetsDiscarded;
    unsigned long      packetsRepaired;
    unsigned long      burstPacketsLost;
    unsigned long      burstPacketsDiscarded;
    unsigned long      burstLossCount;
    unsigned long      burstDiscardCount;
    double             burstLossRate;
    double             burstDiscardRate;
    double             gapLossRate;
    double             gapDiscardRate;
};

dictionary RTCInboundRTPStreamStats : RTCReceivedRTPStreamStats {
    unsigned long      framesDecoded;
};

dictionary RTCRemoteInboundRTCPStreamStats : RTCReceivedRTPStreamStats {
    double             roundTripTime;
};
```
## Benefit:

No need to read prose anymore to see what's where, and it simplifies [usage](https://blog.mozilla.org/webrtc/fiddle-of-the-week-await/) as well:
```js
  let html = "", stats = await pc.getStats();
  for (let stat of stats.values()) {
    // if (stat.isRemote) continue; <--- don't need this line anymore!
    switch (stat.type) {
      case "outbound-rtp": {
        html += dumpOutbound(stat) + "<br>";
        let rtcp = stats.get(stat.remoteId);
        if (rtcp) html += "RTCP " + dumpInbound(rtcp) + "<br>";
        break;
      }
```
Thoughts?

**Comment by alvestrand** [comment]
Hm.

We replace 3 types in an 1-level tree + a variable with 7 types in a 2-level tree. We go from 2/3 to 4/7 of the types being instantiable.

Would outbound-rtp, remote-outbound-rtp, inbound-rtp, remote-inbound-rtp be equally readable?
(class names ReceivedRTPStreamStats, RemoteReceivedRTPStreamStats and so on)
These stats aren't reporting on RTCP, they're reported using RTCP.

**Comment by jan-ivar** [comment]
@alvestrand Dictionaries can't be instantiated; their makeup is hardly discernible in JS, so I'm not worried about that. - I'm happy to bikeshed on names, though. I think you have a point there.

**Comment by taylor-b** [comment]
I like the concept; `isRemote` was pretty confusing to me personally. I think the names could be improved though; both "inbound-rtcp" and "outbound-rtcp" would both be derived from inbound RTCP packets (right?), so it's not intuitive to me which is which.

**Comment by jan-ivar** [comment]
@taylor-b FWIW my thinking behind those names were rtp=local, rtcp=remote:
* "outbound-rtp" - local info about our outbound connection,
* "outbound-rtcp" - remote info (from RR report) about our outbound connection,
* "inbound-rtp" - local info about our inbound connection,
* "inbound-rtcp" - remote info (from SR report) about our inbound connection.

I'm happy to adopt the naming @alvestrand suggests. Either way.

**Comment by jesup** [comment]
I also like getting rid of isRemote

**Comment by jan-ivar** [comment]
@alvestrand To me, "remote-outbound-rtp", sounds like the rtp leaving the remote, coming to us, which this isn't. Maybe being explicit would help:

* "outbound-rtp" - local info about our outbound connection,
* "outbound-rtp-rr" - remote info (from RR report) about our outbound connection,
* "inbound-rtp" - local info about our inbound connection,
* "inbound-rtp-sr" - remote info (from SR report) about our inbound connection.

?

**Comment by alvestrand** [comment]
@jan-ivar "To me, "remote-outbound-rtp", sounds like the rtp leaving the remote, coming to us" - yes, that's excactly what I want it to be (outbound from the remote), so that means it's a good name (I think). It happens to be delivered over RTCP RRs and SRs, with some XRBLOCKs thrown in for good measure, but I don't see why we should name the delivery mechanism in the name.

**Comment by jan-ivar** [comment]
I worry half the audience will think it means "the remote side of this outbound connection".

**Comment by jan-ivar** [comment]
"outbound-rtp-receiver-report" and "inbound-rtp-sender-report" seemed a little verbose.

**Comment by jan-ivar** [comment]
I believe @alvestrand is suggesting (keeping the same order for comparison):

* "outbound-rtp" - local info about our outbound connection,
* "remote-inbound-rtp" - remote info (from RR report) about our outbound connection,
* "inbound-rtp" - local info about our inbound connection,
* "remote-outbound-rtp" - remote info (from SR report) about our inbound connection.

**Comment by alvestrand** [comment]
These aren't connections, of course - they're streams.
The last set of suggested names are a smaller change from what we have - they move the "isRemote" flag from an attribute to a name prefix (and allow us to use the dictionary hierarchy for documentation).

That seems to make sense to me.
Are we bikeshedded enough?

**Comment by alvestrand** [comment]
@aboba do you think this is a breaking change we shouldn't do, or should we Just Do It?
(Chrome hasn't implemented the remote objects yet, and since Jan-Ivar's arguing for the change, I assume that Firefox is cool with it).

**Comment by fluffy** [comment]
As far as stats go, I would much rather get them "right" even if that meant breaking changes.

**Comment by jan-ivar** [comment]
`isRemote` would be falsy once removed, so finding *local* stats wouldn't break.

For *remote* stats in Firefox, I hope most users obtain it through the `remoteId` (aka `associateStatsId` in the spec) shown in my [first comment](https://github.com/w3c/webrtc-stats/issues/189#issue-216190363). If so, then this change won't affect them. If they instead try to enumerate for the remote stats the old way, then the new type names mean they won't find them. Not great, but beats finding rtcp data and thinking it is local data.

(Keeping `remoteId` as an alias for `associateStatsId` for a good while is a separate issue, but a simple thing for us to do. We'll make it non-enumerable so it won't show up but still work.)

**Comment by jan-ivar** [comment]
Of course with discrete dictionaries, the symmetrical `associateStatsId` could become `remoteId` and `localId`...

**Comment by jan-ivar** [comment]
I've updated the proposal in the [OP](https://github.com/w3c/webrtc-stats/issues/189#issue-216190363) with the names Harald proposed. PR coming up.

OK to add to tomorrow's slides?

**Comment by alvestrand** [comment]
@aboba @stefhak OK to present?

**Comment by jan-ivar** [comment]
@alvestrand I added my slide to the deck that was shared with and marked it tentative, in case there's time to discuss it at the end.
