### ISSUE TITLE
Issues raised in TAG review

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-stats#219]
see https://github.com/w3ctag/design-reviews/issues/148

**Comment by triblondon** [comment]
Hi @dontcallmedom, how are you?  Lovely weather here in London for the TAG F2F. We were doing some issue cleanup and wondered how you were getting on.  Hope all's well, wish you were here.

Love from the TAG.

**Comment by alvestrand** [comment]
Closed with #266
