### ISSUE TITLE
Need some way of getting an averaged audio level stat

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-stats#220]
`RTCMediaStreamTrackStats.audioLevel` only represents the level of the last encoded/decoded chunk of audio, or so I assume (may need to be clarified, see https://github.com/w3c/webrtc-stats/issues/193). So it's not useful for all use cases. If `getStats` is called at the wrong time, it may see an `audioLevel` of 0, just because it happened to be called during a blip of silence. The application may really be more interested in an average level over a certain time period.

The guideline for "averaged" stats is to provide "sum" and "count" fields, such that the application can compute an average over any time interval by dividing "sum/count" for that interval. This is a bit more complicated for audioLevel, since it's based on the root mean square (RMS) of audio samples. So we would have to do something like provide a sum of "mean square X sample duration" (say, "totalAudioEnergy"), and a "totalDuration", and let the application compute the average audio level as "sqrt(totalAudioEnergy)/totalDuration".

**Comment by taylor-b** [comment]
> average over what? 

Averaged over whatever period the application desires; at least, if we're following the existing guidance for stats that need averages.

> can we measure energy for audible samples and then use the corresponding duration (for example, totalAudibleSamplesDuration) or estimate it from audibleSamples and packetization interval.

This sounds pretty similar to what I'm suggesting in PR #221. Did you look at it yet?

**Comment by vr000m** [comment]
I didn't relate the two, perhaps having looked at the two at different times. The issue talks about TotalDuration and the PR totalSamples sent or received.

**Comment by taylor-b** [comment]
I was initially thinking a duration would make sense as a denominator. But then I noticed there was already `totalSamplesSent` and `totalSamplesReceived`, and thought maybe they could be used for this purpose. It would produce incorrect results if the sampling frequency changes, though.

**Comment by vr000m** [comment]
Any further thoughts if we want to use duration or samples?

Is it realistic that the sampling frequency changes mid-call for the same SSRC?

**Comment by taylor-b** [comment]
Might as well use duration to be safe. I updated the PR, can you take a look?
