### ISSUE TITLE
Audio/Video sync follow-up

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#222]
This is a follow-up to: #158 

[estimatedPlayoutTimestamp](http://rawgit.com/w3c/webrtc-stats/master/webrtc-stats.html#dom-rtcmediastreamtrackstats-estimatedplayouttimestamp) was added, but estimatedCaptureTimestamp was not due to being able to estimate the time of the capturer by taking the `estimatedPlayoutTimestamp + rtt/2`.

We have rtt based on STUN pings in [RTCIceCandidatePairStats.currentRoundTripTime](http://rawgit.com/w3c/webrtc-stats/master/webrtc-stats.html#dom-rtcicecandidatepairstats-currentroundtriptime), or based on RTCP Receiver Report in [RTCRemoteInboundRTPStreamStats.roundTripTime](http://rawgit.com/w3c/webrtc-stats/master/webrtc-stats.html#dom-rtcremoteinboundrtpstreamstats-roundtriptime). Will the per-SSRC RTCP RR roundTripTime suffice for `rtt/2`?

The current definition of estimatedPlayoutTimestamp is that we extrapolate the timestamp by the time passed since the last frame/sample was playable, the point of this was to get a timestamp that increases in-between frames/samples but it causes a problem: If the renderer freezes or frames/samples stop coming the extrapolation hides this fact until the next time a frame/sample is playable. We should update the definition such that we extrapolate the timestamp from the last known NTP timestamp up to the last playable timestamp. We should not extrapolate beyond playable frames/samples.

**Comment by henbos** [comment]
If we need a new metric to get a useful version of `estimatedCaptureTimestamp` then we need to come up with a definition for how to calculate it beyond available rtt stats.

@icydragons @stefanholmer @vr000m

**Comment by henbos** [comment]
Related: [jitterBufferDelay](http://rawgit.com/w3c/webrtc-stats/master/webrtc-stats.html#dom-rtcmediastreamtrackstats-jitterbufferdelay) (should maybe be renamed) could be similar to playout delay

**Comment by henbos** [comment]
In a meeting offline, me, @icydragons and @vr000m discussed issues around playout delay, delay between capture and sending packets, NTP timestamps not being in-sync between clients and the possibility of sending local delay measurements as part of RTCP Receiver Report metrics.

**Comment by henbos** [comment]
It seems that non-standards stats calculated end-to-end delay with estimates based on RTT, https://codereview.webrtc.org/2946413002/. It uses an RTP header extension to signal timestamps from all over the pipeline. Exposing all of these timestamps would seem more suitable for @alvestrand's WebRTC Frame Event Logging API than getStats since it's per-frame, but the fact that E2E is calculated based on RTT might mean that we can do something like we've previously discussed here? Is the RTP header extension for timing frames needed?

**Comment by henbos** [comment]
@ilyanikolaevskiy what are the minimal set of components necessary to calculate E2E delay?

**Comment by ilyanikolaevskiy** [comment]
@henbos that rtp header extension and timing frames are needed for debugging purposes. The idea is to have detailed history of delays for a certain frame for all components of webrtc. Theoretically, it could be done without the extension - send-side webrtc should report its half, receive-side should report it's side, then peers exchange information via out of band signaling. However, having the extension simplifies implementation and gives more flexibility (e.g. having delay of in-network rtp processors, high granularity reporting). The focus here is not on the E2E delay, but on the full details of all the delays.

Considering E2E delay - the requirement is to have RTT estimated via rtcp messages. I don't know all the details, but looks like it was done via RR rtcp messages. Also, if rtrr/dlrr is enabled it also works for sending-only clients. 

Also, we a currently investigating issue, where many calls have no estimations for E2E delay. What exactly went wrong there, we don't know yet.

**Comment by henbos** [comment]
@icydragons How do we get RTT from a receiving client?

**Comment by henbos** [comment]
https://tools.ietf.org/html/rfc3611#section-4.4

**Comment by henbos** [comment]
If we support XRs then that has to be negotiated with SDP apparently. Do we do that? @ilyanikolaevskiy do you know?

**Comment by henbos** [comment]
And do we need the capture RTP timestamp in remote clock?

**Comment by alvestrand** [comment]
Seems discussion is converging on per-frame timestamp exposure being a matter for https://github.com/alvestrand/webrtc-framelog or its successors (if any).

RTT is already exposed.

Can we close this issue in webrtc-stats?

**Comment by icydragons** [comment]
I don't quite see how rtt and framelog will get us A/V sync. Can you explain?

**Comment by henbos** [comment]
@icydragons Can you (or someone who works with implementing these stats) write a design doc for this stuff? I suspect we can write PRs for the provisional stats document, but we need the current 
design documented to move forward.

**Comment by alvestrand** [comment]
Moved to the provisional stats document for now.
