### ISSUE TITLE
jitterBufferDelay vs playoutDelay

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-stats#223]
In #217, we defined jitterBufferDelay based on the discussion in https://github.com/w3c/webrtc-stats/issues/151.

it is currently defined as: 

```
 It is the total time each audio sample or video frame takes from the time it
is received to the time it is rendered. The delay is measured from the time
the first packet belonging to an audio/video frame enters the jitter buffer
to the time the complete frame is sent for rendering after decoding. The average 
jitter buffer delay can be calculated by dividing the <code>jitterBufferDelay</code>
with the <code>framesDecoded</code> (for video) or <code>totalSamplesReceived</code> (for audio).
```

There was some feedback on renaming this as `playoutDelay`.

**Comment by henbos** [comment]
Any thoughts @icydragons @stefanholmer?

**Comment by vr000m** [comment]
closing this, since there are no comments on this.

**Comment by henbos** [comment]
SGTM I think playoutDelay is misleading, that could be a different stat if need be.

**Comment by Tilakv** [comment]
I am a bit not clear about googJitterBufferMs. We have a freeviewpoint streaming webrtc framework, and I have tested it over experimental network, and found out that the link attributes (changing the RTT of the link) affects the googJitterBufferMs and the googTargetDelayMs to the RTT of the link. The minimum googJitterBufferMs observed in this case was 40msec and increases to 60~70msec, when the link RTT is changed to 40msec. 

The question is, is the jitterBuffer related to client Buffer (time when video frame enters the client buffer and leaves the client buffer) or the time when the video frame is sent from one peer and successfully decoded and played at the client?

Thanks,
Tilak 
[WebRTC Internals_new.pdf](https://github.com/w3c/webrtc-stats/files/3569887/WebRTC.Internals_new.pdf)
