### ISSUE TITLE
RTCPeerConnectionStats: should they contain a link to transports?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-stats#227]
from https://github.com/webrtc/samples/pull/910

where I am currently using a forEach loop to find the transport, making the assumption that there is only one transport which is not valid when not using bundle.

I would rather use https://w3c.github.io/webrtc-stats/#pcstats-dict* (there can be only one) as the entry point and then follow the breadcrumbs of transportIds to https://w3c.github.io/webrtc-stats/#transportstats-dict*

Or am I missing a way? @vr000m @henbos @jan-ivar

**Comment by fippo** [comment]
I thought that this would be a nice way to find the transports:
```
pc.getStats().then(r => r.filter(report => report.type === 'transport'))
.then(transports => console.log(transports))
```
but unfortunately a maplike doesn't do filter or find :-/

**Comment by jan-ivar** [comment]
> https://w3c.github.io/webrtc-stats/#pcstats-dict* 

Side-note: who's idea was it to put a * at the end of url anchor's?

**Comment by jan-ivar** [comment]
@fippo You can do
```js
pc.getStats().then(report => [...report.values()].filter(stat => stat.type == 'transport'))
```

But these are all for-loops in my book. RTCPeerConnectionStats is effectively a global in getStats, which means you'd still need a for-loop, so what would it buy us?

It seems we can also get transports off of RTCRTPStreamStats's transportId. That seems plenty to me, so I think I need a clearer description of the problem.

**Comment by fippo** [comment]
@jan-ivar good point, there no way to avoid the for loop to find our "entry point" anyway -- which I assumed would always be the pcstats dict. But the stats "snowball" has many facets.

I'll ponder a bit and see if I can come up with an example that could be added to the spec (like audio and video bytes sent for two tracks). But closing here in case I forget or don't manage
