### ISSUE TITLE
Dated getStats example.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-stats#236]
The [example](https://w3c.github.io/webrtc-stats/#example-of-a-stats-application) seems dated, as we've had [packetsLost](https://w3c.github.io/webrtc-stats/#dom-rtcreceivedrtpstreamstats-packetslost) for a while. Also, differing timestamps in remote vs local stats aren't accounted for in the calculation, so this may be poor advice as well.

Might a better example be calculating frame-rate based on `framesEncoded` or `framesDecoded`?

Here's a [demo](https://jsfiddle.net/jib1/6j072zcx/) I've tested in Chrome and Firefox.

Also, unless there can be more than one `"outbound-rtp"` per sender (can there?) we probably don't need a for-loop either (both the spec example and my demo are broken if there ever are).

@aboba @vr000m ?

**Comment by vr000m** [comment]
Done!
