### ISSUE TITLE
Do the "audio level" stats include MediaStreamTrack volume settings?

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-stats#239]
For example: If an application sets [volume](https://www.w3.org/TR/mediacapture-streams/#def-constraint-volume) to 0.5, should the `audioLevel` stat be multiplied by 0.5 as well? Or does it represent the level from the raw stream of RTP packets? I assumed it was the latter, but it would be useful to clarify.

**Comment by vr000m** [comment]
It represents the raw stats and not the volume. 

We could add a volume stat.

**Comment by henbos** [comment]
It this set per sender, per receiver or both? Or per track?

Is the volume on the sender's side reflected in the volume on the receiver's side and how?

**Comment by taylor-b** [comment]
> It this set per sender, per receiver or both? Or per track?

Per track.

> Is the volume on the sender's side reflected in the volume on the receiver's side and how?

I believe so:

> The encoding and transmission of each MediaStreamTrack should be made such that its characteristics (width, height and frameRate for video tracks; **volume**, sampleSize, sampleRate and channelCount for audio tracks) are to a reasonable degree retained by the track created on the remote side.

**Comment by vr000m** [comment]
@taylor-b: Go ahead and make a proposal. I can review it.

**Comment by henbos** [comment]
Ping @taylor-b

**Comment by taylor-b** [comment]
On my TODO list, just hasn't reached number one priority yet.

**Comment by icydragons** [comment]
Does this represent the volume setting from the audio device that is playing out the audio sample as well? Users muting their computers and not realizing it is an issue we have discovered.

**Comment by alvestrand** [comment]
This is related to the #271 "input audio level" question.

**Comment by alvestrand** [comment]
I think the answer should be "yes". Check the PR #288 to see if you're happy with it.
