### ISSUE TITLE
Add packetsDiscarded and packetsRepaired to stats

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#24]
From TPAC: "They are useful".
@juberti problem: Definition of "packetsRepaired" seems unclear. @vr000m has pointer to defs.

**Comment by vr000m** [comment]
packetsRepaired comes from https://tools.ietf.org/html/draft-ietf-xrblock-rtcweb-rtcp-xr-metrics-02#section-6.6

> The cumulative number of lost RTP packets repaired after applying a error-resilience mechanism, Appendix A (b) of [RFC7509]. To clarify, the value is upper bound to the cumulative number of lost packets.

**Comment by alvestrand** [comment]
Stuff should be moved from the XRBlock discussions / docs to here.
