### ISSUE TITLE
Stats for Audio network adaptation

### ISSUE THREAD

**Issue by ivocreusen** [w3c/webrtc-stats#240]
We are currently working on adding several statistics related to Audio Network Adaptation to the non-standard GetStats interface in WebRTC. Our current proposal is to add stats to track several things:
- A counter for the number of times the audio bitrate is changed since the start of the call.
- A counter for the number of times DTX is toggled.
- A counter for the number of times FEC is toggled.
- A counter for the number of times the number of audio channels is changed.
- A counter for the number of times the frame length is increased.
- A counter for the number of times the frame length is decreased.
- The uplink packet loss fraction as determined by the FEC controller.
I think these stats are pretty general and not very implementation specific, so would it be a good idea to standardise these?

**Comment by vr000m** [comment]
Commenting on the FEC metrics: there is already the pre-repair (i.e., reported in the RTCP RR) and the residual (post-repair) packet loss. The former is before the FEC controller and the latter is after the FEC controller.

**Comment by vr000m** [comment]
What does the counter for audio bitrate signify? I can see it change or adapt for several reasons and not sure if all reasons warrant a counter.

**Comment by ivocreusen** [comment]
These stats are intended to show how many actions are taken by the audio network adaptation component. So each time a decision is made to change the parameters (bitrate, frame length, dtx, fec, etc.) the corresponding counter is increased. To answer your question about audio bitrate: the counter would show how many times a decision was made to change to a different bitrate, based on the network conditions. 

Of course the behavior of these stats will depend on how network adaptation is implemented, but they can provide useful insights into how much network adaptation was applied and at what time in a given call, for any adaptation strategy.

**Comment by vr000m** [comment]
At first glance, I am okay with the following stats:

+ A counter for the number of times the number of audio channels is changed.
+ A counter for the number of times the frame length is increased.
+ A counter for the number of times the frame length is decreased.

With the FEC, audio bitrate we can have a call.

**Comment by alvestrand** [comment]
With sampled stats, it seems that the counters are most useful because just watching DTX/FEC/bitrate/channels/framelength can miss multiple changes within a polling interval.
Are all these values also exposed as stats? IE it seems a bit strange to have the count of FEC flips without also having a stat for whehter FEC is currently on or off.

**Comment by henbos** [comment]
Ping @ivocreusen

**Comment by alvestrand** [comment]
would be good if @ivocreusen could make a PR, so as not to introduce errors in interpretation on the way

**Comment by ivocreusen** [comment]
The way it is currently implemented is as a pure counter for the number of flips. With the number of FEC flips and knowledge of the starting value (off), the status can be easily calculated at any time. Perhaps it makes sense to add more stats to poll the current state as well, so we don't have to rely on knowledge of the initial conditions?

**Comment by alvestrand** [comment]
This seems like something we should experiment with rather than standardize straigthaway, since we're unsure what exactly is being asked for here, or how useful it is.
