### ISSUE TITLE
Is bytesReceived really available for RTCRemoteInboundRTPStreamStats?

### ISSUE THREAD

**Issue by na-g** [w3c/webrtc-stats#241]
I am not sure how bytesReceived can be calculated on the sender side from RTCP receiver reports.  Am I missing something or should this stat be moved from RTCReceivedRTPStreamStats to RTCInboundRTPStreamStats?

**Comment by jan-ivar** [comment]
"calculated as defined in" https://tools.ietf.org/html/rfc3550#section-6.4.1 which is Sender Report.

**Comment by jan-ivar** [comment]
From Receiver Report https://tools.ietf.org/html/rfc3550#section-6.4.2 *"the five words of sender information are omitted (these are the NTP and RTP timestamps and sender's packet and octet counts)"*

**Comment by vr000m** [comment]
make a PR with 6.4.2 to point to the correct section.

**Comment by alvestrand** [comment]
Assigning to @vr000m since he promised to check it.

**Comment by alvestrand** [comment]
RFC 3550 section 6.4.2 seems to say that the sender octets are omitted from the RR.
