### ISSUE TITLE
jitterBufferDelay and concealed samples, DTX/CNG samples

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#246]
jitterBufferDelay is total time each audio or video samples has spent in the jitter buffer before being decoded and sent out for rendering.

For video, average time spent in jitter buffer is jitterBufferDelay/framesDecoded. This makes sense.

For audio, it is said to be jitterBufferDelay/totalSamplesReceived. Possible problems:
- totalSamplesReceived include concealedSamples, which have spent no time in the jitter buffer. Should we instead divide by (totalSamplesReceived - concealedSamples)?
- We may have received samples that have not been decoded and ready to be played out, and these samples have not contributed to jitterBufferDelay yet. There is no "samplesDecoded", is totalSamplesReceived >= the value we should divide by?
- How are DTX/CNG samples handled? Do these contribute to jitterBufferDelay? Do these contribute to totalSamplesReceived?

**Comment by henbos** [comment]
Are audio samples available for counting before or after audio frames have been decoded? framesDecoded only exist for video.

**Comment by vr000m** [comment]
maybe samplesDecoded is fine?

**Comment by henbos** [comment]
Let's make a PR adding samplesDecoded and have jitterBufferDelay/samplesDecoded then.

**Comment by henbos** [comment]
Correction: jitterBufferDelay/(samplesDecoded - concealedSamples), assuming concealed samples increment samples decoded

**Comment by vr000m** [comment]
That makes sense... confirm that the concealed samples increment the samples decoded.

**Comment by hlundin** [comment]
I think this is still going to be hard to implement, considering all the corner cases with DTX/CNG, and possibly also clock-drift compensation.

I don't know the background, but was it ever considered to accumulate the delay for each packet or frame, without multiplying with number of samples. Then it would have to be normalized by the number of frames decoded (in analogy with the video counterpart). The benefit is that both the delay accumulation and the incrementing of the frames counter will likely be made at the same place in an implementation. What you lose is the weighting with frame size.

**Comment by henbos** [comment]
In your proposal, how does concealed samples affect framesDecoded and jitterBufferDelay?

**Comment by hlundin** [comment]
Not at all. My thinking is that when a frame is taken out of the jitter buffer and given to the decoder, the time it sat waiting in the buffer is calculated and added to the jitterBuferDelay, **and** the framesDecoded is incremented.

For frames that are never decoded (for whatever reason), neither metrics are affected.

**Comment by henbos** [comment]
@vr000m Do we do the same video framesDecoded? Increment the frame count when passing the frame to the decoder, not after decoding has completed?

**Comment by hlundin** [comment]
For audio this is the same thing, I would say. Decoding audio is a direct transaction, where you pass input and get output in the same function call.

**Comment by alvestrand** [comment]
Is there a metric that a) makes sense and b) is simple to compute?
jitterBufferDelay may be defined in a way that says concealed samples are counted in a way that makes calculation simple, if such a number exists.

**Comment by hlundin** [comment]
Elaborating on my proposal above, I can come up with two different variants. One that deals with packets/frames as the base unit, and one that uses samples instead.

1. Packets as unit:
When a frame is taken out of the jitter buffer and given to the decoder, the time it sat waiting in the buffer is calculated and added to the jitterBuferDelay, and the framesDecoded is incremented. This is true for both speech frames and comfort noise frames. To calculate an average delay, normalize jitterBuferDelay with framesDecoded.

2. Samples as unit:
When a frame is taken out of the jitter buffer and given to the decoder, the time it sat waiting in the buffer is multiplied by the number of samples that frame produced, and the result is added to the jitterBuferDelay. samplesDecoded is incremented by the same number of samples. This is true and straightforward for speech frames. For comfort noise frames, which typically does not have a real length, the implementation can give them any length (also zero) and use that both as multiplier to the delay and to increment samplesDecoded. The tricky part here is that the relationship to totalSamplesReceived and concealedSamples may not be hard to define, and will probably be implementation specific. To calculate an average delay, normalize jitterBuferDelay with samplesDecoded.

Of the two above, I prefer number 1.

**Comment by taylor-b** [comment]
There's also a third option, "time as unit". When a frame is taken out of the jitter buffer, you add the delay multiplied by the duration of the frame. Then you can divide this total by `totalSamplesDuration` to get the average delay over time, independent of packetization interval *and* sampling rate.

**Comment by henbos** [comment]
The jitterBufferDelay would have a different unit for audio and video. For audio it's time squared and for video it's time. Having different definitions for audio and video is fine by me.

**Comment by hlundin** [comment]
Reading the definition for `totalSamplesDuration`, it is not clear to me whether this is only the sum length of samples produced by the decoder, or if it is all the samples played out (i.e., including loss concealment and time stretching).

**Comment by taylor-b** [comment]
That's a good point. It's at the "track" stats level, and intended to be the divisor of something based on "received" samples, where `totalSamplesReceived` includes `concealedSamples`, so for those two reasons the most sensible definition would seem to be "all samples played out". Conceptually, all samples delivered to the MediaStreamTrack. I believe that's how it's implemented currently too (it comes from `_outputAudioLevel`).

Would this work for the jitter buffer delay as well?

**Comment by alvestrand** [comment]
Hm. One problem here is that the text "from the time the first packet belonging to an audio/video frame enters the jitter buffer" is implementation dependent, and inconsistent with the previous sentence's "from the time it is received". An implementation that places packets into the jitter buffer on arrival, and reassembles the frame within the jitter buffer, will give different results than one that separates the jitter buffer from the reassembly step.
Suggestion: Change "enters the jitter buffer" to "is received". Implementation-wise, this would involve timestamping the packet at reception (we already do, I think), mark the frame with the timestamp of the lowest-timestamped packet contributing to it, and measure the difference between "current time" and the timestamp when a frame is taken out of the buffer to be displayed.
Since only frames taken out of the buffer are counted, none of the current counters quite fit; we should define new counters for "framesPlayed" and "totalSamplesPlayed".

**Comment by henbos** [comment]
A frame going out of the jitter buffer does not mean it is played out: there could be a decode error, it could get dropped due to missing playout, or other. This means we can't use "framesDecoded" for video, and we can't use "framesDecoded - framesDropped" because they could get dropped before the jitter buffer.

Should we just make the counters specific to coming out of the jitter buffer to avoid all these subtle bugs? "jitterBufferOutput - the number of samples/frames that have gone through the jitter buffer"?

**Comment by vr000m** [comment]
> there could be a decode error, 

That is possibly correct.

> it could get dropped due to missing playout, or other.

This should have been handled by the jitter buffer.
