### ISSUE TITLE
pliCount is Picture Loss Indication, not Packet Loss Indication

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#247]
Our spec says pliCount is...
> Count the total number of Packet Loss Indication (PLI) packets received by the sender. This metric is only valid for video and is sent by receiver. Calculated as defined in [RFC4585] section 6.3.1.

PLI is actually Picture Loss Indication, https://tools.ietf.org/html/rfc4585#section-6.3.1.

**Comment by fippo** [comment]
I knew this sounded familiar... #232, fixed in #233

**Comment by henbos** [comment]
Oh, already fixed yeah.
