### ISSUE TITLE
Add stats for the negotiated DTLS-SRTP and DTLS cipher suites.

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-stats#248]
Presumably this would go on `RTCTransportStats`. Chrome's non-standard stats implementation included these, with the names "srtpCipher" and "dtlsCipher". They would be `DOMString`s that use cipher suite names defined in RFCs, such as "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA".

Any reason not to do this? It seems like it would actually help in implementing one of the requirements of rtcweb-security-arch:

>    UI Requirements:   A user-oriented client MUST provide an "inspector"
>       interface which allows the user to determine the security
>       characteristics of the media.
>    ...
>       *  The "security characteristics" MUST indicate the cryptographic
>          algorithms in use (For example: "AES-CBC" or "Null Cipher".)
>          However, if Null ciphers are used, that MUST be presented to
>          the user at the top-level UI.

**Comment by vr000m** [comment]
RTCTransports has link to RTCCertificates, so it would be a nice place to add the srtpCipher and dtlsCipher.

Please go ahead and make a PR.

**Comment by alvestrand** [comment]
Is this the stream cipher only, or does it include the cert ciphers?
Is there a reference to (D)TLS that you can use to give its definition?

**Comment by henbos** [comment]
How does this tie in to which certificate you used? Should it be per-transport or per-certificate?

**Comment by taylor-b** [comment]
> Is this the stream cipher only, or does it include the cert ciphers?

Is the cert cipher represented by `RTCCertificateStats.fingerprintAlgorithm`, or are you referring to something different?

> Is there a reference to (D)TLS that you can use to give its definition?

`dtlsCipher` would be the selected "cipher suite" as defined in RFC6101, and `srtpCipher` would be the selected "DTLS-SRTP SRTP Protection Profile" as defined in RFC5764.

> How does this tie in to which certificate you used?

The certificates are used for authentication, and (I believe) play a role in encrypting the key that's ultimately used for media.

> Should it be per-transport or per-certificate?

Per-transport.

**Comment by henbos** [comment]
(Implementation-wise this would be very easy to add to RTCTransportStats, presumably.)
