### ISSUE TITLE
Add stat for SRTP decryption failures

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-stats#249]
This would be useful for diagnosing why calls are failing.

The simplest thing would just be a `decryptionFailures` counter, which would be the number of packets that failed decryption. This doesn't appear currently counted by `packetsDiscarded`.

**Comment by vr000m** [comment]
Is this counter increase when the decryption of a packet fails, i.e., for each packet.

**Comment by vr000m** [comment]
Taylor go ahead and make a PR.

**Comment by alvestrand** [comment]
let's call it packetsFailedDecryption, and document that it's packets that are received and not discarded.

**Comment by fippo** [comment]
from what i've seen the most common errors from libsrtp are replay_fail which might be normal, for example if rtx is not used, a packet is nacked twice and the second packet is discarded with this error) and  replay_old which at least for me is typically the result of messing with sequence numbers.

Which of these do you want to count? Having only a single count might mask replay_old errors

**Comment by taylor-b** [comment]
I thought of having counts of different error categories, but thought this may be unnecessary and it may be difficult to define the categories. Would it be reasonable to start with a counter that covers every error, and drill down into individual categories if we find it's necessary later?

**Comment by henbos** [comment]
SGTM
