### ISSUE TITLE
Stats for adaptation reason, for realsies

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#256]
Merging all of these issues into one: #144, #160.

Alternatives:
- sequence (enum) - "CPU", "Bandwidth", "other".
- Pick the one that's obvious - "None", "CPU", "Bandwidth", "other"

googStats are a bunch of booleans that can be turned into a bitmask, and googAdaptationChanges counters.

**Comment by henbos** [comment]
In goog:
googBandwidthLimitedResolution
googCpuLimitedResolution

At some point there was:
googViewLimitedResolution

**Comment by vr000m** [comment]
However, there are a couple of questions:
does this mean bitrate was changed? or is it also frame-size and frame-rate as well, as a result the of which the bitrate was changed?

For bitrate there can be a number of reasons:
+ delay-mode
+ loss-mode
+ capped by max-bitrate
+ or CPU
+ or there was no content to send (black screen, no motion)? 

For frame-size vs frame-rate, it could be because of the degradation-preference.

**Comment by henbos** [comment]
Proposal:

unsigned long adaptationChanges;
Number of times target bitrate or resolution changed as a result of adaptation changing (it can change from CPU to CPU or from something to none, any time the setting is different).

sequence(string) adaptationReason;
The current things limiting bitrate or resolution, such as "CPU" or "bandwidth"

**Comment by henbos** [comment]
Problem: the target bitrate changes all the time.

**Comment by henbos** [comment]
What we want to solve: Why are we not seeing the optimal resolution?

**Comment by henbos** [comment]
How about?
- bandwidthLimitedDuration (could overlap with cpu)
- cpuLimitedDuration (could overlap with bandwidth)
- totalLimitedDuration
- adaptationReason (sequence of current reasons, empty if not limited)
- adaptationCounter: times you go from not limited to not limited

Question: are we ever both CPU and bandwidth limited, considering if bandwidth brings the resolution down that decreases CPU usage?

**Comment by alvestrand** [comment]
With "record" being suggested in another bug, what about:
enum qualityLimitationReason = {cpu, bandwidth, other}
enum qualityLimitationMethod = {none, framerate, resolution, quality}  // quality = qp value manipulation

... outgoing RTP stream ...
qualityLimitationReason limitationReason;  // current most important reason
qualityLimitationMethod limitationMethod; // current most significant method
record<DOMString, double> limitationDurations;   // key qualityLimitationReason, value seconds
long limitationChangeCounter;  // changes every time reason or method changes

We could also attach to "track", but in the case of simulcast, things could be different for each RTP stream depending on, among other things, priority.

**Comment by henbos** [comment]
Assuming you're not sending lossless vIdeo, it's always going to adjust quality based on whatever bitrate it has available (constantly changing). In that sense it is always "bandwidth limited". Despite quality being important, in terms of "is there adaptation going on", the QP would be meaningless unless you define thresholds, but this might be opening a can of worms.

We thought that if there is need for adaptation, and it's only changing QP but not resolution and/or framerate there would be a bug in the WebRTC implementation. As such, we only need to care about resolution and/or framerate. If you have crappy quality, you probably also have crappy resolution/framerate.

**Comment by henbos** [comment]
Another important difference between QP and resolution/framerate, I would think, is that resolution/framerate is something you set with constraints/settings, and the other is the end result of other things.

**Comment by henbos** [comment]
I made an initial PR, excluding change counters for now. Is a change counter only valuable for flip flopping between limited and not limited? I'm hesitant towards increasing the counter up if it changes between "bandwidth" and "cpu" (or "other") in case it walks the line or going back and forth, imagining it is a little limited by both. How fast the counter increases would depend on how aggressive the implementation is. Hopefully, a counter that only goes up when it goes from no limitation to limitation is more stable and useful.
