### ISSUE TITLE
Add stat for network type of ICE candidate

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-stats#257]
It would be pretty useful to know what type of network a local ICE candidate is using (for example, Wi-Fi, Ethernet, cellular, etc.).

Here's an enum we may be able to use: http://wicg.github.io/netinfo/#dom-connectiontype

Or at least copy, assuming referencing a WICG standard isn't allowed.

**Comment by henbos** [comment]
Go ahead and make a PR
