### ISSUE TITLE
Behavior of stats on closed, stopped and never-started tracks/SSRCs and so on needs to be clear

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#26]
The behavior agred on is that stats for an object, once initialized, will be available for the lifetime of the PC. When it's stopped, the clock stops advancing - the stats are the stats at the moment of stoppage, but the stats object does not disappear even if the object does.

This applies to all stats objects.

This needs to be clear.

**Comment by alvestrand** [comment]
Also see #8

**Comment by alvestrand** [comment]
#8 is the attempted fix.

**Comment by alvestrand** [comment]
Need some generic language here too.

**Comment by alvestrand** [comment]
There is an issue (mentioned by @jan-ivar ) about the case where a track moves between senders.

https://github.com/w3c/webrtc-pc/issues/572

**Comment by vr000m** [comment]
Proposal accepted: 
+ State is frozen on stop. Including timestamp.
+ The last state lasts until the PC it belongs to is gone.

**Comment by alvestrand** [comment]
Seems resolved by #68
