### ISSUE TITLE
"Make tidy" is broken?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#263]
In repo, "make tidy" produces a HTML file that is left aligned, no indent.

"make clean" does not improve the situation.

Since "make tidy" is our main tool to keep consistent formatting of our HTML source, this is bad.

**Comment by vivienlacourba** [comment]
Fixed in https://github.com/w3c/webrtc-respec-ci/commit/f804919971d1aaae235f81249ccc819f26f076da

FYI `make clean` only removes generated files (in does not clean nor reformat the source document).
