### ISSUE TITLE
Add per layer stats for SVC

### ISSUE THREAD

**Issue by ssilkin** [w3c/webrtc-stats#275]
In case of SVC, when sender can produces multiple spatial/quality layers, we would like to get video stats per layer. Video layer stats should include:
1. Video-related parameters of RTCMediaStreamTrackStats:
`unsigned long       frameWidth;`
`unsigned long       frameHeight;`
`double                   framesPerSecond;`
`unsigned long       framesSent;`
`unsigned long       framesReceived;`
`unsigned long       framesDecoded;`
`unsigned long       framesDropped;`
`unsigned long       framesCorrupted;`
`unsigned long       partialFramesLost;`
`unsigned long       fullFramesLost;`
2. Qp and loss-related parameters of RTCRTPStreamStats:
`unsigned long      firCount;`
`unsigned long      pliCount;`
`unsigned long      nackCount;`
`unsigned long      sliCount;`
`unsigned long long qpSum;`

Receiver's stats in case of SVC should be the stats of the highest layer it receives.

**Comment by alvestrand** [comment]
@pthatcherg the simulcast layers are represented by RTCRtpStreamStats (which have an SSRC). Do you think we need to change the inheritance hierarchy here for SVC layers?

**Comment by alvestrand** [comment]
ping @pthatcherg again for comment.

**Comment by ssilkin** [comment]
Any update on this?

**Comment by alvestrand** [comment]
@ssilkin do you have an opinion on how these things should inherit from each other?
in particular how we can tell "layers" apart.

**Comment by ssilkin** [comment]
No, not really. I only know that stats should be per spatial layer.

If we can send different layers with different SSRCs then no changes in stats will be needed. But I'm not sure if this will work. I will investigate/try and let you know the results.

**Comment by aboba** [comment]
@alvestrand  VP8/VP9/AV1 all use a single stream for SVC. So it is somewhat tricky to keep statistics on a per-layer basis.  For example, a sender receiving a NACK could be getting feedback on losses within multiple layers, and a receiver sending a NACK would need to track the correspondence between losses and layers.  Also, the SFU will typically adjust the layers forwarded based on the aggregate bandwidth and loss rates.

**Comment by alvestrand** [comment]
@aboba Is it appropriate to forget about the multi-stream SVC format, to make our life simpler?

**Comment by ssilkin** [comment]
It appeared that per-layer stats is not actually needed for project I'm working on. I will unassign myself from the ticket.

**Comment by alvestrand** [comment]
Until we have a customer, we'll close this bug then.
