### ISSUE TITLE
What happens when a partial keyFrames is received? 

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-stats#278]
does the keyFramesReceived counter go up?
partialFramesLost counter will definitely go up...

**Comment by alvestrand** [comment]
We have to decide whether partial lost frames are counted as received.
My vote would be for "no" - it seems silly to count fully lost frames as "received", and counting a multipacket frame as "received" when we have received one useless packet seems wrong too.

So I'd think that we don't increment framesReceived, and don't increment keyFramesReceived.

(Q: When a frame is first partially received and then repaired using FEC or retransmission - does the partialFramesReceived counter go *down* when repair is finished?)

**Comment by vr000m** [comment]
In https://github.com/w3c/webrtc-stats/pull/268, I made a comment on when these counters go up.

framesReceived are definitely full frames, so they should be counted after repair and reorder has been taken in to account.

so if a keyFrame is partially received, the partialFramesLost goes up.
