### ISSUE TITLE
Add TLS version and EC group id to stats

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#279]
This is a spin-off from #276.

**Comment by alvestrand** [comment]
Quoting for @ekr:

Does the group name come from https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-8 ? I suppose that's only applicable for EC cipersuites?
What's the correct reference for the TLS version field? RFC 5246 seems to define only the { 3, 3 } aka TLS 1.2 value - ideally, I'd like to point to somewhere that gives "TLS 1.2" as a string, but as a fallback, I could give a string representation of the version flag from the clientHello.
I want to make sure we don't get "tls-1.2" in one implementation and "TLS 1.2" in another.

**Comment by ekr** [comment]
Given that we are moving towards numeric versions, including draft #s, etc.
maybe just suck it up and use the number?

-Ekr

**Comment by alvestrand** [comment]
so what is the number, and where do I point to for reference?

**Comment by ekr** [comment]
It's the version number. In TLS 1.2 and below it goes in
ServerHello.version. In TLS 1.3 and later it goes in
ServerHello.supported_versions.

-Ekr




On Wed, Dec 13, 2017 at 6:30 AM, Harald Alvestrand <notifications@github.com
