### ISSUE TITLE
"record<RTCQualityLimitationReason, double> qualityLimitationDurations" has invalid type

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#281]
According to WebIDL, https://heycam.github.io/webidl/#idl-record, the record's key must be of type DOMString, USVString, or ByteString.

We're trying to use an enum key type (RTCQualityLimitationReason). Questions:
- Should we use a different type than record?
- Should we use record<DOMString, double> and specify that the key are all the string-values of RTCQualityLimitationReason?
- Should we file a WebIDL issue, requesting record's key to include enum types?

**Comment by henbos** [comment]
I landed the hack #280 to get around travis build failing in the meantime!

**Comment by vr000m** [comment]
We will encounter this problem in the DSCP-related issues as well, #133 #135. Hence, we need a sensible option.

**Comment by henbos** [comment]
I merged #282 so that we have record<DOMString, double> which implementation-wise will work the same as what we intended but I'm not closing this issue until we have decided what to do. If DOMString is the way to go we might want to take a second look to see if we need to clarify the use of enum here.

**Comment by henbos** [comment]
Will file a bug on WebIDL

**Comment by alvestrand** [comment]
It's possible that DOMString is preferable because it allows us to extend the Enum.

**Comment by henbos** [comment]
Filed https://github.com/heycam/webidl/issues/509

**Comment by alvestrand** [comment]
the WebIDL bug seems to conclude that DOMString is all there will ever be.
We'll document that implementations should only emit DOMStrings that are legal enum values, and leave it at that.

**Comment by henbos** [comment]
I'll close this issue, we're already referencing the enum.
