### ISSUE TITLE
Enable continuous publication

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#292]
echidna should be enabled.
Failing that, we should get a new TR when the CR blockers are merged.
@vivienlacourba can you look at echidna?

**Comment by alvestrand** [comment]
#101 check

**Comment by vivienlacourba** [comment]
@alvestrand my last commit should fix your future edits and publications.

Meanwhile I manually triggered Echidna and the doc got published at: https://www.w3.org/TR/2018/WD-webrtc-stats-20180110/

Let me know if your next merge of a PR does not generate a new TR doc.
