### ISSUE TITLE
RTCRTPStreamStats should have senderId/receiverId

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#293]
Now that we have sender/receiver stats, it makes sense for outbound RTP streams to reference sender stats with senderId and inbound RTP stream stats to reference receiverId.

As long as we have track attachment stats we can keep the existing trackId on RTCRTPStreamStats.

**Comment by henbos** [comment]
Related question: Are sender/receiver stats and RTP stream stats always a 1:1 mapping that never changes? Could RTP stream stats be viewed as a subset of sender/receiver stats?

**Comment by taylor-b** [comment]
What's the difference between `RTCVideoSenderStats` and `RTCLocalVideoStreamTrackStats`? Does it have to do with `replaceTrack`? I'm a little confused about the current state of the stats objects.

Anyway, to answer your question: it's not a 1:1 mapping, more a 1:M mapping. My current understanding is that each `RTCRTPStreamStats` represents one RTP stream, and one sender/receiver could definitely use multiple RTP streams over its lifetime. In the case of the sender, multiple at once if using simulcast.

**Comment by henbos** [comment]
> Anyway, to answer your question: it's not a 1:1 mapping, more a 1:M mapping. My current understanding is that each `RTCRTPStreamStats` represents one RTP stream, and one sender/receiver could definitely use multiple RTP streams over its lifetime. In the case of the sender, multiple at once if using simulcast.

Ok, thanks! Then having them as separate objects still makes sense.
There is a `rtpstream -> track` reference, at some point we chose not to have redundant references in both directions, but conceptually there is `track -> rtpstream(s)`.

> What's the difference between `RTCVideoSenderStats` and `RTCLocalVideoStreamTrackStats`? Does it have to do with `replaceTrack`? I'm a little confused about the current state of the stats objects.

`RTCVideoSenderStats` is the stats for the sender during all of its lifetime. Imagine a graph that keeps growing indefinitely over time since the sender was created.
The `RTCLocalVideoStreamTrackStats` represents a subset of the graph, starting from and with the baseline of a track being attached to the sender, which grows until the track is no longer attached in which case `objectDeleted = true`.

There is no need for a separate dictionary for this, since a track attachment is just another baseline of the sender stats and for a different duration of time. It was added when we still had a `boolean detached` member, now that all `RTCStats` dictionary has `objectDeleted` it was removed.

I think removing and renaming some of these dictionaries will make the picture less confusing. In the future, if having "track attachment stats" (subsets of the sender attachment stats with other baselines) proves as unnecessary as we think they are we can deprecate and remove these, and only think in terms of sender/receiver stats.

**Comment by alvestrand** [comment]
I think we should only have pointers in one direction, so I suggest that the sender stats have the ID of the stats for its currently attached track.

**Comment by taylor-b** [comment]
> The RTCLocalVideoStreamTrackStats represents a subset of the graph, starting from and with the baseline of a track being attached to the sender, which grows until the track is no longer attached in which case objectDeleted = true.

So this does have to do with `replaceTrack`, then? Every time you call `replaceTrack`, a new `RTCLocalVideoStreamTrackStats` shows up and the previous one is marked as `objectDeleted`? That seems like something worth calling out.

**Comment by henbos** [comment]
Yes!
