### ISSUE TITLE
Rename RTCRTPStreamStats to RTCRtpStreamStats?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#294]
In webrtc-pc, the only abbreviation that's all-CAPS is RTC.
Example: RTCRtpSender.

All stats dictionary names ending with RTPStreamStats should be renamed RtpStreamStats.

**Comment by alvestrand** [comment]
Let's do it.

**Comment by vr000m** [comment]
@karthikbr82 could you take care of this PR.

**Comment by na-g** [comment]
RTCRTPContributingSources also defies this convention, and could be concurrently renamed.
