### ISSUE TITLE
Define timestamps in terms of performance.origin

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#295]
Check discussion here:

https://github.com/w3c/webrtc-pc/issues/1690

Timestamps should be defined as performance.timeOrigin + performance.now().

**Comment by fippo** [comment]
Note that this is causing issues on Linux with suspend. As my favorite LLM said:
> timeOrigin + now() definition means timestamp does not advance while the system is suspended and 
> therefore diverges from wall clock by the suspend duration

I have seen getStats timestamps which where off by *hours*. This isn't an issue if one only looks at deltas but it makes it hard to look at in graphs.

See also https://github.com/w3c/hr-time/issues/115
