### ISSUE TITLE
Rename "objectDeleted" to something else.

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#296]
In the case of "track" stats, "objectDeleted" would be true for any attachments that are no longer current, even though no object has necessarily been deleted. Neither "object" or "deleted" are suitable descriptions unless you consider the "attachment" the "deleted object".

Generally speaking, any object that is exposed to the application may not have been deleted due to existing references (by application or webrtc) ((or if we want to be pedantic, because the GC has not run)).

This may be bikeshedding but if we want to rename it we should do so now before UAs ship it.
What's more suitable? "active", "isActive", "objectActive"? (RTCTransportStats.active has since long been removed from the spec)

**Comment by alvestrand** [comment]
May be OBE if we pick the "emit event" resolution for #235

**Comment by vr000m** [comment]
related to #235, pursue this if that doesnt go through

**Comment by alvestrand** [comment]
Closing as "OBE by #235"
