### ISSUE TITLE
getStats should not abort on a closed connection

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-stats#3]
(see bug originally reported at https://www.w3.org/Bugs/Public/show_bug.cgi?id=26620)

(this assumes that getStats moves to this document as discussed during TPAC 2014)

**Comment by alvestrand** [comment]
Behavior of the getStats call shouldn't be in this doucment. Closing.

**Comment by fippo** [comment]
for papertrail: https://github.com/w3c/webrtc-pc/issues/131 says "except getStats"
