### ISSUE TITLE
terminology: rename mediaType to kind

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-stats#301]
We use "kind" (from MediaStreamTrack.kind) everywhere to describe the media type and should update
https://w3c.github.io/webrtc-stats/#dom-rtcrtpstreamstats-mediatype for consistency.

This is also mentioned in the main spec once [here](http://w3c.github.io/webrtc-pc/#mandatory-to-implement-stats)

originally added in #9

**Comment by alvestrand** [comment]
Breaking change for users, and we're likely to have to keep the old name around roughly forever.
Still, people who look for "kind" in other places are likely to look for it here too. Should do.
