### ISSUE TITLE
CodecType "encode" / "decode" needs to default to "both"

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#303]
The description of RTCCodecStats has the field "codecType" that can be either "encode" or "decode".
It should say that if the field is missing, the codec is one that the implementation is prepared to both encode and decode.

**Comment by alvestrand** [comment]
This was discussed in #195 - it seems that the decision at the time was to always have two codecs attached to the PeerConnection as appropriate.

**Comment by vr000m** [comment]
Discussed this at length in #195, I do not think much has changed since that discussion.

**Comment by alvestrand** [comment]
Note - codec is referred to from RTCStreamStats - outgoing streams would have an "encode" codec and incoming streams would have a "decode" codec.
