### ISSUE TITLE
Stats need to mark up which members are required

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#304]
Some fields are needed for the stats to make any sense at all. Others may or may not be present, depending on the state of the connection or the quality of the implementation.

Those that are absolutely necessary should be marked up with "required" in the IDL.

**Comment by alvestrand** [comment]
This is entirely orthogonal to the question of whether they're mandatory-to-implement.

**Comment by aboba** [comment]
@alvestrand Can we get a PR to close this issue since it is blocking issuance of the CR?
