### ISSUE TITLE
video packet counters should be moved out from RTCRTPStreamStats to appropriate dictionaries

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-stats#312]
Since the changes in #272 were a lot of work, did we just miss these or was there a reason that we chose to keep them in RTCRTPStreamStats and not move them to appropriate dictionaries? 

```c
    unsigned long      firCount;
    unsigned long      pliCount;
    unsigned long      nackCount;
    unsigned long      sliCount;
    unsigned long long qpSum;
```

**Comment by vr000m** [comment]
@jan-ivar could you comment if these stats are in the right dictionary.

**Comment by vr000m** [comment]
Is the sender reporting these?

**Comment by alvestrand** [comment]
Should be on local sender and local receiver RTP stream, since the counts aren't transferred in RTCP.

**Comment by henbos** [comment]
There are lots of sender/receiver (track) stats that may or may not make sense to move to/from RTP stream stats, related issue: #318

**Comment by henbos** [comment]
@vr000m Can you create a PR?

**Comment by jan-ivar** [comment]
The reason I didn't move them initially is I misunderstood their descriptions—unsure what "sent by receiver" meant in the context of rtp/rtcp. From @alvestrand's https://github.com/w3c/webrtc-stats/issues/312#issuecomment-361946378 it seems:

* firCount: *"only valid for video and is sent by receiver"* -> RTCInboundRtpStreamStats?
* pliCount: *"only valid for video and is sent by receiver"* -> RTCInboundRtpStreamStats?
* sliCount: *"only valid for video and is sent by receiver"* -> RTCInboundRtpStreamStats?
* nackCount: *"Count ... packets received by the sender and is sent by receiver"* -> ???
* qpSum: *"sum of the QP values of ... framesDecoded for inbound ... framesEncoded for outbound"* -> RTCInboundRtpStreamStats and RTCOutboundRtpStreamStats?

Except for *nackCount* they're all video stats AFAICT. I can attempt a PR if someone tells me where *nackCount* goes.

**Comment by jan-ivar** [comment]
*qpSum* is also only for some video codecs, I gather?
