### ISSUE TITLE
When are "fractionLost", "packetsLost," "jitter", and other RFC3550-based stats updated?

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-stats#313]
There are a number of stats that are described as "calculated as defined in section 6.4.1. of [RFC3550]", which is the "SR: Sender Report RTCP Packet" section. So my question is: should these stats represent the values from the last generated SR? Or should `getStats` return "live" values?

I'm bringing this up because I found that [Chrome only returns values from the last SR](https://bugs.chromium.org/p/webrtc/issues/detail?id=8804), and it wasn't 100% clear if this is the correct behavior or not; "calculated as defined in section 6.4.1" leaves it a bit ambiguous.

My opinion: for "fractionLost", this makes sense, since it's defined as "the fraction of RTP data packets from source SSRC_n lost since the previous SR or RR packet was sent". It's a somewhat redundant stat anyway, since it can be computed with `packetsReceived` and `packetsLost`. But for the rest of the stats, I don't see any reason why we shouldn't return live values.

**Comment by vr000m** [comment]
My expectation would be that:
At the receiver, the live stats are reported.
At the sender,  only values in the RR are reported.

Is that not the case? @taylor-b

**Comment by alvestrand** [comment]
and values reported in the RR are timestamped with the arrival time of the RR.
That was my expectation.
This does create a problem for "fractionLost", which is computed from the previous SR/RR - and we haven't defined anything that allows the user to figure out when that was.
(Solved by dropping fractionLost? It seems useless once we have packetsLost and packetsReceived).

**Comment by taylor-b** [comment]
> Is that not the case?

It's not; that's what the Chrome bug I linked is about.

And yes, `fractionLost` is the one oddball I can find. I don't know if it's safe to remove, but we could leave it defined as "since last SR/RR" and encourage using `packetsLost`/`packetsReceived` instead.

**Comment by jan-ivar** [comment]
@taylor-b Specifically which stats are we talking about? I think local stats are live, remote stats are not.

Note that both senders and receivers have "remote" stats:
 1. Remote stats on the sender come from RR.
 2. Remote stats on the receiver come from SR.



Firefox does not implement *fractionLost* yet FWIW.

**Comment by jan-ivar** [comment]
*fractionLost* lives on "remote-inbound-rtp". How can that be live?

**Comment by taylor-b** [comment]
Ah, that must be something that changed at some point. In our current implementation it's in `RTCInboundRTPStreamStats`.

That makes this simple then; local stats should be live. Is this interpretation obvious enough (in which case this can be closed), or is there some language we could use to make it clearer?

**Comment by jan-ivar** [comment]
FWIW, Firefox implements live stats for all non-remote stats, from counters in our rtp stack. I believe webrtc.org did as well until around ~57, when we noticed some of the upstream bits we'd been relying on disappeared on us, and we had to work around it. Is that perhaps when Chrome broke?

@taylor-b I agree the spec language is problematic, and that we need to clarify it to be live.

E.g. [timestamp](http://w3c.github.io/webrtc-pc/#dom-rtcstats-timestamp):

*"The timestamp, of type DOMHighResTimeStamp [HIGHRES-TIME], associated with this object. The time is relative to the UNIX epoch (Jan 1, 1970, UTC). For statistics that came from a remote source (e.g., from received RTCP packets), timestamp represents the time at which the information arrived at the local endpoint."*

It doesn't explicitly say what the timestamp represents in the non-remote case. It probably should (time of sampling?)

Also, the individual stats members of [RTCReceivedRTPStreamStats](https://w3c.github.io/webrtc-stats/#dom-rtcreceivedrtpstreamstats) - like e.g. `packetsLost` - are reused in both [RTCInboundRTPStreamStats](https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats) and [RTCRemoteInboundRTPStreamStats](https://w3c.github.io/webrtc-stats/#dom-rtcremoteinboundrtpstreamstats), yet their prose seems to only cover use in the latter. Ditto for [RTCSentRTPStreamStats](https://w3c.github.io/webrtc-stats/#dom-rtcsentrtpstreamstats) and its two derivatives. We should update that prose.

**Comment by taylor-b** [comment]
> I believe webrtc.org did as well until around ~57, when we noticed some of the upstream bits we'd been relying on disappeared on us, and we had to work around it. Is that perhaps when Chrome broke?

I believe it's only `fractionLost`, `packetsLost`, `jitter` that are not "live" in Chrome; I'm not sure about the disappearing bits you refer to.

**Comment by vr000m** [comment]
@taylor-b @jan-ivar: PTAL #314

**Comment by vr000m** [comment]
@taylor-b did this require a fix in webrtc-pc as well? http://w3c.github.io/webrtc-pc/#dom-rtcstats-timestamp, I can create a PR if needed.

**Comment by taylor-b** [comment]
@vr000m I think addressing it in the stats spec is enough.
