### ISSUE TITLE
Cleanup: reformat the sections 

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-stats#316]
+ Codec Stats (7.3 should be subsection to RTCRTPStreamStats)
+ RTCQualityLimitationReason (7.9 should be part of RTCOutboundRTPStreamStats)

there might be some more that can be collapsed under other sections.

**Comment by alvestrand** [comment]
There should be a section around all the RTPStreamStat subclasses, and similarly a section around all the RTPHandler subclasses.

**Comment by henbos** [comment]
Duplicate of #324
