### ISSUE TITLE
Typo - RTCLocalAudioStreamTrackStats should inherit from RTCAudioSenderStats

### ISSUE THREAD

**Issue by karthikbr82** [w3c/webrtc-stats#317]
In section 7.21 RTCLocalAudioStreamTrackStats should inherit from RTCAudioSenderStats not RTCVideoSenderStats.

The dictionary is empty, any plans to add some stats to it ?

**Comment by alvestrand** [comment]
We can delete those unless we find an use for them Real Soon.

**Comment by vr000m** [comment]
@jan-ivar delete this?

**Comment by henbos** [comment]
I fly-by fixed this in #317, let's see if that gets merged.

**Comment by henbos** [comment]
I mean in #322
