### ISSUE TITLE
Work through implications of simulcast

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#318]
If we want to give sensible stats when we receive simulcast, we need more work.

This can be delayed until the WG decides that we should receive simulcast.

There may be sender-side issues too.

**Comment by henbos** [comment]
Sender-side issues:
- We report only highest stream resolution in sender stats (and track stats), as opposed to moving these to the RTP stream stats and having sender reference all RTP streams for all simulcast layers. Sender:RTPStreams is 1:Many.

Receiver-side issues:
- Receiver:RTPStream is 1:1 in terms of there is always one stream on the wire, but which sender stream it represents may vary over time, chaning ssrc information etc.

**Comment by henbos** [comment]
https://photos.app.goo.gl/iU9la0zsFme9TZ2j2

**Comment by aboba** [comment]
@alvestrand   In diagnosing simulcast reception problems, I am not sure how valuable it would be to look at individual RTP streams. The SFU will only forward a single stream at a time to the receiver, so from the browser point of view, there is only ever a single track provided by the receiver, the same as if the SFU were sending only a single stream.  While the RTP stream stats would include multiple streams, the issue in simulcast reception is most typically reordering/delay at the resolution switch points. So looking at individual RTP stream stats may not provide as much insight as looking at track stats to understand the aggregate.

**Comment by alvestrand** [comment]
@aboba is there any difference between track stats and rtpsender/rtpreceiver stats in this regard?

The sender/receiver stats (of some type that is a subtype of RTCMediaHandlerStats) reports on all SSRCs for an RTPSender, unlike the inbound-rtp and outbound-rtp that only report on a single SSRC.

**Comment by alvestrand** [comment]
Sender stats need to report on the highest quality stream produced from the track - OutgoingRTPStream stats need to report on each indvidual RTP stream.

**Comment by henbos** [comment]
From WG meeting: Harald, Sergio, Bernard to work out the implications of simulcast :) stats to be revisited afterwards

**Comment by jan-ivar** [comment]
@aboba @henbos We got a question about how to verify outgoing width and hight of simulcast layers using stats. Does this deserve a tag and a slide at TPAC?

**Comment by jan-ivar** [comment]
I assume with simulcast there'd be multiple `"outbound-rtp"` stats whose `stat.senderId` would match, but unfortunately `.frameWidth` hangs off of `"sender"` stats, of which there's still just one.

**Comment by alvestrand** [comment]
Seems that simulcast messes things up in "what lives where". We might want to think about adding another dictionary describing stats for a simulcast layer, possibly defining that the values in the "overall" object is = the highest layer.

**Comment by henbos** [comment]
The implications of simulcasts were discussed at length in yesterday's workshop. It spawned a bunch of issues listed below.

- #393
- #394
- #395
- #396
- #397
- #398
- #399
- #400
- #401
- #402
- #403

I will give an overarching proposal on the virtual interim next week (I filed https://github.com/w3c/webrtc-pc/issues/2116). Closing this issue as obsolete given the other issues.
