### ISSUE TITLE
RTCIceCandidatePairStats.priority is wrong

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-stats#321]
[RTCIceCandidatePairStats](https://w3c.github.io/webrtc-stats/#dfn-rtcicecandidatepairstats) has
```js
unsigned long long            priority;
```

The values as defined cannot be accurate, due to a limitation in JavaScript. Never filed an issue on [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1258725#c2) apparently:

*"JS only has double-precision floating point as a numeric type.  So "unsigned long long" in IDL really means "53-bit integer" in practice. If the API is relying on exact representation of integers that don't fit in 53 bits, it's a spec bug."*

We should probably fix the API if we care about accurate values.

**Comment by fippo** [comment]
the pair priority is a combination of both local and remote candidate pair priority defined [in the ice rfc](https://tools.ietf.org/html/rfc5245#section-5.7.2)

As far as I can see it does not provide much value unless you want to sort the candidate pairs by priority. Removing it might be an option, it can be reconstructed if absolutely necessary

**Comment by alvestrand** [comment]
Let's propose to remove it. It can be computed based on the ICE RFC computation if needed, but can't be represented in 53 bits.

**Comment by fippo** [comment]
(note: [ice role](https://w3c.github.io/webrtc-stats/#dom-rtctransportstats-icerole) is needed for reconstruction)
