### ISSUE TITLE
Clarify stats hierarchies

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#324]
We've ended up with multiple hierarchies and it's not obvious how everything fits together.
We should add an introductory section and/or structure the sections to follow the hierarchies.

I'm talking about:
```
RTCRTPStreamStats
  RTCReceivedRTPStreamStats
    RTCInboundRTPStreamStats
    RTCRemoteInboundRTPStreamStats
  RTCSentRTPStreamStats
    RTCOutboundRTPStreamStats
    RTCRemoteOutboundRTPStreamStats
```

And after https://github.com/w3c/webrtc-stats/pull/322:
```
DICTIONARY NAME                          | INSTANCE FOUND BY
-----------------------------------------+--------------------------------------
RTCMediaHandlerStats                     | N/A
  RTCAudioHandlerStats                   | N/A
    RTCAudioSenderStats                  | kind == 'audio' && type == 'sender' 
      RTCSenderAudioTrackAttachmentStats | kind == 'audio' && type == 'track'
    RTCAudioReceiverStats                | kind == 'audio' && type == 'receiver'
  RTCVideoHandlerStats                   | N/A
    RTCVideoSenderStats                  | kind == 'video' && type == 'sender'
      RTCSenderVideoTrackAttachmentStats | kind == 'video' && type == 'track'
    RTCVideoReceiversStats               | kind == 'video' && type == 'receiver'
```

Currently, all of these are just listed one after another and it's up to the reader to figure out their relationships to one another.

**Comment by alvestrand** [comment]
Related to #316 - closing that one in favor of this.

**Comment by vr000m** [comment]
duplicate of #316.

**Comment by henbos** [comment]
From #316:
> - Codec Stats (7.3 should be subsection to RTCRTPStreamStats)
> - RTCQualityLimitationReason (7.9 should be part of RTCOutboundRTPStreamStats)

**Comment by henbos** [comment]
@vr000m Can you create a PR?

**Comment by alvestrand** [comment]
Should incorporate the picture from #348 somehow.

**Comment by henbos** [comment]
Let's close this because we have the summary section now https://w3c.github.io/webrtc-stats/#summary
