### ISSUE TITLE
Add hugeFramesSent counter to RTCVideoSenderStats dictionary

### ISSUE THREAD

**Issue by ilyanikolaevskiy** [w3c/webrtc-stats#330]
Please add a hugeFramesSent counter to RTCVideoSenderStats dictionary.

This should report the total number of "huge" frames sent since the beginning of the call.
A frame is defined as "huge" if it's encoded size is at least 2.5 times the average encoded frame size for the configured encoder bitrate. In the simulcast case, if any of the substreams produced a "huge" frame, this should be counted as a single "huge" frame sent.

This metric is useful for in case of screensharing a presentation for detecting slide changes.

Without such a metric, only way to do so would be to compare uncompressed captured frames, which is slow and may not even be possible. On the other hand, this metric is fairly easy to implement inside the webrtc. Although it may not be 100% accurate, for detecting the slide changes, it's reasonably efficient.

**Comment by vr000m** [comment]
Would the hugeFrame be equivalent to an key frame, i.e., an I-frame or equivalent?

https://w3c.github.io/webrtc-stats/#dom-rtcvideosenderstats-keyframessent

**Comment by ilyanikolaevskiy** [comment]
No, while key-frames are most certainly would be huge frames, most of the huge frames would be delta frames. The issue is that encoder will most likely produce a delta frame, even on a big change in the screenshared content, even if that produced frame would be 4 times more than the allocated per-frame size. Also, key frames can't be used for detecting the slide changes because they may be caused by network loss, or receiving party deciding to switch to another stream.

**Comment by henbos** [comment]
I think we need to clarify what "average encoded frame size is".
Does the average include the frame that just arrived when we determine if it was huge? If so the first frame is never huge, otherwise the first frame is always huge for any size because the average is initially zero (x > 0).

During a call, it is possible to change resolution, quality, video track, sender parameters, etc, etc. Do we reset the counters for calculating the average when something happens or do we calculate the average for the last x frames?

The proposal needs to describe this.

**Comment by henbos** [comment]
@ilyanikolaevskiy can you create a PR?

**Comment by alvestrand** [comment]
I don't know if the value 2.5 is magical, arrived at by experience, or just a guess. Do we have statistics that show that this occurs often when what we are looking for happens (slide change, scene change?), and rarely in other cases?

Concur with @henbos worry about stats at the beginning of the call - I would tend to define "average" as a decaying average over the frames encountered with modulus 50 - that is, average(p) = average(p-1) * 0.98 + size(p)*0.02. but 50 is another random number. What did you use when experimenting?

**Comment by ilyanikolaevskiy** [comment]
@henbos, will make a PR one tomorrow. BTW, I can't add a branch to this repository, should I fork it then?

"average encoded frame size" is by definition <allocated bitrate>/<fps>. I.e if the encoder could magically produce all the frames of the same size, they all would be that size. The first frame will almost always be the huge frame, as it will be a key-frame and it will typically be quite large for any configured bitrate.

We don't have any counters to keep track of the average frame size. It's just the function of a bitrate (and fps). Resolution nor quality do not affect these calculations.


@alvestrand, We logged encoded frames sizes from internal webrtc testing tools, then chosen 2.5 as a reasonably above normal deviation in size, but less so all the slide changes in our testing were detected as an outliers. Unfortunately, I have no data to prove it now.

Again, there are no need to calculate average if it's defined as that it is: configured bitrate / configured fps.

**Comment by henbos** [comment]
Yes if you fork it and upload your change in a new branch there you can create a PR from your forked repo on github.

**Comment by alvestrand** [comment]
Where do you get the "configured bitrate" from?
We normally don't recommend that people try to configure bitrate; in most cases, the target bitrate is set by congestion control.

**Comment by ilyanikolaevskiy** [comment]
@alvestrand, the bitrate is taken directly from the encoder. This is the target bitrate set by the congestion control. Maybe I have to rename it to "target bitrate" in the proposal.

**Comment by ilyanikolaevskiy** [comment]
I've made a pull request: https://github.com/w3c/webrtc-stats/pull/331
Currently, there are some issues with the integration test infrastructure. Also, can we please skip the w3c account creation?

**Comment by vr000m** [comment]
In RFC3550 Jitter uses:
> avg_rtcp_size = (1/16) * packet_size + (15/16) * avg_rtcp_size
>  J(i) = J(i-1) + (|D(i-1,i)| - J(i-1))/16

the numbers come from:  Cadzow, J., Foundations of Digital Signal Processing and Data
        Analysis New York, New York: Macmillan, 1987.

**Comment by ilyanikolaevskiy** [comment]
If I log observed frame sizes together with target frame size and put it all on github, will that be enough of the justification for the multiplier selection?

**Comment by vr000m** [comment]
Anything that shows statistical significance, would be really appreciated.

**Comment by ilyanikolaevskiy** [comment]
You can see the experiment data here:
https://github.com/ilyanikolaevskiy/webrtc-frame-sizes-experiment-data

Should I add this link to the PR too?
