### ISSUE TITLE
Unable to distinguish "sender" stats if multiple senders are sending the same track

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#342]
"trackIdentifier" can be used to look up "track" stats and that made sense until senders were introduced and the same track can be sent multiple times simultaneously.

Now we have both "sender" and "track" stats with no way to help distinguish which sender they represent in cases where trackIdentifier is not unique. RTCRtpSender does not have an id, but its RTCRtpTransceiver has mid.
- Can we expose and use mid in stats? What if its not set?
- Do we need to introduce RTCRtpSender.id and RTC[Audio/Video]SenderStats.senderIdentifier?

**Comment by henbos** [comment]
RTCRtpSender.getStats() could be invoked to let the implementation tell you which "sender" and "track" correspond to it (but this encourages additional getStats() calls and iteration).

"What if mid is not set?" This would only be the case before negotiation when all counters are zero. Not a very useful case.

**Comment by alvestrand** [comment]
Workaround at the moment is to call sender.getStats() and look at its stats ID. If there's more use cases, this can be reopened.
