### ISSUE TITLE
add a graph showing the relationship of stats to the spec

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-stats#348]
@henbos has done a whiteboard drawing of the current stats graph which I find *very* useful:
https://photos.app.goo.gl/6P0i4AV1E3szctTl1

Would be great to add this to the spec too as it explains some of the concepts much better than two pages of text could

**Comment by henbos** [comment]
Here's a version of the picture linked above that doesn't have black lines indicating what is directly or indirectly referenced from the RTP streams:
https://photos.app.goo.gl/7n0eresV2OvBNdAT2

**Comment by alvestrand** [comment]
The graphs shown in #350 sound like a more maintainable approach than hand-drawing them.

**Comment by vr000m** [comment]
@balazskreith is taking responsibility for this. 

When it is ready, we will need someone from W3C to vet the licenses on the dependency libs

**Comment by jan-ivar** [comment]
There's also [this slide](https://docs.google.com/presentation/d/1vc3VB45gidEUcWgtmbjfJwHuoOnsCCcc3qksKMpFEuE/edit#slide=id.g1cc24b4961_3_5) from March 2017, though some of the dictionary names have changed since.

**Comment by vr000m** [comment]
@pallab-gain and @karthikbr82 put together an interactive:  https://webrtc-stats.callstats.io/graph/

**Comment by vr000m** [comment]
<img width="865" alt="screenshot 2019-02-25 at 14 50 10" src="https://user-images.githubusercontent.com/382354/53374344-dfe18380-390c-11e9-8c31-ecb15619f4b0.png">

**Comment by henbos** [comment]
Beautiful!

**Comment by MoeRT09** [comment]
Just in case, someone is interested:
I created such a graph for my thesis as well, including differences between Firefox (version 77) and Chrome (version 84). Only stats relevant for audio/video communication are shown.

![stats relation](https://moert09.gitlab.io/master-thesis/files/stats-relation.svg)

**Comment by vr000m** [comment]
@MoeRT09 Thanks for producing this. This is good stuff.

For this issue, What we need for the spec should show the interlinking of the objects.

**Comment by vr000m** [comment]
This was fixed by @dontcallmedom with the summary table, closing
