### ISSUE TITLE
RTCIceCandidateStats.deleted can be removed

### ISSUE THREAD

**Issue by na-g** [w3c/webrtc-stats#356]
This field was made redundant by the addition of the onstatsended event, though the accompanying prose may still be useful.

**Comment by vr000m** [comment]
@youennf could you PTAL at this issue and create a PR?

**Comment by youennf** [comment]
Will do, thanks for the reminder!

**Comment by youennf** [comment]
There are potential slight differences between the deleted candidate value definition and the definition of when a candidate is deleted as per https://w3c.github.io/webrtc-stats/#dom-rtcstatstype-local-candidate.

In theory, an ICE transport could free the candidate when it is not used by the selected candidate pair.
The same could apply to a candidate pair that 'disappears' before an ICE restart is done or the connection closed.

I guess for now we can remove the deleted attribute and decide whether we want/need to precise https://w3c.github.io/webrtc-stats/#dom-rtcstatstype-local-candidate and https://w3c.github.io/webrtc-stats/#dom-rtcstatstype-candidate-pair later on.

**Comment by vr000m** [comment]
@youennf Are you asking how to mark unselected by successful ice-candidate-pairs?

**Comment by henbos** [comment]
This was fixed in #462
