### ISSUE TITLE
References to "objectDeleted" can be removed

### ISSUE THREAD

**Issue by na-g** [w3c/webrtc-stats#357]
The onstatsended event work removed objectDeleted but a few straggling references remain in the prose for RTCSenderVideoTrackAttachmentStats and RTCSenderAudioTrackAttachmentStats.  It may be useful to mention that it is expected that an onstatsended event will be fired.

**Comment by youennf** [comment]
Wrote https://github.com/w3c/webrtc-stats/pull/459 when noticing this undefined objectDeleted notion in the spec.

**Comment by henbos** [comment]
This is no longer applicable
