### ISSUE TITLE
RTCIceCandidateType: is it 'relay' or 'relayed'

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-stats#360]
We are defining RTCIceCandidateType in https://w3c.github.io/webrtc-stats/#dom-rtcicecandidatestats-candidatetype
which points to https://w3c.github.io/webrtc-pc/#rtcicecandidatetype-enum which has host/srflx/prflx/relay.

However, both Chrome and Firefox implement a different set of strings -- host/serverreflexive/peerreflexive(?)/relayed.

When was this changed? I recall finding it annoying to have both 'relay' and 'relayed' but not annoying enough to warrant breaking backward compat.

**Comment by vr000m** [comment]
The strings in the enums come from the ABNF in RFC5245 or the latest ICE SDP spec. 

‘’’
candidate-types = "host" / "srflx" / "prflx" / "relay" / token
‘’’

**Comment by fippo** [comment]
what the browsers implement comes from https://w3c.github.io/webrtc-stats/archives/20151023/webrtc-stats.html#rtcstatsicecandidatetype-enum

This was changed in #36 

> I think the spec should reflect the standard, so the browsers are perhaps wrong.

I agree the new thing is more aligned but this is a change of deployed code without a migration path. Doesn't help that neither Chrome nor Firefox picked it up in two years.

**Comment by vr000m** [comment]
I hear you. Perhaps report bugs on the respective browsers?

Are you are suggesting to change something here?
