### ISSUE TITLE
Remove track/stream stats in favor of RTCMediaHandlerStats.mid

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-stats#365]
@karthikbr82 said in https://github.com/w3c/webrtc-stats/issues/361#issuecomment-419095016:
> if we are moving "tracks" [to the] Obsolete stats section then we could do the same for "stream".

👍 I suspect "stream" stats existed to help locate relevant stats from a media starting point. This made sense when `pc.addStream` was the media hand-off API. E.g.
```js
pc.addStream(stream);
await negotiate();
const stats = await pc.getStats();
const streamStat = [...stats.values()]
  .find(stat => stat.type == "stream" && stat.streamIdentifier == stream.id);
const [senderStat] = streamStat.trackIds.map(id => stats.get(id));
```

These days, it's probably more helpful to start from a track:
```js
pc.addTransceiver(track);
await negotiate();
const senderStat = [...(await pc.getStats()).values()]
  .find(stat => stat.type == "sender" && stat.trackIdentifier == track.id);
```
But the track isn't stable (may be changed with *replaceTrack*); the *transceiver.mid* is. So better: 
```js
const transceiver = pc.addTransceiver(track);
await negotiate();
const senderStat = [...(await pc.getStats()).values()]
  .find(stat => stat.type == "sender" && stat.mid == transceiver.mid);
```
Of course `transceiver.sender.getStats()` works, but sometimes we need to navigate the big one.

**Comment by henbos** [comment]
TPAC decision: remove "track" and "stream" stats in favor of "mid"; don't need to add streamIdentifiers because that is knowable by other means and not very relevant to stats (if someone want that that should be filed separately).

**Comment by henbos** [comment]
This issue will be inblocked by #498 which exposes the mid on the "transceiver" stats.

**Comment by henbos** [comment]
Not sure which PR, but the "stream" stats have already been made obsolete ([link](https://w3c.github.io/webrtc-stats/#obsolete-rtcmediastreamstats-members)) and making "track" obsolete is tracked in issue #479. Closing this one.
