### ISSUE TITLE
Call out which stats are expected to trigger StatsEnded events

### ISSUE THREAD

**Issue by na-g** [w3c/webrtc-stats#366]
It would be nice to have the stats that are expected to trigger StatsEnded events called out or listed.

**Comment by vr000m** [comment]
@karthikbr82 @pallab-gain could you look into this?

**Comment by alvestrand** [comment]
I thought we'd written "all stats live forever, except those with a delete procedure", but I don't know if that made it into text.

**Comment by jan-ivar** [comment]
I think I owe a PR here.

**Comment by henbos** [comment]
The section "Lifetime considerations for monitored objects" explains deleted, and the "RTCStatsType" section (and other places) calls out when deleted happens. I think we can close this issue as fixed.
