### ISSUE TITLE
RTT metrics in milliseconds or seconds?

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-stats#37]
currently the spec is not clear on what the unit for all RTT measurements are. In one place it says (seconds), and for the other no units are presented. 

Should the RTT metrics be reported in milliseconds or seconds. Since the type is double, I feel the milliseconds for the integer part may be the right resolution.

**Comment by jesup** [comment]
I vote for (and have assumed) ms

**Comment by jan-ivar** [comment]
> Since the type is double, I feel the milliseconds for the integer part may be the right resolution. 

That seems counter-intuitive to me. Had you said "Since the type is integer", I would have bought ms.

But with floating point, why not just assume the base unit?

FWIW we've implemented `jitter` and `mozRtt` since Firefox 30 (both in seconds).

**Comment by jan-ivar** [comment]
> currently the spec is not clear on what the unit for all RTT measurements are. In one place it says (seconds), and for the other no units are presented. 

@vr000m The place where it says "seconds" was committed by you on [Aug 29, 2014](https://github.com/w3c/webrtc-stats/commit/7c40ead6a6e0f2fe75092def27dc75418c5ef339).

The place with no mention of unit was committed by you on [Feb 2, 2015](https://github.com/w3c/webrtc-stats/commit/212576fdae0fc027d59c4d8d5487404a54811a0b).

So for at least 6 months it was consistent. ;-)

**Comment by jesup** [comment]
I'll revise -- with floating point, seconds makes sense.

**Comment by vr000m** [comment]
@jan-ivar, my implementation of STUN-PATH-CHAR draft uses milliseconds, although the spec itself does not say what it should be measured in. 

If we have converged on seconds, I'll fix my PR to seconds and move ahead.

**Comment by alvestrand** [comment]
PR #44 (wrong title) will set it to seconds.
