### ISSUE TITLE
audioLevel can be removed from 'csrc'

### ISSUE THREAD

**Issue by karthikbr82** [w3c/webrtc-stats#370]
RTCRtpContributingSourceStats contains audioLevel and also in RTCAudioHandlerStats, So its duplicated value and can be removed from RTCRtpContributingSourceStats.

**Comment by na-g** [comment]
The audioLevel in RTCRtpContributingSourceStats is the contribution of a single participant in a mixed audio stream, not the audio level of the whole stream. There is no descriptive text of RTCAudioHandlerStats in the draft yet, but it looks like it applies to the whole stream.
