### ISSUE TITLE
[DataChannels] Use RTT from sctp in the stats

### ISSUE THREAD

**Issue by shacharz** [w3c/webrtc-stats#376]
SCTP keeps an RTT parameter which is constantly being adjusted as data is being sent through the channel. Using that RTT can be significantly more accurate than using the ICE heartbeeting. Furthermore, browsers (such as Firefox) would find it easier to implement for data channel only peer connections. @nils-ohlmeier

**Comment by alvestrand** [comment]
The SCTP RTT should probably be exposed on an SCTPTransport stats object. we don't have such an object at the moment, but we can add one.

**Comment by alvestrand** [comment]
Is this exposed on the usrsctp API?

**Comment by lgrahl** [comment]
Untested but it should be there: https://tools.ietf.org/html/rfc6458#section-8.2.2 (`spinfo_srtt`).

**Comment by vr000m** [comment]
> SCTP RTT versus Using that RTT can be significantly more accurate than using the ICE heart-beating. 

Is the issue about accuracy a question about how often the RTT is calculated (i.e., SCTP updates per packet or window) versus ICE heartbeats happen at longer intervals (1s or similar)?

**Comment by shacharz** [comment]
> Is the issue about accuracy a question about how often the RTT is calculated by the protocols (i.e., SCTP updates per packet or window) versus ICE heartbeats happen at longer intervals (1s or similar)?

yes, that's my understanding of it

**Comment by vr000m** [comment]
Since, we expose RTT each level, it make sense to expose the round-trip time for SCTP. 
If you can make a PR, I can review it.

**Comment by nils-ohlmeier** [comment]
> Is the issue about accuracy a question about how often the RTT is calculated by the protocols (i.e., SCTP updates per packet or window) versus ICE heartbeats happen at longer intervals (1s or similar)?

You are assuming that ICE measures RTT in the first place. Which Firefox ICE does not. So if we can get the SCTP RTT instead it helps.

**Comment by vr000m** [comment]
@nils-ohlmeier I am not opposed to more accurate measurements from across the pipeline. If someone can make a PR, I am happy to review it.

**Comment by henbos** [comment]
TPAC decision: Add RTCSctpTransportStats with RTT metrics. If there is an accumulative counter that is standardized so we can reference it prefer that, otherwise use [spinfo_srtt in RFC6458](https://tools.ietf.org/html/rfc6458#section-8.2.2) as a "the current smoothed round-trip time" but convert it to seconds.
