### ISSUE TITLE
[DataChannels] Expose bandwidth or congestion window from the SCTP lib

### ISSUE THREAD

**Issue by shacharz** [w3c/webrtc-stats#377]
It can be very helpful for applications to get the bandwidth/c_wnd from the SCTP layer, so it can adjust business logic accordingly.
@lgrahl

**Comment by alvestrand** [comment]
How is this supposed to work when SCTP runs on top of DTLS which runs on top of ICE?

**Comment by lgrahl** [comment]
For SCTP, UDP/DTLS looks like a raw socket (and AFAIK pretty much behaves like that).

**Comment by vr000m** [comment]
I am curious what things can the application can do in response to the c_wnd stats?

**Comment by lgrahl** [comment]
That is indeed an interesting question since we already have a (quirky) flow control with `.bufferedAmount` and friends.

**Comment by shacharz** [comment]
> I am curious what things can the application can do in response to the c_wnd stats?

decide whether to send data to this client or another (each client is connected to multiple others)

**Comment by vr000m** [comment]
Since, we are on the topic of this, what other SCTP stats would applications want to use? also are there any other SCTP metrics that would be interesting for the app

**Comment by shacharz** [comment]
> That's a bug.

AFAIK it's not a bug, since bufferedAmount don't include the sctp buffer.


> Since, we are on the topic of this, what other SCTP stats would applications want to use? also are there any other SCTP metrics that would be interesting for the app

- opened a different issue for RTT
- packet loss would also be interesting.
- also interesting but more futuristic, for us at least: maximum size for data payload before packet will be split to 2 (mtu - all the headers calculation)

**Comment by lgrahl** [comment]
> > That's a bug.
> 
> AFAIK it's not a bug, since bufferedAmount don't include the sctp buffer.

It is definitely a bug. See the [corresponding spec section](https://w3c.github.io/webrtc-pc/#dom-rtcdatachannel-bufferedamount). The only reason why all implementations are affected by this is because they all use usrsctp which currently does not expose that information.

> Since, we are on the topic of this, what other SCTP stats would applications want to use? also are there any other SCTP metrics that would be interesting for the app

I'm not seeing further items that should be in the stats (there are a couple that could be added to `RTCSctpTransport` at some point, such as MTU, partial delivery point, RT max, RTO initial/min/max, heartbeat interval, ...). Arguably, some of these *could* also be in the stats but I'm not entirely convinced about that so far.

> also interesting but more futuristic, for us at least: maximum size for data payload before packet will be split to 2 (mtu - all the headers calculation)

I believe that should not be in the stats but rather on the `RTCSctpTransport`. Interesting candidates are https://tools.ietf.org/html/rfc6458#section-8.2.1 `sstat_fragmentation_point` and https://tools.ietf.org/html/rfc6458#section-8.2.2 `spinfo_mtu` (I'm not sure what's the difference between those two and would have to ping my fellow SCTP expert for that).

**Comment by shacharz** [comment]
yea, I agree that these attributes are more fit for `RTCSctpTransport` instead of stats.
But the sad story is [lack of support](<https://wpt.fyi/results/webrtc/RTCSctpTransport-constructor.html?aligned&label=stable>)

**Comment by lgrahl** [comment]
Tell me about it.  :disappointed:

**Comment by shacharz** [comment]
if you haven't already upvote:
[chrome](<https://bugs.chromium.org/p/chromium/issues/detail?id=818643&q=RTCSctpTransport&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified>)
[ff1](<https://bugzilla.mozilla.org/show_bug.cgi?id=1278299>)[ff2](<https://bugzilla.mozilla.org/show_bug.cgi?id=1307996>)

**Comment by lennart-csio** [comment]
> Since, we are on the topic of this, what other SCTP stats would applications want to use? also are there any other SCTP metrics that would be interesting for the app

when i worked with datachannels (full bulk) i had no clue what was limiting the throughput, maybe that is something to work on. not sure what is needed for this, though, i guess basic network stats like throughput, loss, and rtt is a start. having cwnd is of much interest for understanding this as well if one is familiar with protocol behavior.
my guess is that the limitation is also often from browser resources? no idea how to measure that. maybe processing time?

**Comment by lgrahl** [comment]
> i guess basic network stats like throughput, loss, and rtt is a start

* Throughput can be calculated,
* I haven't found the number of retransmissions for a specific stream in the SCTP socket API (@tuexen?)
* RTT is #376.

**Comment by alvestrand** [comment]
these are stats on SCTP transport, not on each datachannel, right?

**Comment by vr000m** [comment]
@lennart-csio @lgrahl could you make a proposal.

**Comment by lgrahl** [comment]
Sorry, too busy with other work.

**Comment by henbos** [comment]
> > bufferedAmount is not relevant for sending somewhat small chunks of data and not big files since it'll always remain 0
> 
> That's a bug.

Didn't we (Chrome) fix that?

**Comment by henbos** [comment]
TPAC decision: Exposing congestion information for use in application deserves a proper API and we should file an issue on [webrtc-nv-use-cases](https://github.com/w3c/webrtc-nv-use-cases/issues), getStats() is not the right place for this.
