### ISSUE TITLE
Width and Height of Simulcast layers sent

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-stats#378]
@jan-ivar has suggested that this might be a useful statistic (and topic for discussion at TPAC).

**Comment by jan-ivar** [comment]
For context, this came from discussion in https://github.com/w3c/webrtc-stats/issues/318#issuecomment-431346946.

With simulcast, there'd be multiple `"outbound-rtp"` stats whose `stat.senderId`s match.

But unfortunately, `frameWidth`, `frameHeight`, `framesPerSecond`, `framesSent`, `hugeFramesSent`, `keyFramesSent` hang off of `"sender"` stats.

Only `framesCaptured` would survive.

**Comment by jan-ivar** [comment]
Options I see:
 1. Move all but *framesCaptured* to `"outbound-rtp"`.
 2. Have more than one `"sender"` stats floating around in the simulcast case.

**Comment by henbos** [comment]
Closing this issue, follow-up at #400 and #402.
