### ISSUE TITLE
RTCPeerConnectionStats appear redundant. Remove?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-stats#382]
There are events for all the data in [RTCPeerConnectionStats](https://w3c.github.io/webrtc-stats/#dom-rtcpeerconnectionstats). Seems redundant, and fails the minimal API test. Can we remove it?

cc @alvestrand @vr000m

**Comment by vr000m** [comment]
@karthikbr82 is the javascript able to addEventHandler for the events exposed for the datachannel events?

@henbos  I cant quite remember what we discussed before, but there was some stats we wanted to add to PCStats? any idea what those were? It would help If you could link those issues to this request.

**Comment by alvestrand** [comment]
What do events have to do with it?
There are lots of things that a JS app could measure by counting things happening every time they happen (such as counting outgoing bytes on a datachannel by instrumenting every send() call), but we make these things available in an aggregated fashion by making stats for them.

I don't understand why this is a logical argument in favor of removing the object.

**Comment by jan-ivar** [comment]
> such as counting outgoing bytes on a datachannel by instrumenting every send() call

That won't tell you how many bytes were actually sent, or whether the message was fully delivered, since `send()` returns immediately.

I think we should focus on things the JS app cannot easily measure, since we have almost [300](https://webrtc-stats.callstats.io/verify/) stats to implement.

No JS app needs the browser to tell it how often it called `pc.createDataChannel()`, or how often events fired. Here:
```js
pc.addEventListener('datachannel' () => dataChannelsAccepted++);

function createDataChannel(...args) {
  const channel = pc.createDataChannel(...args);
  dataChannelsRequested++;
  channel.addEventListener('open', () => dataChannelsOpened++);
  channel.addEventListener('closed', () => dataChannelsClosed++);
}
```
We have lots of precedent for axing things that aren't necessary.

**Comment by vr000m** [comment]
Marking the decision as: No. not well enough justified. Closing the issue.

**Comment by jan-ivar** [comment]
I wrote 5 lines of JavaScript to replace it. What more justification do we need?

**Comment by na-g** [comment]
@alvestrand , it is possible for the application application to know with certainty how may times it called pc.createDataChannel(). This is not true of bytesSent, the application can only know how many bytes it has requested to be sent and so this stat must be gathered on the caller's behalf. I think this distinction is important.
