### ISSUE TITLE
Mark up duplicate definition of RTCStats dictionary

### ISSUE THREAD

**Issue by foolip** [w3c/webrtc-stats#385]
https://w3c.github.io/webrtc-stats/#basic-concepts has a duplicate definition of https://w3c.github.io/webrtc-pc/#rtcstats-dictionary, clearly marked as duplicate for a human reader.

However, it's still extracted into https://github.com/tidoust/reffy-reports/blob/master/w3c/idl/webrtc-stats.idl, and a machine readable annotation is needed to exclude it.

@tidoust looking at https://github.com/tidoust/reffy/blob/master/src/cli/extract-webidl.js I can't now find what the class to omit IDL is, can you help?

**Comment by tidoust** [comment]
@foolip There is no class to omit IDL in Reffy yet. We talked about it in https://github.com/tidoust/reffy/issues/123 but I haven't implemented support for the `extract` class for now.

Reffy extracts the IDL index generated by Respec and Bikeshed, which exclude IDL definitions that have an `extract` class. But the `webrtc-stats` spec does not seem to have any IDL index, so Reffy extracts individual IDL snippets and will include the offending definition no matter what.

**Comment by tidoust** [comment]
@foolip FYI, I have an update ready for Reffy, which I'll merge as soon as I'm able to test it on all specs to make sure I didn't break anything: https://github.com/tidoust/reffy/pull/137

Note I followed Respec's convention that actually reacts on the `exclude` class name (which seems a better name than `extract`) and which also drops IDL definition that appear in informative sections.

**Comment by foolip** [comment]
Excellent, thank you! @mdittmer, does this match the rules you had for excluding IDL blocks in https://github.com/mdittmer/web-apis?

**Comment by alvestrand** [comment]
So exactly what should we write? @foolip can you write the PR?

**Comment by foolip** [comment]
Turns out that nothing needs to be done because this IDL block is in a section with `class="informative"`. After https://github.com/tidoust/reffy/pull/137 was merged, the block went away from reffy-reports:
https://github.com/tidoust/reffy-reports/commit/85b22abe3b0f4c02973a7b37ff6980c82bb182fb#diff-fbaa84965dfc6b232dec19ef1ccb7344

Amazingly, nothing else was removed because of accidentally being in an informative section or anything like that. Either @tidoust has amazing intuition about what will work, or the PR was tested against the corpus of specs first :)
