### ISSUE TITLE
Need to add the fractionLost into the dictionary RTCInboundRtpStreamStats

### ISSUE THREAD

**Issue by karthikbr82** [w3c/webrtc-stats#388]
https://w3c.github.io/webrtc-stats/#inboundrtpstats-dict* 

RTCInboundRtpStreamStats Dictionary is missing fractionLost.

Creating this issue based on an email sent to the public-webRTC group from elias.sun@ringcentral.com

(I filed a bug to the Firefox about the fractionLost is missed in the 'inbound-rtp ‘. However, the guy in the Firefox team complains this field is not in the dictionary RTCInboundRtpStreamStats , so the Firefox will not support it. However, the top of this web page has the statement as below, 

An implementation MUST support generating statistics for the type RTCInboundRtpStreamStats, with attributes packetsReceived, bytesReceived, packetsLost, jitter, and fractionLost.Please add the fractionLost into the dictionary RTCInboundRtpStreamStats officially. By the way, Chrome and Safari support it.)

**Comment by alvestrand** [comment]
This stat is now in the dictionary RTCRemoteInboundRtpStreamStats - it is reporting on the value of a field in an RTCP message; the stat is in a format that is rather problematic (fraction lost since last report sent).

Why do you need this, rather than computing your own loss statistics from # of packets received and # of packets lost, both of which are members of RTCReceivedRtpStreamStats?

**Comment by henbos** [comment]
Two observations:

- The [Conformance](https://w3c.github.io/webrtc-stats/#conformance) section in webrtc-stats is not up-to-date with the dictionary hierarchy and should be updated. It does however mandate fractionLost. This is not authoritative - "They should put in their document text like this" - (soft "should"), but it certainly sounds like a recommendation.
- The [Mandatory to implement](https://w3c.github.io/webrtc-pc/#mandatory-to-implement-stats) section of webrtc-pc, which is more up-to-date, does not mandate fractionLost.

Having two mandatory sections seems confusing, especially if they're contradicting.

**Comment by eliassun** [comment]
hi Henrik, alvestrand,
  I think [Conformance](https://w3c.github.io/webrtc-stats/#conformance) should be updated if it is really out of date. 
  I do see Google and Apple implemented the fractionLost in the inbound-rtp, which is useful to me. If the industry has implemented it in the real web browsers, I think it is good to make it official to all browsers. 

**Google Chrome implementation:**
 ID: RTCCodec_audio_Inbound_0 
Timestamp: 1549480434040.71
payloadType : 0
mimeType : audio/PCMU
clockRate : 8000
Report: codec 
 ID: RTCCodec_audio_Inbound_103 
Timestamp: 1549480434040.71
payloadType : 103
mimeType : audio/ISAC
clockRate : 16000
Report: codec 
 ID: RTCCodec_audio_Inbound_104 
Timestamp: 1549480434040.71
payloadType : 104
mimeType : audio/ISAC
clockRate : 32000
Report: codec 
 ID: RTCCodec_audio_Inbound_105 
Timestamp: 1549480434040.71
payloadType : 105
mimeType : audio/CN
clockRate : 16000
Report: codec 
 ID: RTCCodec_audio_Inbound_106 
Timestamp: 1549480434040.71
payloadType : 106
mimeType : audio/CN
clockRate : 32000
Report: codec 
 ID: RTCCodec_audio_Inbound_110 
Timestamp: 1549480434040.71
payloadType : 110
mimeType : audio/telephone-event
clockRate : 48000
Report: codec 
 ID: RTCCodec_audio_Inbound_111 
Timestamp: 1549480434040.71
payloadType : 111
mimeType : audio/opus
clockRate : 48000
Report: codec 
 ID: RTCCodec_audio_Inbound_112 
Timestamp: 1549480434040.71
payloadType : 112
mimeType : audio/telephone-event
clockRate : 32000
Report: codec 
 ID: RTCCodec_audio_Inbound_113 
Timestamp: 1549480434040.71
payloadType : 113
mimeType : audio/telephone-event
clockRate : 16000
Report: codec 
 ID: RTCCodec_audio_Inbound_126 
Timestamp: 1549480434040.71
payloadType : 126
mimeType : audio/telephone-event
clockRate : 8000
Report: codec 
 ID: RTCCodec_audio_Inbound_13 
Timestamp: 1549480434040.71
payloadType : 13
mimeType : audio/CN
clockRate : 8000
Report: codec 
 ID: RTCCodec_audio_Inbound_8 
Timestamp: 1549480434040.71
payloadType : 8
mimeType : audio/PCMA
clockRate : 8000
Report: codec 
 ID: RTCCodec_audio_Outbound_110 
Timestamp: 1549480434040.71
payloadType : 110
mimeType : audio/telephone-event
clockRate : 48000
Report: codec 
 ID: RTCCodec_audio_Outbound_111 
Timestamp: 1549480434040.71
payloadType : 111
mimeType : audio/OPUS
clockRate : 48000
Report: candidate-pair 
 ID: RTCIceCandidatePair_Mn5U3fjw_GFS2aJOQ 
Timestamp: 1549480434040.71
transportId : RTCTransport_audio_1
localCandidateId : RTCIceCandidate_Mn5U3fjw
remoteCandidateId : RTCIceCandidate_GFS2aJOQ
state : succeeded
priority : 7961835276064522000
nominated : true
writable : true
bytesSent : 78140
bytesReceived : 42859
totalRoundTripTime : 2.561
currentRoundTripTime : 1.055
availableOutgoingBitrate : 300000
requestsReceived : 1
requestsSent : 1
responsesReceived : 11
responsesSent : 1
consentRequestsSent : 10
Report: remote-candidate 
 ID: RTCIceCandidate_GFS2aJOQ 
Timestamp: 1549480434040.71
transportId : RTCTransport_audio_1
isRemote : true
ip : 104.245.57.253
port : 29620
protocol : udp
candidateType : host
priority : 2130706431
deleted : false
Report: local-candidate 
 ID: RTCIceCandidate_Mn5U3fjw 
Timestamp: 1549480434040.71
transportId : RTCTransport_audio_1
isRemote : false
networkType : wifi
ip : 50.207.16.19
port : 64597
protocol : udp
candidateType : prflx
priority : 1853759231
deleted : false
Report: inbound-rtp 
 ID: RTCInboundRTPAudioStream_1431023951 
Timestamp: 1549480434040.71
ssrc : 1431023951
isRemote : false
mediaType : audio
kind : audio
trackId : RTCMediaStreamTrack_receiver_5
transportId : RTCTransport_audio_1
codecId : RTCCodec_audio_Inbound_111
packetsReceived : 798
bytesReceived : 33701
packetsLost : 2
jitter : 0.013
fractionLost : 0.00390625


**Apple Safari Implementation**
 ID: RTCIceCandidatePair_tVocIxe0_El0Ca/cc 
Timestamp: 1549481466931
availableIncomingBitrate : 0
availableOutgoingBitrate : 300000
bytesReceived : 232470
bytesSent : 438569
currentRoundTripTime : 1.053
localCandidateId : RTCIceCandidate_tVocIxe0
nominated : true
priority : 7926369428998980000
readable : false
remoteCandidateId : RTCIceCandidate_El0Ca/cc
requestsReceived : 2
requestsSent : 2
responsesReceived : 40
responsesSent : 2
state : succeeded
totalRoundTripTime : 7.157
transportId : RTCTransport_audio_1
writable : true
Report: inbound-rtp 
 ID: RTCInboundRTPAudioStream_3906964699 
Timestamp: 1549481466931
firCount : 0
isRemote : false
nackCount : 0
pliCount : 0
qpSum : 0
sliCount : 0
ssrc : 2
burstDiscardCount : 0
burstDiscardRate : 0
burstLossCount : 0
burstLossRate : 0
burstPacketsDiscarded : 0
burstPacketsLost : 0
bytesReceived : 212716
fractionLost : 0.09375
framesDecoded : 0
gapDiscardRate : 0
gapLossRate : 0
jitter : 0.001
packetsDiscarded : 0
packetsLost : 53
packetsReceived : 4483
packetsRepaired : 0

For the details , please check my ticket filed to Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1525692 .

**Comment by alvestrand** [comment]
The relevant change is #283 (December 2017) which was based on bug #255.

#283 failed to add RTCInboundStreamStats.fractionLost to "obsolete stats".

I have prepared PR #389 to fix this issue (and also make the note about the conformance text being an example have some words in ALL CAPS for emphasis).

**Comment by eliassun** [comment]
Yes, it sounds reasonable to fix the document only. I am good with the decisions above.
