### ISSUE TITLE
Rename nackCount to nacksReceived & nacksSent respectively?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-stats#390]
From @vr000m in https://github.com/w3c/webrtc-stats/pull/384#pullrequestreview-195542744:
> When it was in the base class, the ambigious *Count name made sense because the text described how the counters were updated at the sender and receiver. Now that these metrics are being moved to the appropriate dictionary, we can add the suffix -Sent/-Received qualifier.
> 
> If we are going down this path, I would encourage the -suffix, but that would require retiring the -Count metrics.
> 
> Browsers that have implemented these -Count metrics should also chime in? @henbos @aboba @jan-ivar @youennf

I don't actually think we can afford this at this point due to web compat, but I'm breaking this out as a separate issue, for discussion.

**Comment by alvestrand** [comment]
Closing this one as "won't do because it's implemented with the old name".
