### ISSUE TITLE
framesDecoded is on both "receiver" and "inbound-rtp"

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-stats#392]
Their descriptions are identical. Where do we want it to live?
 1. https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-framesdecoded
 2. https://w3c.github.io/webrtc-stats/#dom-rtcvideoreceiverstats-framesdecoded

The inverse [framesEncoded](https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-framesencoded) lives on `"outbound-rtp"`, which suggests (1).

But then [framesDropped](https://w3c.github.io/webrtc-stats/#dom-rtcvideoreceiverstats-framesdropped) lives on (2).

I'm trying not to be influenced by (2) having a dedicated video type.

**Comment by vr000m** [comment]
Related to #402

**Comment by henbos** [comment]
This has since been moved to the obsolete section, so it's only on the inbound-rtp now. I think we can close this issue?
