### ISSUE TITLE
RTC[Audio/Video]SenderStats should have mid

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#396]

**Comment by henbos** [comment]
See also #396

**Comment by alvestrand** [comment]
MID is a transceiver property. Shouldn't it be enough to have it in transceiver stats?
Do we have any transceiver stats?

**Comment by henbos** [comment]
We don't have any transceiver stats and there would be little use for them, but at the moment there is not much more use for sender/receiver stats than transceiver stats. I filed #478

**Comment by henbos** [comment]
There's also #479 for removing "sender" stats, though "mid" would be a reason for keeping them, unless we add "transceiver" stats.

**Comment by henbos** [comment]
TPAC decision: Add transceiver { senderId, receiverId, mid }, but file separate issues where we can discuss whether or not we want other fields (such as direction, currentDirection and codecIds).

**Comment by aboba** [comment]
@henbos Can we review the PR at the November 2019 interim?  Or even better, can we merge it and close this issue?

**Comment by henbos** [comment]
Made obsolete by #478 which has PR
