### ISSUE TITLE
Add RTCEncodingParameterStats

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#398]

**Comment by henbos** [comment]
This one: https://w3c.github.io/webrtc-pc/#dom-rtcrtpencodingparameters

**Comment by vr000m** [comment]
@aboba suggested also exposing scalabilityModes from https://w3c.github.io/webrtc-svc/#dom-rtcrtpencodingparameters-scalabilitymode

```
partial dictionary RTCRtpCodecCapabilities {
    sequence<DOMString> scalabilityModes;
};
```

**Comment by henbos** [comment]
TPAC decision: add "rid" to "outbound-rtp", but don't add "encoding-parameters" (unless we have a specific use case) because this information is already available in getParameters().

**Comment by henbos** [comment]
Per TPAC decision I am closing this issue. Adding the "rid" is tracked in #395
