### ISSUE TITLE
Move all stream stats from the "sender"/"receiver" stats

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#402]
Any RTP media related metrics should be placed on "outbound-rtp" or "inbound-rtp" accordingly. One "sender" could have multiple "outbound-rtp" due to simulcast, so having counters on a per-"sender" basis is wrong. For symmetry, conceptual correctness, and for more future-proof way of thinking, we should do the same thing for "receiver" and "inbound-rtp", even though today a "receiver" only ever has a single "inbound-rtp" object.

**Comment by vr000m** [comment]
This may have an impact on track stats...

**Comment by henbos** [comment]
See also #392

**Comment by vr000m** [comment]
How do we resolve this one, @henbos -- quite a few stats depend on this issue.

**Comment by henbos** [comment]
I might be able to take a stab at it before next meeting, but I can't promise anything, I'm trying to ramp up on a new project. Otherwise do we have anyone on your side that can take it?

**Comment by henbos** [comment]
With #463 and #466, this is now fixed.
