### ISSUE TITLE
References to undefined RTCReceiverAudioTrackAttachmentStats and RTCReceiverVideoTrackAttachmentStats

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-stats#414]
The definition of `trackId` in`RTCInboundRtpStreamStats` refers to `RTCReceiverAudioTrackAttachmentStats` and `RTCReceiverVideoTrackAttachmentStats`, but no such dictionaries exist.

**Comment by vr000m** [comment]
This may depend on the Issue opened by @henbos on #403.

**Comment by alvestrand** [comment]
RTCSenderAudioTrackAttachmentStats exists. I think we're missing the other 3 (empty) dictionaries.

**Comment by henbos** [comment]
I filed #424 which covers this one, merging this into that.
