### ISSUE TITLE
Rethinking RTCOutboundRtpStreamStats.targetBitrate

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#416]
Knowing something about the target encode bitrate is important, for example when debugging issues related to too large frames being encoded.

The current definition of [targetBitrate](https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-targetbitrate) is:

> It is the current target bitrate configured for this particular SSRC and is the Transport Independent Application Specific (TIAS) bitrate [RFC3890]. Typically, the target bitrate is a configuration parameter provided to the codec's encoder and does not count the size of the IP or other transport layers like TCP or UDP. It is measured in bits per second and the bitrate is calculated over a 1 second window.

Two problems:
- Measuring the bitrate over a 1 second window is not what implementations necessarily should do. Chrome doesn't. We should not force implementation strategies about when this bitrate can and cannot update the target.
- This is a bitrate. If an application would like calculate the difference between target and actual bytes produced, there is no way to do this. You would have to estimate target total bytes based on bitrate and compare to total bytes sent. Why doesn't the stat provide accumulative counters instead?

**Proposal**
Replace targetBitrate with targetTotalBytesEncoded, to be defined as:

> The total number of bytes the encoder would have produced if it exactly matched the configured target. In reality, the actual number of bytes may be higher or lower on a frame-by-frame basis. This value is updated each time a frame has been encoded.

This definition is agnostic towards when or how the target is updated, the counter would go up with whatever the target was for each frame, which makes it directly comparable to bytesSent.

**Comment by alvestrand** [comment]
Given that targetBitrate is currently deployed, and easily understandable, my suggestion is to fix that by removing the "calculated over an 1 second window" text and replace it with "This statistic gives the configured target bitrate at the time of the stats timestamp".

I'm all in favor of adding targetTotalBytesEncoded as a new stat, in order to give the ability to inspect history, but I'm not in favor of removing the old one.

**Comment by henbos** [comment]
OK. Updating the "calculated over an 1 second window" is enough to unblock me, and targetTotalBytesEncoded is a nice bonus. I'll make a PR with both changes and we can follow up there.
