### ISSUE TITLE
Make targetBitrate obsolete (was: targetBitrate should not be "measured over 1 second window")

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#423]
This is a spin-off issue from #416.
While rate measurements have to be measured over a specific time interval, a "target" is not a measurement, it is a goal, this could vary on a frame-by-frame basis and depending on your framerate you might have to overshoot or undershoot this to different degrees for a particular frame. There's also a difference between key frames and non-key frames and the nature of the frames being encoded.

This stat description should reflect the fact that this is an encoder setting and be agnostic towards when or how the implementation modifies the target.

**Comment by henbos** [comment]
Quoting @vr000m from previous discussions:

> Split the discussion on 1-second window... (We are undoing #13). At the time we thought TIAS was needed for the bitrate definition and TIAS seemed appropriate and perhaps at the time, rates needed a window to be defined.
> 
> This brings in if TIAS is really appropriate for target bitrate, since TIAS is the maximum session bitrate.
> 
> > The Transport Independent Application Specific Maximum (TIAS)
> > bandwidth modifier has an integer bit-rate value in bits per second.
> > A fractional bandwidth value SHALL always be rounded up to the next
> > integer. The bandwidth value is the maximum needed by the
> > application (SDP session level) or media stream (SDP media level)
> > without counting IP or other transport layers like TCP or UDP.
> 
> In this case, 1-second window is perhaps not needed because it is possible that the encoded may never achieve this rate. We should also point out that the target bit rate can change often, as often as generating a new frame or upon receiving a packet.

**Comment by henbos** [comment]
Given that we now have [totalEncodedBytesTarget](https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-totalencodedbytestarget) and you can calculate bitrate from it (e.g. totalEncodedBytesTarget/s by doing delta bytes divided by delta timestamp), I propose we simply move this stat to the obsolete section; it was never implemented by Chrome.

**Comment by vr000m** [comment]
@lennart-csio WDYT? remove this?

**Comment by henbos** [comment]
The previous metric was under-specified and not implemented, and the new metric is well-defined and shipped ;)

**Comment by henbos** [comment]
See #560 why I'm closing this and following it up there.
