### ISSUE TITLE
Receiver attachment stats missing

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#424]
RTCReceiverAudioTrackAttachmentStats and RTCReceiverVideoTrackAttachmentStats are referenced by [RTCInboundRtpStreamStats.trackId](https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-trackid), but these do not exist.

These are from the old way of thinking, before we had "receiver" stats, as a receiving track attachment stats object would be identical to the "receiver" stats object. However this is what is currently shipped in Chrome, and it seems a bit asymmetrical to have sender attachment "track" stats but not receiver attachment "track" stats.

We should either add these to the main section or to the obsolete stats section. If added to the obsolete section then we need to move "trackId" there as well.

**Comment by henbos** [comment]
See also #403, though I think this needs to be addressed regardless.

**Comment by jan-ivar** [comment]
> If added to the obsolete section then we need to move "trackId" there as well.

I vote for this. There's no symmetry here, so appearance of symmetry where there is none, is a problem rather than a desirable property IMHO.

There are no "track attachments" on the receiver. `"receiver"` stats and `"track"` stats are 100% the same.

**Comment by henbos** [comment]
Opinion poll: Long term, assuming all browsers had sender and receiver stats fully implemented, would you like to see "track" stats as something mandated or as legacy section dictionary? @jan-ivar 
I've viewed it as a remnant of the "old way" of thinking, though it's arguably a useful slicing of the "sender" stats, that combined with onstatsended...

**Comment by jan-ivar** [comment]
I think we should ask:
 1. Do we need "track" stats sender-side?
 2. Do we need "track" stats receiver-side?

I don't think they're related, and I think the answer to 2. is unequivocally no.

**Comment by vr000m** [comment]
2. Tracks at the receiver are not needed. because they are not supposed to change.

On the sender, I am still waiting to see how we get around the replace tracks issue.

**Comment by henbos** [comment]
I think we should add receiver attachment stats to the obsolete section to reflect the fact that receiving "track" stats are implemented in Chrome. (Then, when we feel like going wild, we can move everything to the obsolete section #479 ;) )

**Comment by henbos** [comment]
This is a duplicate of https://github.com/w3c/webrtc-stats/issues/452 and others, closing
