### ISSUE TITLE
Byte/packet counter type consistency (retransmittedPacketsSent is unsigned long long)

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#425]
Generally speaking, currently in the spec byte counters are "unsigned long long" but packet counters are "unsigned long". Should we continue this pattern or should we use "unsigned long long" for everything?

A recent PR added both retransmittedBytesSent and retransmittedPacketsSent. Both were added as "unsigned long long". Should retransmitedPacketsSent be "unsigned long"?

**Comment by vr000m** [comment]
@karthikbr82 PTAL.
