### ISSUE TITLE
RTCRemoteInboundRtpStreamStats: total round trip time

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#426]
[RTCRemoteInboundRtpStreamStats.roundTripTime](https://w3c.github.io/webrtc-stats/#dom-rtcremoteinboundrtpstreamstats-roundtriptime) is only the [latest estimate](https://tools.ietf.org/html/rfc3550#section-6.4.1) (scroll down to "delay since last SR (DLSR): 32 bits").

To allow calculating averages we should do the same thing that we did with regards to RTCIceCandidatePairStats - have a `totalRoundTripTime` and a counter that gets up every time you calculate a sample, i.e. every time you get a Receiver Report... or more accurately, every time you get a Report Block; `reportsReceived`.

**Comment by vr000m** [comment]
No issues with doing `totalRoundTripTime` And IIUC you are making a proposal for `reportsReceived` and `reportsSent`, which I thought we already had... if we dont have these, it makes sense to add them.

> averageRtcpInterval of type double
>
>The average RTCP interval between two consecutive compound RTCP packets. This is calculated by the sending endpoint when sending compound RTCP reports. Compound packets must contain at least a RTCP RR or SR packet and an SDES packet with the CNAME item.

if we go with reportSent/Received, I would ament the above . to do totalRtcpInterval and divide it with the report counters.

---

Reasons  we were fine with the most current value or latest RTT estimate:

RTCP Reports are not sent very often, according to RFC3550 they are sent 5 +/- 2.5 seconds, i.e., as early as 2.5s or as late as 7.5s, and the RTCP interval value changes after each RTCP. And if we poll getStats API at say 1 or 2s intervals, we should be fine. 

However, if the RTCP interval were shorter than the polling interval for getStats (there are several cases, where people poll just at the end of the call)... the totalRoundTripTime would be useful.

Also it should be noted that if we poll getStats more often than RTCP interval, we would get the same value and timestamp for these remote reports would be the same.

**Comment by vr000m** [comment]
@pallab-gain PTAL.

**Comment by henbos** [comment]
This is probably still worth doing. However, in Chrome remote-inbound-rtp reports are updated about once per second, so it feels like we'd have an estimate about as often as we poll getStats(), so there won't be much variety here, and thus less need for an accumulative counter. But having it would allow things like average RTT over a long period of time, such as last 10 s or entire call

**Comment by henbos** [comment]
(Or perhaps it was every few seconds)
