### ISSUE TITLE
RTCSenderAudioTrackAttachmentStats: Audio Device Errors

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-stats#429]
Audio device errors can occur when attempting to initialize a microphone or speaker, or they can occur on an ongoing basis.  When occurring at initialization, an error will result in the `getUserMedia` promise being rejected with a new `DOMException` object whose name attribute has values such as `NotReadableError` or `AbortError` (see Media Capture and Streams Section 10.2).   Currently there is no mechanism within the media capture API that provides errors on an ongoing basis. 

Currently there are no statistics kept relating to audio device errors and the devices that experienced them (as identified in `track.label`).  Also, there are no statistics kept on:

o       Time period that the speaker or microphone was muted (at a lower level than app where the app is unaware)
o       Master (and where applicable, session) volume level for render and capture (if analog AGC is not enabled)

With respect to audio errors, it appears possible to provide more detail.  For example, the operating system may provide more information relating to the error type, such as: 

- Already initialized,
- Unsupported format,  
- Buffer too large,
- Device stall,  
- No interface,  
- Device hung, 
- Exclusive mode only 

Currently devices are identified by label, but there is additional Device information which may be helpful for diagnostics purposes (but which might represent additional fingerprinting surface) such as:

o       PID/VID of mic and spk device in use
o       Device form factor (headset / speaker phone / etc.)
o       Device interface (USB/BT/PCI/etc)

**Comment by jan-ivar** [comment]
What audio device? An audio track can come from all sorts of places: *element.captureStream*, *web audio*, another *RTCPeerConnection* track, *getDisplayMedia*, and *getUserMedia* (the microphone).

This seems out of scope for `pc.getStats`, whose scope is to report on the peer connection IMHO.

**Comment by vr000m** [comment]
Open an error/issue on peerconnection or media-capture.

We would consider these if these were measured as counters.
