### ISSUE TITLE
OPUS -- Exposing SILK or CELT mode in getStats

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-stats#432]
We've found that Opus performance can vary depending on what mode it is in. Especially, when it transitions from one mode to another, and it is currently impossible to know when that transition occurs or what mode the encoder is in to begin with.

I am not sure how this information could be exposed in getStats. Any thoughts or proposals?
For example -- counters for each mode, and start-mode and current-mode might make sense.

**Comment by na-g** [comment]
@vr000m do other codecs have similar mode switching behaviors?

**Comment by vr000m** [comment]
As far as I can tell that Opus is a single codec that combined two codecs. Although the SILK codec is not exactly like the SILK in Skype... however, there is a hybrid mode in Opus when a combination of both are used.

I would try to solve this problem rather than look for a general solution.

**Comment by henbos** [comment]
We could have opus-specific counters?

**Comment by vr000m** [comment]
@aboba will provide addition information on the current stats from Opus.

**Comment by vr000m** [comment]
@henbos could someone from Google weigh in on this?

**Comment by vr000m** [comment]
@mvarela do you have thoughts on this, since you are working on the opus quality model.

**Comment by mvarela** [comment]
It would be useful to have the information, of course.

**Comment by henbos** [comment]
@aboba Is this TPAC stuff or not?

**Comment by vr000m** [comment]
This should be TPAC stuff

Founder, CEO, callstats.io ( http://callstats.io )
http://www.callstats.io

Interested in networking, media quality, and diagnostics.
We are hiring!: www.callstats.io/jobs/ ( http://www.callstats.io/jobs/ )

**Comment by aboba** [comment]
@vr00m @henbos If you feel it would help to discuss it at TPAC, go ahead and mark it "TPAC 2019" and add slides to the deck, which is here: https://docs.google.com/presentation/d/1Xprz0ElNTUWRDdX6kyp11cZ4ItTvUFUmzoXsKZdXxuU/

**Comment by henbos** [comment]
I believe this was not discussed at TPAC.
