### ISSUE TITLE
The spec has incorrect assumptions abound SR and RR

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#433]
The spec seems to assume that RTCRemoteInboundRtpStreamStats map 1:1 with a Receiver Report and RTCRemoteOutboundRtpStreamStats map 1:1 with a Sender Report. This may be true when there is only one stream in one direction, but talking with the network folks this does not seem to be true in general.

For example, when both sending and receiving, the "remote-inbound-rtp" objects correspond to _Report Blocks_, but the blocks could have been carried over either in a Sender Report or a Receiver Report.

The reports are just a list of blocks. Also one report may contain blocks for multiple different streams.

The spec is probably correct if we replace the "Sender Report" and "Receiver Report" language by "Report Block" instead.

**Comment by henbos** [comment]
^--- needs more set of eyes to verify @alvestrand @jan-ivar

**Comment by fippo** [comment]
I think saying "Sender Report" and "Receiver Report" is ok, its more useful to think of this as a compound rtcp packet. The only place where I would change it is "Compound packets must contain at least a RTCP RR or SR packet and an SDES packet with the CNAME item. "

**Comment by jan-ivar** [comment]
Thanks @henbos for filing this.

Reading https://www.freesoft.org/CIE/RFC/1889/18.htm helped me. Thanks @na-g!

Apparently, SRs can contain zero or more receiver report blocks, reporting on both directions at once.

RR is an optimization, in other words.

This seems to conflict with this spec's colloquial use of *"Sender Report"* to mean *"the report the sender sent us"*, and *"Receiver report"* to mean *"the report the receiver sent us"*.

I'm happy to review clearer language, but I hope we can avoid ambiguity.

**Comment by henbos** [comment]
/me trying to implement RTCRemoteInboundRtpStreamStats primarily for the sake of roundTripTime and getting confused several times :) thanks for checking

**Comment by vr000m** [comment]
SR and RRs can be sent separately or together in a single message depending on the situation (also implementation). 

RTP-USAGE draft explains this --- https://tools.ietf.org/html/draft-ietf-rtcweb-rtp-usage-26#section-4.1 as "Support for sending and receiving RTCP SR, RR, SDES, and BYE packet types."

We could make the change to `RTCP RR packet types` instead of reports or messages.

**Comment by henbos** [comment]
Is this ready for PR?
