### ISSUE TITLE
RTCStats.id should not be "predictable"

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#437]
This is a request to change webrtc-pc, but filed the issue here to grab the attention of stats editors.

[Current definition](https://w3c.github.io/webrtc-pc/#dom-rtcstats-id):
> A unique id that is associated with the object that was inspected to produce this RTCStats object. Two RTCStats objects, extracted from two different RTCStatsReport objects, MUST have the same id if they were produced by inspecting the same underlying object. User agents are free to pick any format for the id as long as it meets the requirements above.

Based on being free to pick any format, Chrome's implementation generates IDs that follow patterns that are "easy" to predict. For example, outbound-rtp have IDs "RTCOutboundRTP[Audio/Video]Stream_[ssrc]". Having a predictable patterns makes it easier for implementations to ensure the ID is the same between multiple calls to getStats() and makes it easy to generate one dictionary with an ID reference to another dictionary, before that dictionary has been generated.

The downside to implementations being allowed to use predictable IDs is that applications may take advantage of the predictability and start depending on non-standard ID formats that only work in some browser implementations and versions.

Should we say that ID has to be seemingly random? I imagine ID should look similar to track and stream IDs. What does Firefox do, @jan-ivar ?

**Comment by henbos** [comment]
(The ID of course has to be stable over multiple calls to getStats, but the first time you see a stats object you shouldn't be able to guess it's ID)

**Comment by alvestrand** [comment]
The human-readable names make some types of debugging easier (make it obvious what type the pointed-to object in an 'Id' attribute points to, for instance), but once everything works, obscuring the ID doesn't seem to have very big downsides.
Note: base64(sha1(predictable-string)) is, to all intents and purposes, unpredictable.

**Comment by henbos** [comment]
That's a good idea :)

**Comment by jan-ivar** [comment]
Firefox has the same problem. We're happy to fix this since I agree doing so would improve web compatibility.

**Comment by henbos** [comment]
TPAC decision: Make a PR, something similar to "RTCStats.ids MUST NOT be predictable by the application. An application MUST NOT be able to guess what ID a particular stats object will have without having looked it up in a prior getStats() call of the same RTCPeerConnection"

**Comment by henbos** [comment]
PR exists (on webrtc-pc): https://github.com/w3c/webrtc-pc/pull/2304
