### ISSUE TITLE
We should move RTCCodecStats.implementation to RTC[In/Out]boundRtpStreamStats

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#445]
The set of codec objects is a list based on capabilities and what is negotiated in the SDP.
Which encoder is instantiated for a given codec could theoretically be different for different RTP streams, and is a decision that could be made on-the-fly. When we create codec objects we don't know the implementation. In Chrome, one could start with a HW encoder, but then due to HW encoder errors, it falls back on the fly to a SW implementation.

The current state of the spec is unable to express codecs with multiple implementations, since they are tightly coupled with the SDP, which says nothing about implementation.

The list of codec objects is already huge, I propose we do not duplicate every codec object to have a "implementation: SW" and "implementation: HW" version of the same thing.

To minimize bloat, and to make implementation simpler (at least for Chrome that already has a googCodecImplementation), I propose we move "RTCCodecStats.implementation" to "RTC[In/Out]boundRtpStreamStats.codecImplementation" (or encoderImplementation/decoderImplementation).

This would make shipping "implementation" in Chrome require just a few lines of code, versus refactoring or special logic for the edge-case of implementation changing.

**Comment by vr000m** [comment]
> In Chrome, one could start with a HW encoder, but then due to HW encoder errors, it falls back on the fly to a SW implementation.

Because of the webrtc-stats polling, we cannot precisely know when the codec changed, but I would like webrtc-stats to show the current status of the codec implementation.

**Comment by henbos** [comment]
And current status is a per-instantiation (e.g. per-outbound-rtp) of a codec, not per-codec. Let's move ;)

**Comment by vr000m** [comment]
It makes sense to do it per instantiation. 

However, if I wanted to know which other codecs were available, how would I do that?

cc: @karthikbr82 @mvarela @pallab-gain

**Comment by karthikbr82** [comment]
@vr000m I think we can still obtain all the codes supported using getParameters.

**Comment by henbos** [comment]
Yes and also there will be codec objects from all negotiated codecs, for each payload type, I'm not suggesting moving all of RTCCodecStats. The question here is only about encoder/decoder implementation. This is a very implementation-specific string as well, I don't think we should do more fingerprinting and bloat than we have to, especially since there is no API for controlling which implementation is used.

**Comment by henbos** [comment]
> However, if I wanted to know which other codecs were available, how would I do that?

The codec objects are still there (both in stats and parameters), what you don't know is what other encoder/decoder implementations, but probing implementation capabilities prior to usage belong to a different API than getStats().

**Comment by henbos** [comment]
I'll make a PR that allows me to land [this CL](https://webrtc-review.googlesource.com/c/src/+/149168) to expose this information in Chrome.

**Comment by alvestrand** [comment]
Moving them as indicated sounds reasonable to me.
