### ISSUE TITLE
Audio samples and channels

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#448]
totalAudioEnergy is based on totalSamplesSent or totalSamplesReceived, as is totalSamplesDurations.
These are all based on number of samples.

The spec never mentions audio channels though. The current implementation in Chrome calculates all of these things without taking the number of channels in to account. For example, assuming no packet loss, the totalSamplesDuration increase by 1 second per second. If we took in to account the fact that the audio has 2 channels, we would expect the true samples count to be twice as high, and as a consequence that the totalSamplesDurations increased by 2 seconds per second.

Is Chrome doing the right thing or the wrong thing?
Should we update the spec to say "samples per channel" everywhere it currently says "samples"?

**Comment by henbos** [comment]
I propose we clarify the spec to say what the implementation does, but let's get an audio engineer to explain what makes more sense.

**Comment by henbos** [comment]
@ivocreusen Does it make sense to say that "a sample" refers to "a sample in all channels", i.e. if the number of channels is 2 and we receive a sample in each channel, we count this as 1 sample? Or would we ever have a different number of samples in different channels or need to tell the difference?

**Comment by vr000m** [comment]
This probably needs some discussion at the TPAC. Would someone be able to champion this from Google, cc: @henbos?

**Comment by vr000m** [comment]
Typically the packet size increase when you have multiple channels.

For example:
G.711, 8000 Hz,  8bits/sample and packetization interval of 20ms:
1. 1 channel is 160 samples. The packet size 160*8= 1280 bits
2. 2 channels is 320 sample. The packet size 320*8= 2560 bits

**Comment by henbos** [comment]
I spoke with audio folks and we would always have samples for each channel. We might want per-channel stats in the future (e.g. what is the audio level in this channel versus that channel) but that would require multiple metrics and thus the existing ones are not good enough anyway. So to not break existing usage (and most of the time you don't care about per-channel), I've got a [slide](https://docs.google.com/presentation/d/1Xprz0ElNTUWRDdX6kyp11cZ4ItTvUFUmzoXsKZdXxuU/edit#slide=id.g41c8f53d0b_1_199) proposing that we only increase counters if any of the channels have samples, not for each channel, i.e. twice as many channels does NOT mean twice as high counts.

**Comment by henbos** [comment]
TPAC decision: Clarify that the counters do not increase more the more channels you have (existing Chrome behavior).
