### ISSUE TITLE
Respec citing issues

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-stats#455]
- Couldn't match "DOMHighResTimeStamp" to anything in the document or to any other spec. Please provide a data-cite attribute for it. at: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12.
- Couldn't match "rtcreceiveraudiotrackattachmentstats" to anything in the document or to any other spec. Please provide a data-cite attribute for it. at: 1.
- Couldn't match "rtcreceivervideotrackattachmentstats" to anything in the document or to any other spec. Please provide a data-cite attribute for it. at: 1.
- Couldn't match "rtcmediastreamsource" to anything in the document or to any other spec. Please provide a data-cite attribute for it. at: 1, 2.
- Couldn't match "unsigned long long" to anything in the document or to any other spec. Please provide a data-cite attribute for it. at: 1, 2.
- Couldn't match "RTCDataChannelState" to anything in the document or to any other spec. Please provide a data-cite attribute for it. at: 1.
- Couldn't match "RTCIceCandidateType" to anything in the document or to any other spec. Please provide a data-cite attribute for it. at: 1.
- Couldn't match "rtcaudiohandlerstats.audiolevel" to anything in the document or to any other spec. Please provide a data-cite attribute for it. at: 1.

**Comment by henbos** [comment]
I tried to look in to this but I'm having trouble running the check locally on my mac

**Comment by henbos** [comment]
In webrtc-pc I am able to run `sudo make check`.

In webrtc-stats I get:
```
/bin/sh: cmake: command not found
make: *** [support/tidy-html5/build/cmake/tidy] Error 127
```
Even though `cmake --version` shows I have version 3.13.3. `make travissetup` and `nvm install lts/*` doesn't help. I tried to clone and build htacg/tidy-html5 separately too.

**Comment by karthikbr82** [comment]
made a PR that fixes most of the respec issues - https://github.com/w3c/webrtc-stats/pull/456
