### ISSUE TITLE
Definitions missing - rtcreceiveraudiotrackattachmentstats and rtcreceivervideotrackattachmentstats

### ISSUE THREAD

**Issue by karthikbr82** [w3c/webrtc-stats#457]
Definitions are missing for these two dictionaries
1. rtcreceiveraudiotrackattachmentstats 
2. rtcreceivervideotrackattachmentstats

**Comment by vr000m** [comment]
Inbound stats refers to --- "The identifier of the stats object representing the receiving track, an RTCReceiverAudioTrackAttachmentStats or RTCReceiverVideoTrackAttachmentStats." @henbos should be able to comment on this... since he is changing the inheritance structure of the dictionaries.

**Comment by henbos** [comment]
This sounds like a symptom of #452, closing.
