### ISSUE TITLE
Deleted was removed in #462, was not added to Obsolete section

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-stats#467]
@youennf could you fix this, i.e., update the obsolete stats section  with the changes made in #462 ?

**Comment by youennf** [comment]
Was @deleted shipped in any browser?
If so, that makes sense to add it to the obsolete stats section and probably add a corresponding WPT history test.
Otherwise, is it really worth adding a note?

**Comment by henbos** [comment]
@youennf Yes this was shipped in Chrome. We only ever had non-deleted candidates show up in the stats, so this was hard-coded to always return false, but the metric is still exposed to the web.

**Comment by vr000m** [comment]
It is already in the deleted section
