### ISSUE TITLE
RTCMediaStreamStats can be made obsolete

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#470]
Now that things have been moved to "outbound-rtp" and "inbound-rtp", "track" stats makes less sense, and "stream" stats less so since its a list of trackIds.

We could replace the dictionary by streamIdentifiers on the "sender" and "receiver"

**Comment by henbos** [comment]
- Add streamIdentifiers to sender and receiver stats
- Move RTCMediaStreamStats to the obsolete section

**Comment by vr000m** [comment]
@karthikbr82 @lennart-csio would removing this impact any of our algorithms or diagnostics?

**Comment by henbos** [comment]
TPAC decision: remove "track" and "stream" stats in favor of "mid"; don't need to add streamIdentifiers because that is knowable by other means and not very relevant to stats (if someone want that that should be filed separately).
