### ISSUE TITLE
Rethinking "sender" and "receiver" stats

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#471]
Now that everything is in "outbound-rtp" and "inbound-rtp", the "sender" and "receiver" (and "track") stats is based on a hierarchy of mostly empty dictionaries with some ID references.

We can simplify this:
- RTCMediaHandlerStats can contain "kind" and "mid", and for backwards compatibility with "track" stats have "remoteSource" in the obsolete section. It can also have an array of "streamIdentifiers", removing the need for RTCMediaStreamStats.
- RTCSenderStats can inherit directly from it, adding "mediaSourceId"
- RTCReceiverStats can inherit directly from it too.

**Comment by henbos** [comment]
This removes the need for different dictionaries for Audio and Video cases.

**Comment by vr000m** [comment]
Affects #396

**Comment by alvestrand** [comment]
Is this an user visible change?

**Comment by henbos** [comment]
Anything useful about these dictionaries are in the obsolete section. Simplifying the dictionaries is purely editorial and not user visible (this issue), however the need for "sender"/"receiver"/"track" stats is questioned now that anything useful about a "track" is its _Obsolete_ stats (#472)

**Comment by henbos** [comment]
Let's revisit after TPAC...

**Comment by henbos** [comment]
This is obsolete after the more recent efforts to move unimplemented metrics/dictionaries to the provisional spec and flattening the hierarchies
