### ISSUE TITLE
What should we do about onstatsended?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#480]
Now that there is little point to having track/sender/receiver stats dictionaries around because all their members are made obsolete (#479), it seems that the only use case for them are having objects that would trigger `onstatsended`.

So what is the use case for `onstatsended`? Well, it's nice to know if replaceTrack() was called so that you can correlate stats changing with that point in time.

I think we can do better and not mandate people implement track attachment stats anymore. So what do we do about `onstatsended`?

**Comment by henbos** [comment]
@vr000m

**Comment by vr000m** [comment]
We removed 'deleted' in #356 and #462 (leaving it here if earlier changes are impacted.)

**Comment by henbos** [comment]
TPAC decision: Remove "onstatsended" and file a separate issue for "onstatsevent" or "onreplacetrack" or what else to do.

**Comment by henbos** [comment]
Related TPAC decision: Remove "track" stats

**Comment by vr000m** [comment]
@pallab-gain @karthikbr82 @lennart-csio this may affect our implementation and use-cases, Please take a look and put together a proposal for alternate solutions (atm it seems to be an event on webrtc-pc)

**Comment by henbos** [comment]
onstatsended have now been removed from webrtc-pc: https://github.com/w3c/webrtc-pc/issues/2305

**Comment by aboba** [comment]
@henbos Can we close this issue?

**Comment by henbos** [comment]
I think so, we know the path forward for now based on TPAC and suggestions for alternative events can be addressed separately
