### ISSUE TITLE
RTCStatsType out of sync with webrtc-pc

### ISSUE THREAD

**Issue by milkypostman** [w3c/webrtc-stats#5]
The [RTCStatsType in webrtc-stats](http://w3c.github.io/webrtc-stats/#idl-def-RTCStatsType) is out of sync with [RTCStatsType in webrtc-pc](https://w3c.github.io/webrtc-pc/#idl-def-RTCStatsType).

1. In webrtc-stats there is no hyphen before `rtp`.
2. There are missing stats types from the webrtc-pc documentation.

**Comment by vr000m** [comment]
Thank you for the feedback, Donald. This was discussed at TPAC14 and there are active PRs under discussion which fix the issue.

AFAIU, the RTCStatsType defined in webrtc-stats are the correct ones and we are currently working out how best to document this to avoid this kind of discrepancy between the two documents.

**Comment by alvestrand** [comment]
@dontcallmedom promised to find the link to the TAG document which says whether we should have hyphens or not.

**Comment by dontcallmedom** [comment]
re hyphens in inboundrtp/outboundrtp vs hyphenated version, the TAG guidance is to [use hyphens for enum values](http://w3ctag.github.io/design-principles/#casing-rules):
> Enum values: Lowercase, dash-delimited

**Comment by alvestrand** [comment]
Two items:
- Need to add the dashes in the stats document
- Need to sort out things so that one of the places is clearly authoritative
First one is editorial.

**Comment by alvestrand** [comment]
Note: Extensible enums don't currently exist. Filed bug at https://github.com/heycam/webidl/issues/184

**Comment by alvestrand** [comment]
Correct extensible enum bug: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27048
