### ISSUE TITLE
wrong definition of RTCIceServerStats.protocol?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-stats#512]
The definition of [RTCIceServerStats.protocol](https://w3c.github.io/webrtc-stats/#dom-rtciceserverstats-protocol) seems to be copied from another place, most likely [this one](https://w3c.github.io/webrtc-stats/#dom-rtcicecandidatestats-protocol):
```
    Valid values for transport is one of udp and tcp. 
    Based on the "transport" defined in [RFC5245] section 15.1.
```
which is the protocol used by the candidate. We're rather interested in the protocol used to connect to the TURN server to say "how long is the RTT for this udp turn server", no?
I.e. we want [relayProtocol](https://w3c.github.io/webrtc-stats/#dom-rtcicecandidatestats-relayprotocol):
```
It is the protocol used by the endpoint to communicate with the TURN server.
This is only present for local candidates. Valid values are udp, tcp, or tls. 
```
We could obviously extract that from the url but...

chore task: all the references to 5245 need to be updated :-|

**Comment by vr000m** [comment]
@lennart-csio Please take a look

**Comment by lennart-csio** [comment]
the intention is indeed to have the protocol to connect to the server, i will clarify.
@fippo what do you mean by the core task? at least in the RtcIceServerStats dict there is only this one reference. should it be a task in this issue to go through all references to the RFC and check if its accurate?

**Comment by fippo** [comment]
@lennart-csio, chore, not core. RFC 5245 got obsoleted by 8445 so all references to the old one need to be updated eventually. Which is incredibly boring ;-)

**Comment by lennart-csio** [comment]
thanks for clarifying :)
i will do the fix first as a PR, then we can see if we want to have another issue for updating the RFC reference or not
