### ISSUE TITLE
Add frameBitDepth to RTCInboundRtpStreamStats and RTCOutbountRtpStreamStats

### ISSUE THREAD

**Issue by drkron** [w3c/webrtc-stats#516]
Add the video frame bit depth to RTCInboundRtpStreamStats and RTCOutbountRtpStreamStats.

This is useful in the same way as frameWidth and frameHeight to quickly determine the characteristics of the incoming/outcoming video stream.

**Comment by drkron** [comment]
I have started with implementing this in Chrome and have run into some issues. It becomes a bit complicated when dealing with a mix of hardware and software decoders where the transform from YUV to RGB happens at different places. At least in Chrome it will be hard to get something consistent and meaningful for bit depth per pixel. If the video frame is in i420 then the bits per pixel is 12 until it's converted to RGB where it's 24. The number of bits per channel is the same though.

From my point of view I would like to either:
- Change this back to bit depth per channel.
- Remove bit depth and instead add a boolean isHdr which is true if the content is HDR.

**Comment by henbos** [comment]
If the bits per pixel is 12, how can the bits per channel be 8?

If this is problem of before vs after conversion, don't we just need to clarify that this value is before converting it? I.e. the raw information.

Otherwise, should there be a before and an after value?

**Comment by drkron** [comment]
> If the bits per pixel is 12, how can the bits per channel be 8?

For YUV 420, which is what the SW decoder outputs, two of the channels are subsampled so that for an area of 2x2 pixels there are 4 Y samples, 1 U sample, and 1 V sample. If all are encoded using 8 bits that gives in total 48 bits for 4 pixels.
However, many HW decoders output directly into RGB in which the output is 3x8 pixels.
So the problem (from my perspective) is that you get different result depending on if the frame is decoded using a SW or HW decoder. So the bit depth per channel is same in both cases. Another solution is of course to always report the bit depth per RGB pixel.

> 
> If this is problem of before vs after conversion, don't we just need to clarify that this value is before converting it? I.e. the raw information.
> 
> Otherwise, should there be a before and an after value?

**Comment by drkron** [comment]
I want to be able to distinguish between SDR and HDR, or Vp9 Profile 0 and Profile 2, which is essentially the same as a bit depth per channel of 8 or 10 (or possibly 12). I'm not interested in if it's represented as RGB (24 bits per pixel), YUV 420 (12 bits per pixel) or YUV 444 (24 bits per pixel).

**Comment by henbos** [comment]
Feel free to create another PR that changes the metric to be what you want it to be.
