### ISSUE TITLE
Move RTCMediaHandlerStats::remoteSource to the obsolete section

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#528]
With "sender" and "receiver" stats, you can already tell if it's remote or not. (Not to be confused with Varun's conception of "remoteSource": #453)

**Comment by vr000m** [comment]
I do not see an issue with the definition, is the problem that the implementation does not mirror the definition? also related to #453

**Comment by henbos** [comment]
This particular one should be made obsolete regardless because for what the definition says it is is in the wrong place (#453 to add it where it makes sense) and for what this metric was ever implemented it is adds no new information. Implementing this as described in the current spec causes interop issues and is not doing what either of us wants.

**Comment by henbos** [comment]
Would you feel better if we resolved both issues in the same PR? Then we could ensure that the old definition gets a new home and that this metric's definition is updated to reflect what implementations should deprecate
