### ISSUE TITLE
Move RTCMediaHandlerStats::priority to the obsolete section

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#529]
It refers to a feature that was at risk and has subsequently been [removed from webrtc-pc](https://github.com/w3c/webrtc-pc/pull/2342) and [added to extension spec webrtc-dscp-exp](https://github.com/w3c/webrtc-dscp-exp/pull/5). This is also the wrong place for it to exist, so if anybody wants to support this properly this needs to be revisted.

**Comment by alvestrand** [comment]
while I remember to make a note of it: when re-adding priority stat, we should probably split it into network priority and local priority.
