### ISSUE TITLE
Home of ended, trackIdentifier and kind

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#530]
These used to exist on the "track" stats and currently remain on the handler stats (a.k.a. "sender" and "receiver").

Decide whether they should remain here or if we want to move stuff to "media-source" and/or "inbound-rtp".

This is worth looking at _after_ having made "track" stats obsolete.

**Comment by alvestrand** [comment]
These have different properties.
In particular, track.clone() will result in two tracks with different "id", but "ended" will turn true at the same time for both, and of course "kind" will be the same.

I'm in favor of putting ended and kind on the source-objects (source or rtpreceiver). If "id" has a place in stats, it needs to be on rtpsender ("id of current outgoing track").

**Comment by henbos** [comment]
I think this has either been resolved already or no longer applicable, and we can always add new metrics if we want ended, but I don't think that is needed in stats
