### ISSUE TITLE
Add metric for bytes sent for connectivity/consent requests and responses

### ISSUE THREAD

**Issue by jonasore** [w3c/webrtc-stats#534]

**Comment by alvestrand** [comment]
can you add a few words about why this is a good thing to record?

**Comment by jonasore** [comment]
It is useful to have metrics on connectivity/consent requests and responses
(aka STUN BINDINGS) to get an idea how much bandwidth is consumed
by "overhead" of the ICE stack.

**Comment by fippo** [comment]
Isn't that the same problem described in https://github.com/w3c/webrtc-stats/issues/507#issuecomment-570494862 ? If we have transport stats we can subtract ice transport stats and get a feeling for the overhead?
