### ISSUE TITLE
Expose SCTP stats in RTCSctpTransportStats

### ISSUE THREAD

**Issue by shacharz** [w3c/webrtc-stats#548]
Applications that use data channels intensively would find it useful to have data from SCTP layer:
- **congestion window size** (spinfo_cwnd)
- **receiver window size** (sstat_rwnd)
- **MTU** (spinfo_mtu)
- **packet loss ratio** (not exposed directly in sctp as far as I can tell, but might be able to calculate from sstat_unackdata)

For example:
- congestion, receiver, MTU and rtt together can predict the throughput of the channel, and help prioritize different channels.
- packet loss can help identifying a problem somewhere in the network path.

**Comment by vr000m** [comment]
Make it into PR and we can discuss it there.. I think there was https://github.com/w3c/webrtc-stats/issues/377 and concerns raised in that issue.

**Comment by alvestrand** [comment]
the first use case is a particular way of achieving user-defined congestion control, which is a can of worms for which I think stats is not appropriate.
The second use case seems reasonable on the surface - but it's not exposing a stat that is predefined in SCTP. Exposing scstat_unackdata might be more interesting.

**Comment by shacharz** [comment]
Corresponding bugs tracked on implementors
- [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=1088402)
- [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1642286)
- [Webkit](https://bugs.webkit.org/show_bug.cgi?id=212589)
