### ISSUE TITLE
RTCInboundRTPStreamStats, RTCInboundRTPStreamStats  & RTCRTPStreamStats defined in both -stats -and -pc

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/webrtc-stats#55]
`RTCInboundRTPStreamStats`, `RTCInboundRTPStreamStats`  & `RTCRTPStreamStats` are defined both in webrtc-stats and webrtc-pc (although the definitions aren't the same); we need to pick one or the other (or if needed, make one spec uses partial dictionaries to complete the other).

**Comment by vr000m** [comment]
related to: https://github.com/w3c/webrtc-pc/issues/561, #5, #23, and #25.

**Comment by alvestrand** [comment]
Closed by #64

**Comment by alvestrand** [comment]
(note that https://github.com/w3c/webrtc-pc/issues/561 tracks the webrtc-pc side of resolving this)
