### ISSUE TITLE
Standard getStats() and RTX streams

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#553]
The spec has this to say about RTX:

> When there are multiple RTP streams connected to the same sender, such as when using simulcast or RTX, there will be one RTCOutboundRtpStreamStats per RTP stream, with distinct values of the ssrc member

The RTCOutboundRtpStreamStats dictionary contains bytesSent (all payload bytes, including retransmissions) and retransmittedBytesSent (the subset of bytesSent that are retransmissions).

In the non-RTX case it is clear what value is what.

In the RTX case, the spec suggests there would be a separate outbound-rtp stream stats object. But this does not align with implementations. Implementing the spec raises several questions:
- How do I know which stream is the normal one and which one is the RTX one?
- Would the RTX stream have any metrics other than byte counters defined? For example resolution, frame rate and encode time seems rather strange for an RTX stream?
- Would bytesSent always equal to retransmittedBytesSent? Or would we only define one of them?

But even more importantly: Is there any value in creating a separate stats object? At least in the webrtc.org implementation, if I understand correctly, there is always one RTX stream per RTP stream when RTX is used. So why not just add those bytes to the original outbound-rtp stats object?

**Proposal A**
Add a metric like "isRTX" so you know which object is which, and a reference to the original outbound-rtp object.

**Proposal B**
Merge the RTX into the original outbound-rtp objects' retransmittedBytesSent.

**Comment by henbos** [comment]
Can you comment @alvestrand ?

**Comment by henbos** [comment]
ilnik@ suggesst Proposal B and it makes sense to me, perhaps we just want a metric that lets you know that RTX is used, something like if "rtxSsrc" is present RTX is used with this SSRC, but you only have a single outbound-rtp?

**Comment by henbos** [comment]
@vr000m PTAL

**Comment by vr000m** [comment]
I thought we had this discussion and retransmittedBytes was added without creating a different object. We could add rtxSsrc if people want to know. But the assumption at the time was that one rtx ssrc for each media ssrc.

**Comment by henbos** [comment]
Ack. Then we should clarify the spec. I can write up a PR and fix the implementation.
