### ISSUE TITLE
targetBitrate should be defined as current encoder target settings

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#560]
In #423 I proposed marking this metric obsolete in favor of [totalEncodedBytesTarget](https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-totalencodedbytestarget) but there may be [issues with totalEncodedBytesTarget](https://bugs.chromium.org/p/webrtc/issues/detail?id=11443). For the time being, let's keep targetBitrate.

Its definition doesn't make sense. Especially "It is measured in bits per second and the bitrate is calculated over a 1 second window."
- It's an instantaneous target reflecting the encoder setting, not something you measure over a period of time.
- I'm not sure what the TIAS reference is accomplishing? Looks like a bandwidth modifier in SDP?

I propose just saying this is the current encoder target settings, which is a target for the payload bytes excluding retransmissions.

**Comment by vr000m** [comment]
I think the TIAS reference was to give a measurement guidance and that the target could be set by an external source not necessarily the congestion control algorithm. Nonetheless, if the reference is confusing then it should be clarified.

The target bitrate and not bytes was the input from RMCAT/Congestion control, i.e., what bitrate the congestion controller wants to achieve. it does not specify what time period it should achieve it in, which was not seen as a major issue at the time.

The main purpose was to compare the set targetBitrate and compare it with the currentTransmitBitrate
