### ISSUE TITLE
Add QP statistics to video tracks

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#57]
From Sami Kalliomäki sakal@google.com:

What we need is a way to get average QP over some period of time. I don't think adding this to the receiver side is needed by us but maybe it should be added as well. I think the approach of adding a sum of QP would be a good idea. It probably should be added to the RTCMediaStreamTrackStats structure. Maybe something like this:

qpSum of type unsigned long
Only valid for video. QP (quantization parameter) describes how much spatial detail is included a frame. Low value corresponds with good quality. The range of the value per frame is defined by the codec being used. This parameter represents the sum of all QPs for framesDecoded on remote streams and framesSent on local streams.

The average QP has been implemented before as a goog stat but it never landed. The relevant CLs are here:
https://codereview.webrtc.org/1264693003/
https://codereview.webrtc.org/1420963005/

**Comment by vr000m** [comment]
Is there guidance on what low and high mean here?

**Comment by alvestrand** [comment]
It's well defined for VP8, H.264, VP9 and HEVC, I think. Not redefining it would seem to be a Good Thing.

**Comment by vr000m** [comment]
Yes, the CL states the value is between 1-127. which would important to add. I suppose there is sufficient information to guess what low and high means. A value in the 20s is better than in the 50s.

**Comment by jesup** [comment]
To make use of this, we need to know the video codec in use, reset it on codec change, and also ensure this is per-track since each track will have different QP (or even different codecs)..

I think it is a reasonable thing to feed back to the application.

**Comment by alvestrand** [comment]
Hm. I'm trying to work out how this hangs together.
Frames are counted in RTCMediaStreamTrackStats, and you have to divide the sum-of-QP by the number of frames to get the average QP value.

But the codec information (necessary to know what the QP value means) hangs off RTCCodecStats, which is linked to the codecId of the RTCRtpStreamStats. The linkage between the two is taht RTCMediaStreamTrackStats has a sequence of SSRCs that can be used to find the RTCRtpStreamStats involved. 

Should we put the sum of QP values on the RTCRtpStreamStats, since that has a single codec? Should we then put the FramesReceived there too, so that if a MediaStreamTrack switches codecs mid-flight, the QP values can be counted sensibly for each codec?

**Comment by vr000m** [comment]
Frames that are not decoded but received do not have a QP value, ergo, FramesDecoded would be more appropriate than Frames Received. 

Frames may be received by the endpoint and not be decoded, may occur when a new user joins and starts receiving an existing stream or a user that was not in the filmstrip starts speaking. 

I suppose this would not be an issue if a stream is paused and resumed by the sender?

**Comment by alvestrand** [comment]
Summarizing status:
- The basic approach makes sense. The question is where to place the counters.
- To interpret the number, we need to know the codec. That's only visible in RTCRtpStreamStats (via "codecId" that references an RTCCodecStats object).
- To get the average QP on reception, we need to know the number of decoded frames. At the moment, that's an RTCMediaStreamTrackStats value.

Suggestion:
- Add the proposed counters to RTCRtpStreamStats
- Add a FramesDecoded value to RTCRtpInboundStreamStats
- Add a FramesEncoded value to RTCRtpOutboundStreamStats

I think that should make the counters usable without too much tree-walking.
As long as RTCRtpStream remains 1:1 with RTCMediaStreamTrack, the counters should have the same value as those other counters, but that won't necessarily be true always - the big exception is simulcast, where there would be multiple RtpStreams all pointing to the same RTCMediaStreamTrack.
