### ISSUE TITLE
Datachannel "transportId" doesn't say which transport

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#575]
https://w3c.github.io/webrtc-stats/#dom-rtcdatachannelstats-transportid - says "A stats object reference for the transport used to carry this datachannel."

The datachannel runs on top of an SctpTransport, which runs on top of a DtlsTransport, which runs on top of an ICETransport (the two latter are merged in the stats object model). So "the transport" is ambiguous.

I think the reference should be to the SctpTransport, and the text should say so.

**Comment by henbos** [comment]
When fixing this, also consider fixing #582

**Comment by alvestrand** [comment]
Based on discussion: SCTPTransport seems to be a singleton inside the PeerConnection, so we may not want to have it after all.

**Comment by alvestrand** [comment]
AI is to remove TransportID from datachannel; the correct way is to find the only SCTPTransport in the stats.
