### ISSUE TITLE
Add appendix with flattened stats hierarchies?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#577]
The document as-is is quite hard to read when you come in asking "for a bottom level stats dictionary, what fields can be present?"

The hierarchies make things easier to maintain (common things defined once), but harder to read.

One solution would be to have a machine-generated "fully populated set of dictionaries" as an appendix in the spec, showing all the members and all the inherited members for each dictionary that is actually instantiated in practice.

Tagging @dontcallmedom who's been willing to consider if this is possible to implement.

**Comment by dontcallmedom** [comment]
@alvestrand would something similar to https://w3c.github.io/webrtc-pc/#mandatory-to-implement-stats (but automatically generated) work?

**Comment by tsahilevi** [comment]
Yes please.

Can I get two of those? If possible, with an indication of which of the parameters browser vendors don't implement, end which parameters browser vendors implement in a buggy and unusable fashion 😁
