### ISSUE TITLE
(jitterBufferDelay/jitterBufferEmittedCount * 1000) from pc.getStats is not equal to jitterBufferDelay/jitterBufferEmittedCount_in_ms in chrome://webrtc-internal

### ISSUE THREAD

**Issue by HAHAHA44** [w3c/webrtc-stats#590]
jitterBufferDelay/jitterBufferEmittedCount_in_ms in chrome://webrtc-internal is not equal to the number of (jitterBufferDelay/jitterBufferEmittedCount * 1000) from pc.getStats , especially the video`s stats. 

The remote peer set playout delay in  rtp header, the receiving end can clearly feel that the delay setting takes effect, and jitterBufferDelay/jitterBufferEmittedCount_in_ms equals to the expected number, but jitterBufferDelay/jitterBufferEmittedCount * 1000 is slowly rising.

**Comment by alvestrand** [comment]
Please file a bug at https://crbug.com/ - unless you think this is an error in how the stats are defined, this is a Chrome bug, not a spec bug.

**Comment by fippo** [comment]
(chrome bug filed here: https://bugs.chromium.org/p/webrtc/issues/detail?id=12329)

**Comment by zhuya1996** [comment]
Have you solved this problem? I also encountered this problem. thanks！！！！
