### ISSUE TITLE
media-source video resolution: Before or after adaptation?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#596]
Imagine we have a 720p MediaStreamTrack and a single encoded stream with scaleResolutionDownBy:2 which under perfect circumstances means we encode at 360p.

Now imagine there is adaptation happening. In Chromium, we may adapt 720p before sending it to the encoders. So for example, 720p gets adapted down to 480p. Now because of scaleResolutionDownBy:2, what we actually encode is 240p.

My understanding of the spec is that what getStats reports is:
- media-source.width and height: This refers to the MediaStreamTrack resolution of 720p.
- outbound-rtp.frameWidth and frameHeight: This refers to what we actually encode, i.e. 240p in the adapted case.

On the Chromium implementation side, I don't know if...
1. media-source reports the MediaStreamTrack resolution (720p) or the adapted resolution (480p). I _think_ it reports 480p: if so, this is a bug, right?
2. Do we want a metric for the adapted resolution (480p)? If neither source or encoded stream is 480p I imagine we should not expose this metric, since it seems to be a Chromium implementation detail. That value could also be derived from encoded resolution * scaleResolutionDownBy if someone wants a scaling factor-intependent representation of "how adapted are we"

**Comment by henbos** [comment]
> If neither source or encoded stream is 480p I imagine we should not expose this metric, since it seems to be a Chromium implementation detail.

Actually having a reference resolution for what we would encode if scaleResolutionDownBy was 1.0 would have a meaningful definition on any implementation.

What could be "implementation-specific" is trying to interpret "how adapted are we?" from an adapted resolution value, because while adaptation could cause this resolution to decrease, and equally valid implementation could be to drop other layers instead.

Regardless we should have a metric that makes it easy to tell if a layer is active or not: https://github.com/w3c/webrtc-stats/issues/597

**Comment by henbos** [comment]
I think the same problem exists for frame rate.

**Comment by henbos** [comment]
Yep, I can tell from the code that it is incorrect, I filed https://crbug.com/webrtc/12501.

But if we fix this bug, then we will no longer have access to these "input" metrics. What to do? @vr000m @alvestrand

**Comment by vr000m** [comment]
The media source should report 720, and the outbound metric would be 240. The fact that adaptation happens on the input should not change the media source input value.

I am assuming the  RTCQualityLimitationReason would set something in this scenario. In which case the application knows that the 720 --> 240 happened due to  RTCQualityLimitationReason and scaleResolutionDownBy.

**Comment by henbos** [comment]
OK, then this sounds like a bug in libwebrtc and no action needed on the spec front.
