### ISSUE TITLE
Need to relate all timestamps to Unix time

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#600]
In the webrtc-pc spec, it is clear that the timestamp on a stats record is based on Unix time (https://w3c.github.io/webrtc-pc/#dom-rtcstats-timestamp). It is also mentioned elsewhere (in CSRC) that the value is performance.now() + performance.timeOrigin.

We have however not said explicitly that this basis is used for all timestamps in stats. We should say that (once).

**Comment by vr000m** [comment]
Makes sense. would adding to the preamble section suffice?

**Comment by vr000m** [comment]
https://www.w3.org/TR/webrtc-stats/#basic-concepts

**Comment by alvestrand** [comment]
Given the text in "Basic concepts":

Timestamps are expressed with [DOMHighResTimeStamp](https://www.w3.org/TR/hr-time-3/#dom-domhighrestimestamp) [[HIGHRES-TIME](https://www.w3.org/TR/webrtc-stats/#bib-highres-time)], and are defined as [Performance](https://www.w3.org/TR/hr-time-3/#dom-performance).[timeOrigin](https://www.w3.org/TR/hr-time-3/#dom-performance-timeorigin) + [Performance](https://www.w3.org/TR/hr-time-3/#dom-performance).[now](https://www.w3.org/TR/hr-time-3/#dom-performance-now)() at the time the information is collected.

I think this can be closed.
