### ISSUE TITLE
missing roundTripTime in RTCRemoteOutboundRtpStreamStats

### ISSUE THREAD

**Issue by minyuel** [w3c/webrtc-stats#602]
roundTripTime (together with totalRoundTripTime and roundTripTimeMeasurements) is defined in RTCRemote**Inbound**RtpStreamStats ([link](https://www.w3.org/TR/webrtc-stats/#dom-rtcremoteinboundrtpstreamstats-roundtriptime)), it is supposed to be calculated based on RTCP RR.

For receiving only streams, roundTripTime won't be based on RTCP RR, but can be based on RTCP XR SR ([RFC 3611](https://tools.ietf.org/html/rfc3611)), then I think it ought be reported as one or more data field in RTCRemote**Outbound**RtpStreamStats

**Comment by henbos** [comment]
@alvestrand @vr000m Is this as simple as "let's add another RTT field to the RTCRemoteOutboundRtpStreamStats dictionary"? If so I'm happy to review a PR saying so

**Comment by vr000m** [comment]
yes, this sounds appropriate if the XR is being implemented

**Comment by henbos** [comment]
This issue is fixed since we merged https://github.com/w3c/webrtc-stats/pull/603
