### ISSUE TITLE
MediaStatsHandler.remoteSource should be true in case of receiver

### ISSUE THREAD

**Issue by balazskreith** [w3c/webrtc-stats#605]
> remoteSource of type boolean
> Only applicable for "track" stats. true if the track attachment is on an RTCRtpSender, false if the track attachment is on an RTCRtpReceiver.

**Comment by vr000m** [comment]
The stat is obsolete. The initial idea was to capture if the track being was relayed into the current peerconnection from an output of another peerconnection.

**Comment by balazskreith** [comment]
It is regardless of the initial idea.
The issue is raised because the current state of the standard is inconsistent with the implementations and the current form of the text is misleading. Closing the issue indicate that the text is coherent, however, it is not the case.

**Comment by misi** [comment]
I am also confused here that the spec is right and chrome implemented it differently?
I think it should be addressed if it is a bug in the spec to avoid the confusion, or if it is a bug in chrome then addressed there. 
IMHO it should be updated to fix the misleading text or removed totally.
@vr000m @alvestrand the PR https://github.com/w3c/webrtc-stats/pull/604 is opened to make consistent the actual implementation behavior with the spec.
Please accept it to make actual chrome implementation inline with the spec and avoid further confusion, or remove the obsoleted part from the spec, or if the implementation is bad then fix or remove it from chrome.

**Comment by vr000m** [comment]
> Closing the issue indicates that the issue is irrelevant and the implementation is aligned with the standard, however, it is not the case.

Correct. The implementation is not aligned with the standard. It was also for exactly the above reason that the metric was obsoleted. 

Obsolete also means that these metrics will go away. If this metric is really needed, it would most likely require a new metric name with the updated definition, so that it does not collide with anything that might have implemented the obsolete version of the metric.

I am going to leave the PR #604 in place, in case you want to propose the new metric.

**Comment by balazskreith** [comment]
The standard says: 
>  `true` if the track attachment is on an RTCRtpSender, `false` if the track attachment is on an RTCRtpReceiver.

Interpreted as: if the track is attached to `RTCRtpReceiver` then it is **not** a `remoteSource`

Is the text of the standard has a mistake about `true`, or `false` in the description of the field `remoteSource`. ?

**Comment by misi** [comment]
@vr000m Thanks for the answer!
