### ISSUE TITLE
Stats table generation has failed

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#606]
At the moment, there's a red dot on https://w3c.github.io/webrtc-stats/ saying "Function generateStatsHierarchy threw an error during postProcess. See developer console. (Plugin: "core/post-process")."

this is the magic made by @dontcallmedom - can you fix it?

**Comment by dontcallmedom** [comment]
webidl2.js (on which the script depends) is [no longer available where it was expected](https://github.com/w3c/webidl2.js/pull/562#issuecomment-866298077) - looking into it
