### ISSUE TITLE
Implementing the Circuit Breaker based on StatsAPI

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-stats#61]
Information for calculating the Circuit breaker with the information in the Stats.

CB Trigger 1. latest timestamp of a packet for each SSRC. Covers both sent and received streams
CB Trigger 2. latest timestamp of the RTCP packet for each SSRC. I believe this is covered with the timestamp in the remote stats.
CB Trigger 3. TFRC can be computed with the information, although one piece of information that is missing is the average RTCP interval.

**Comment by alvestrand** [comment]
We could also expose a count of circuit-breaker actions triggered (and leave it as "undefined" for browsers that don't implement circuit-breakers), but the information listed above is interesting anyway.

**Comment by vr000m** [comment]
In addition:
+ target RTCP interval
+ average RTCP Interval
