### ISSUE TITLE
Missing consent interval in RTCIceCandidatePairStats

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-stats#63]
Currently, the consent interval is different for each browser, it would be nice to have a way to know what value is used by the browser.

@aboba @taylor-b comments? 

TPAC16 decision:
Go ahead and create PR.

**Comment by taylor-b** [comment]
As Peter described in Lisbon, we don't really have a fixed consent interval, because for us, "consent checks" serve a double purpose as connectivity checks, and as a way of evaluating the RTT. So we may send them more or less frequently based on the state of the connection.

We still could probably expose some interval in the stats. But it would need to be variable.

**Comment by vr000m** [comment]
That interval, although variable would be a sufficient. 

I'd probably query this when the ICE goes to the disconnected state, mainly to determine the duration of loss in connectivity.

**Comment by alvestrand** [comment]
So the useful number would be the interval between the last two connectivity checks sent?

**Comment by vr000m** [comment]
Yes. The interval between the last two checks. And perhaps a long term average, sum of intervals should be sufficient as we can divide that by the (total number of checks-1)

**Comment by alvestrand** [comment]
Hm. If connectivity is lost, you won't get duration of loss in connectivity from the interval between the last two checks; both were sent before connectivity was lost.
Two interesting numbers are:
- Time of last successful check (which places an upper bound on how long connectivity has been lost)
- Sum and count of intervals

A third interesting number might be the time of the last check sent (which would be a failed one in the case of lost connectivity).

**Comment by vr000m** [comment]
These two would work for me.

**Comment by alvestrand** [comment]
will you write the PR to add lastCheck and sumCheckInterval?

**Comment by vr000m** [comment]
Yes.
