### ISSUE TITLE
Make encoderImplementation/decoderImplementation video-only

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#638]
There has been not enough interest to implement this for audio for years. Maybe easier to update the spec to match the implementation? (Can always revisit later if there is a need for this)

**Comment by alvestrand** [comment]
on a principled basis, it would seem that it should be implemented returning the constant string "default". but reflecting reality is kind of important too.

**Comment by fippo** [comment]
if you send stats elsewhere (even using techniques like delta compression) you don't want the extra bytes or memory
