### ISSUE TITLE
The "Latest editor's draft" points to a June 14 version; latest change was June 29

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#646]
https://github.com/w3c/webrtc-stats/pull/641 merged on June 29 but today (June 30) the latest editor's draft still does not contain it. Should we wait more or is something wrong?

**Comment by henbos** [comment]
Any ideas Dom?

**Comment by dontcallmedom** [comment]
Must have been a temporary glitch in github pages - I pushed a minor change and the latest version now shows up correctly.

**Comment by henbos** [comment]
Great, thanks
