### ISSUE TITLE
No SctpTransport stats?

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-stats#648]
There are currently no statistics relating to `RTCSctpTransport`.  This might include metrics such as `smoothedRtt`, `rttVariation`, `minRtt`, `latest_rtt`.  Also of potential interest: `cwnd`, `rwnd`, `ssthresh`, `congestion state`. 

See: https://docs.google.com/presentation/d/1ot8QMaR6lRSz4ULcJlXkqQHkyKlzsV382447s962QeA/edit#slide=id.g12c2557e5e9_0_5

**Comment by dontcallmedom** [comment]
closing until there is implementor commitment
