### ISSUE TITLE
https://w3c.github.io/webrtc-stats/ is extremely slow

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#651]
Sometimes it times out, sometimes it does eventually load, in either case [the editor's draft site](https://w3c.github.io/webrtc-stats/) is not very usable right now making [the TR draft site](https://www.w3.org/TR/webrtc-stats/) more reliable.

@dontcallmedom are we aware of this? Is there anything to be done?

**Comment by dontcallmedom** [comment]
(fore the record, from a cursory check, I think this was due to loading webidl2.js from unpkg.com which we use it to generate the consolidated table of stats)

**Comment by henbos** [comment]
Well it seems to be working now after your PR :)

**Comment by fippo** [comment]
there seems to have been some latency woes with unpkg today. This web thing... ;-)
