### ISSUE TITLE
Getting the id of an ongoing RTCPeerConnection

### ISSUE THREAD

**Issue by ThierryMajutec** [w3c/webrtc-stats#655]
When I'm using Google Meet, is there any way to get the RTCPeerConnection id of the ongoing session by using a JS API ?

**Comment by henbos** [comment]
Which ID are you referring to? I'm _guessing_ the ID is an implementation detail not exposed anywhere.

**Comment by ThierryMajutec** [comment]
The goal here is to use the getStats() API for which I need to know the RTCPeerConnection.

**Comment by ThierryMajutec** [comment]
So in other words, the question is: "Is it possible to use the getStats() API on ongoing Google Meet sessions?"

**Comment by henbos** [comment]
The app already have access to its own peer connection, are you trying to do cross-document stats polling? I think the context is lost on me for what you're trying to do

**Comment by fippo** [comment]
there is no normal way to get a reference to an already existing peerconnection.

You might try the approach from https://github.com/fippo/webrtc-externals to wrap peerconnections and then inject your own code.

**Comment by dontcallmedom** [comment]
doesn't look a like a webrtc-stats spec issue at this point, closing
