### ISSUE TITLE
There is no ICE "cancelled" state

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#66]
https://tools.ietf.org/html/rfc5245#section-5.7.4 doesn't have a "cancelled" state. If we want this in the RTCStatsIceCandidatePairState enum, we have to find another definition for it.

**Comment by vr000m** [comment]
Is there a reason not to move forward with removing cancelled state?

Cancel appears 4 times in RFC5245, and the closest is:
'''

      *  If the state of that pair is In-Progress, the agent cancels the
         in-progress transaction.  Cancellation means that the agent
         will not retransmit the request, will not treat the lack of
         response to be a failure, but will wait the duration of the
         transaction timeout for a response.  In addition, the agent
         MUST create a new connectivity check for that pair
         (representing a new STUN Binding request transaction) by
         enqueueing the pair in the triggered check queue.  The state of
         the pair is then changed to Waiting.
'''

**Comment by alvestrand** [comment]
If you don't know where it came from either, let's kill it.

**Comment by henbos** [comment]
Related question: The difference between the enum and the referenced RFC is on purpose, yes? E.g. "inprogress" vs "In-Progress".

**Comment by alvestrand** [comment]
Hm. the TAG advice is to use lowercase dash-separated names in enums. So it should be "in-progress" if we follow that advice. We've done so in other cases.
Are there implementations of this state name (apart from Chrome)?

**Comment by henbos** [comment]
@jan-ivar (How) is this implemented in Firefox?
