### ISSUE TITLE
When are RTP streams destroyed?

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#668]
Originally part of issue https://github.com/w3c/webrtc-stats/issues/643. See also [When are RTP stream stats created?](https://github.com/w3c/webrtc-stats/issues/667)

Spec says never to delete RTP stream stats.

Proposal: Delete RTP stream stats at... RTCP bye? SSRC changes? Receiver is reconfigured?

**Comment by fippo** [comment]
for backward compat reasons you can't destroy them on BYE until... 2030 because certain implementations have [for years not cared about violating the spec](https://bugs.chromium.org/p/webrtc/issues/detail?id=5964).

**Comment by henbos** [comment]
I don't want to depend on `RTCP BYE` for deletion because I don't think memory leaks should happen if the remote endpoint disappears without sending you a special packet. A participant abruptly disconnecting is not an excuse to cache SSRCs indefinitely. Also I think it is perfectly sensible to inactivate an `RTCRtpTransceiver` using `direction` rather than `stop()`, and this should count as the RTP stream not existing from a stats perspective.

I'm leaning towards RTP stats deletion happening...
- When negotiation makes the sender or receiver inactive, reconfiguring these objects to ignore these ssrcs.
- If a codec change happens such that the "active ssrc" is swapped out.

In both cases, it's perfectly legal for an inactive ssrc to become active again later in the session. In this case I think we should create a new RTP stats object with a unique stats ID. E.g. the first time you used ssrc=x and the second time you used ssrc=x are different stats objects, because whenever you stop using an ssrc that is when we delete all counters and information about that ssrc's history.

**Comment by henbos** [comment]
@vr000m @alvestrand @jan-ivar Thoughts?

**Comment by henbos** [comment]
A codec change doesn't necessarily change the SSRC but we need to be careful when things are reconfigured e.g. if going to/from simulcast

**Comment by fippo** [comment]
https://www.rfc-editor.org/rfc/rfc3550.html#section-6.3.5 has rules for "timing out a participant" even if there is no bye. I wouldn't rely on that being implemented as specified though.

The problem you are trying to solve is a large multiparty call (run over a single RTCPeerConnection) where participants (and each of them gets 2+ unique ssrcs) join and leave all the time. This leads to
> RTP monitored objects are not [deleted](https://w3c.github.io/webrtc-stats/#dfn-deleted).
describing a lot of participants that are no longer there which is quite a problem.

Binding the lifetime to the lifetime of the transceiver (i.e. stopping it removing the associated stats) seems sensible

**Comment by henbos** [comment]
What if you never stop transceivers? A pattern I've seen is where people negotiate once and then swap out ssrcs when participant changes, but never re-negotiate. This should not lead to infinite RTP stats objects.

While we could delete inactive ssrcs after a timeout, I would much rather only show RTP stats objects for streams currently configured by the sender/receiver.

**Comment by henbos** [comment]
E.g. in singlecast, you would at most only have one outbound-rtp per RTCRtpSender. Very closely tied to current config, but where the stats ID may change whenever we reset counters

**Comment by henbos** [comment]
TPAC: Cullen pointed out that "when the ssrc changes" may be hard to define, but overall there was support for this PR. I propose we merge the PR as-is, in practise the ssrc probably changes at renegotiation time but I don't think the stats spec should say how the implementation deals with ssrcs, seems out of scope.
