### ISSUE TITLE
Need definition for RTCTransportStats.activeConnection

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#67]
The definition for RTCTransportStats.activeConnection is "Set to true when transport is active."

But there's no definition of what "active" means. It might be that the RTCIceTransport that it corresponds to has its state in {connecting, completed}, or it might mean something else. Clarification needed.

**Comment by taylor-b** [comment]
Why not just put the DTLS state, ICE state, and whether the transport is still being used by the PeerConnection in separate fields? Maybe the latter is what `activeConnection` was originally trying to represent.

**Comment by taylor-b** [comment]
Actually, "not being used by the PeerConnection" would cause the ICE state to be "closed", so the ICE state is enough.

**Comment by alvestrand** [comment]
I'd be happy if we changed the definition to "Set to false when ICE state is anything but "closed", true otherwise". Or take it out and replace it with ICEtransportstate.
(Stats assumes that there's one and only one ICEtransport per DTLStransport, and that any ICETransport that doesn't have a DTLSTransport is not interesting. This is probably true for this iteration of the specs.)

**Comment by alvestrand** [comment]
#122 replaces "ative" with "state". @henbos @taylor-b please review.

**Comment by henbos** [comment]
activeConnection [was implemented](https://cs.chromium.org/chromium/src/third_party/webrtc/api/rtcstatscollector.cc?q=rtcstatscollector.cc&sq=package:chromium&dr&l=875) as whether or not we have a selectedCandidatePairId, i.e. didn't add any information that wasn't already there if selectedCandidatePairId was implemented. The DTLS state makes sense to surface instead.
