### ISSUE TITLE
Redundant field `kind` in RTCInboundRtpStreamStats

### ISSUE THREAD

**Issue by balazskreith** [w3c/webrtc-stats#690]
Check the [summary table](https://www.w3.org/TR/webrtc-stats/#summary), "inbound-rtp", and you see the field `kind` listed twice.

`RTCInboundRtpStreamStats` contains the field `kind`.
`RTCInboundRtpStreamStats` dictionary extends `RtcReceivedRtpStreamStats`
`RtcReceivedRtpStreamStats` dictionary extends `RtcRtpStreamStats`
`RtcRtpStreamStats` dictionary contains `kind` field.

It makes sense to keep it only in `RtcRtpStreamStats`.

**Comment by vr000m** [comment]
Agree, we should not have the other dictionaries, redefine this.

**Comment by henbos** [comment]
Let's remove the duplicate definitions. Will you create a PR?
