### ISSUE TITLE
Exposing HW for Cloud Gaming use cases (HW encoder/decoder revisited)

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#698]
We finally have a [hardware exposure privacy mitigation](https://w3c.github.io/webrtc-stats/#limiting-exposure-of-hardware-capabilities), hurray!

@drkron mentioned there is one more use case where HW information may be needed, and that is Cloud Gaming. Unlike VC use cases, a Cloud Gaming app would not be using getUserMedia() (no audio/video capture in the context).

Cloud Gaming does do something that a passive fingerprint is not doing though: it runs in fullscreen.

Can we add "is fullscreen" to the list of conditions where HW exposure is allowed? @youennf @pes10k

**Comment by henbos** [comment]
I assume the app can't toggle fullscreen for a split millisecond without the user noticing... but if it could, the gating could say something like "fullscreen has been active for at least X seconds"...

**Comment by henbos** [comment]
@aboba might care about this too

**Comment by henbos** [comment]
Proposal:

- If [document.fullscreenElement](https://fullscreen.spec.whatwg.org/#dom-document-fullscreenelement) is not null, return true.

**Comment by fippo** [comment]
while that probably encompasses most gamestreaming use-cases you might want to add https://www.w3.org/TR/gamepad/#dfn-gamepad-user-gesture to be on the safe side
