### ISSUE TITLE
Fullscreen shouldn't be enough to reveal fingerprinting-surface

### ISSUE THREAD

**Issue by pes10k** [w3c/webrtc-stats#712]
Currently the spec has two gates to exposing high-resolution / high-granularity fingerprinting surface [capturing or fullscreen](https://w3c.github.io/webrtc-stats/#limiting-exposure-of-hardware-capabilities).

Capturing seems like an appropriate guard since the user has already likely gone through some browser UI flow, and indicated a pretty high level of trust with the site.

Having a `fullscreenElement` though doesn't indicate any such level of trust, and is not a sufficient guard against fingerprinting.  This is especially true since the element that has fullscreen might be only loosely related to the page itself, and might not indicate any level of trust with any frame on the document (think, for example, a clickbate site hosting a youtube video, or any other `<video>`, etc).

Further, many (most?) fullscreen elements have nothing to do with WebRTC

I suggest the spec remove the `fullscreenElement` option in the guard (i.e. remove bullet 2 from [Section 6.1.](https://w3c.github.io/webrtc-stats/#limiting-exposure-of-hardware-capabilities))

**Comment by henbos** [comment]
I don't mind removing this, unless someone objects. @aboba would you care if it was no longer possible to read HW information from getStats (e.g. powerEfficientDecoder, decoderImplementation) in the use case of being in fullscreen and not having GUM access?

**Comment by henbos** [comment]
The gate was originally added as to not break Cloud Gaming use cases, but it is a pretty nieche use case to do fullscreenw without GUM and there is already MediaCapabilities that should give accurate enough information

**Comment by pes10k** [comment]
Terrific, thank you all!
