### ISSUE TITLE
RTCAudioPlayoutStats::totalSamplesCount should be an unsigned long long rather than double

### ISSUE THREAD

**Issue by Hernqvist** [w3c/webrtc-stats#719]
Since it represents an integer number of samples. It needs to be a 64 bit integer, since a 32 bit integer would only fit about half a day of samples assuming a sample rate of 96khz.

**Comment by henbos** [comment]
Definitely, the double was not intentional, so this is ~basically a editorial (don't think anyone has implemented it as a double)
