### ISSUE TITLE
Not clear if RTCTransportStats combines RTP+RTCP or not.

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-stats#72]
The summary states:

> A Transport carries a part of an SDP session, consisting of RTP and RTCP. When Bundle is in use, an SDP session will have only one Transport per Bundle group. When Bundle is not in use, there is one Transport per m-line.

This heavily implies that an RTCTransportStats combines RTP and RTCP for an m= section.

But later, we have rtcpTransportStatsId, defined as:

> If RTP and RTCP are not multiplexed, this is the id of the transport that gives stats for the RTCP component, and this record has only the RTP component stats.

Which implies that there are separate RTCTransportStats for RTP and RTCP. This seems correct, since that would allow a 1:1 mapping from an RTCIceTransport to an RTCTransportStats. Also, it's the only way there could be a single "selected candidate pair" per RTCTransportStats.

**Comment by alvestrand** [comment]
The intent of the spec (I think this was hashed out in the Washington interim, a few years back) is that in the normal case (RTCP-mux), there would be only one transport object; in the exceptional case of unbundled RTCP, there would be two (has to be, given that selectedCandidateId will be different), but the only way to find the RTCP one would be through the RTP one.

**Comment by taylor-b** [comment]
That's what I'd assumed. In that case I think the summary just needs to be updated to make this clear. I'll make a PR.

**Comment by alvestrand** [comment]
PR is #73

**Comment by alvestrand** [comment]
Fixed in #73
