### ISSUE TITLE
Move obsolete section to provisional spec

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#723]
Being able to find "track" and "stream" definitions in the spec has been useful because these objects have been shipped.

We're now well on our way to unship these metrics, so I predict (fingers crossed) that in a couple of months, they will no longer exist in Chromium or libwebrtc.

When that happens I don't think the main spec should contain non-existing metrics. It doesn't feel very "Proposed Rec" to have non-existing metrics.

**Comment by vr000m** [comment]
We should list that the formerly proposed metrics have been documented in the provisional spec, just in case people go looking for them.

**Comment by henbos** [comment]
sgtm

**Comment by henbos** [comment]
Obsolete section has already been removed
