### ISSUE TITLE
Add RTCInboundRtpStreamStats:decoderFallback

### ISSUE THREAD

**Issue by xingri** [w3c/webrtc-stats#724]
After [#712](https://github.com/w3c/webrtc-stats/issues/712) has been merged,  it is no longer possible to get the decoder fallback information in case of cloud gaming services which do not require hardware access permission in general use cases.

And the decoder fallback information is highly important to assess the session information whether the session has been fully accelerated by the hardware decoder or not. So I would like to propose adding decoderFallback in RTCInboundRtpStreamStats to get the information without hurting the security concern.
- https://github.com/w3c/webrtc-stats/commit/d5c96ad30313055f48f1600f5e2e840d5cf0e2ba

If the first proposal is not acceptable, as an alternative, I would also like to propose to remove fingerprint restriction on powerEfficientDecoder in RTCInboundRtpStreamStats.
- https://github.com/w3c/webrtc-stats/commit/01e32ce879c0cc4687771453c761efaf7674ca9f

My justification behind the second approach is that the powerEfficientDecoder can be modifiable when the decoder is getting fallback to the software decoder, so it is not a static variable to represent a user agent.

**Comment by fippo** [comment]
@henbos ^
I've been pondering exposing the number of times this fallback happened which might be a bit more insightful

**Comment by henbos** [comment]
I'm wondering if a boolean would suffice for "the selected codec does have HW but it's currently not used due to fallback to SW being active". So powerEfficient is false but softwareFallback is true.

I think a boolean is more helpful than a counter because a counter talks about the past rather than what is currently the case, and I'm not sure there is much value in counting the number of times an attempt is made, which seems like an implementation detail that could be different on different browsers. E.g. one browser may try to re-boot the HW after a while but another browser may stop using it for the rest of the session... the caller of getStats shouldn't care.

@eshrubs do you have any thoughts or opinions about adding SW fallback information to getStats? I think it would be a good addition to powerEfficient to have this.

> So I would like to propose adding decoderFallback in RTCInboundRtpStreamStats to get the information without hurting the security concern.

Sadly I disagree that this is not a privacy/security concern. This metric exposes that HW was available, so It also needs to be gated. I think what you want @xingri is more conditions to the "exposing hardware is allowed" check

**Comment by eshrubs** [comment]
A counter could be useful, I think that one should be able to detect this using the `powerEfficient` metric; of the previous datapoint was `powerEfficient` and the following on is not then a software fallback could be considered. There are of course some issues with this, for example if the hardware decoder fails initially, or the flip-flop case as @fippo describes. The former case could be detected using media capabilities to check if a hardware decoder was expected to be used. The latter is probably a bug and would generate a lot of keyframes.

**Comment by xingri** [comment]
Thank you all for sharing the feedback on the request. 
As @henbos mentioned, we needs the current state of the decoder, so I hope to keep the boolean instead of the count.

**Comment by fippo** [comment]
while we are at it I have a long standing annoyance with the lack of being able to tell *why* fallback happened. WDYT about exposing what Chromium gathers [as reasons](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/peerconnection/rtc_video_decoder_fallback_recorder.h;l=15;bpv=1;bpt=1):
```
enum class RTCVideoDecoderFallbackReason {
  kSpatialLayers = 0,
  kConsecutivePendingBufferOverflow = 1,
  kReinitializationFailed = 2,
  kPreviousErrorOnDecode = 3,
  kPreviousErrorOnRegisterCallback = 4,
  kConsecutivePendingBufferOverflowDuringInit = 5,
  kMaxValue = kConsecutivePendingBufferOverflowDuringInit,
};
```
UMA are hard to correlate with a particular encoder on the other end.

With the ability to restrict exposure this should be reasonably safe?

**Comment by xingri** [comment]
@fippo thanks you for the update. As I already mentioned, on #725, please consider the following aspects of the new metric.

I agree that new metric could also expose the HW capability at some instance of the time. 

However I would like to note that what the fingerprint guidance concerns is not only the hardware exposer of the user agent(browser) but risk of the fingerprinting of the user agent as defined by <https://w3c.github.io/fingerprinting-guidance/> as follows:

_**..., browser fingerprinting is the capability of a site to identify or re-identify a visiting user, user agent or device via configuration settings or other observable characteristics.**_

To share the transitions of this metric, it may look like following:
- In case of no HW Decoder:  stays false
- In case of HW Decoder: starts with false and turns to true only when the decoder gets fallback and changes to false again when the decoder gets recovered to HW.
 
So the current metric could not be used for identifying the user, user agent or device because of ephemeral characteristics of decoder fallback. 

And when we consider the cloud gaming's general use case, the camera and microphone permission are not required  because it works as one-way streaming from the gaming server to the browser client, so it does not require user permission for the hardware access.

And we could detect any streaming abnormalities through the decoder fallback from decoder implementation metric and it is currently blocked by the fingerprint concern by [#712](https://github.com/w3c/webrtc-stats/issues/712).

That's why I proposed this new metric which might not expose the finger print of the user agent directly unlike decoder implementation and power efficiency metrics.

**Comment by xingri** [comment]
Will follow up through https://github.com/w3c/webrtc-extensions/issues/146.
