### ISSUE TITLE
Confusing use of the terms defined and undefined

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-stats#737]
The terms _"defined"_, _"undefined"_, the JS value `undefined`, and member present/omitted/[exists](https://infra.spec.whatwg.org/#map-exists) are different concepts.

This spec appears to be using these terms interchangeably in some places. For example, [encoderImplementation](https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-encoderimplementation) says:
- _"Only defined when [exposing hardware is allowed](https://w3c.github.io/webrtc-stats/#dfn-exposing-hardware-is-allowed). ... Only [exist](https://infra.spec.whatwg.org/#map-exists)s for video."_

Here the term [exists](https://infra.spec.whatwg.org/#map-exists) is well-defined, but "defined" is not (no pun intended). There's no way to tell what it means, but I suspect what was meant was:
- "Only [exists](https://infra.spec.whatwg.org/#map-exists) for video, and only when [exposing hardware is allowed](https://w3c.github.io/webrtc-stats/#dfn-exposing-hardware-is-allowed)."

See https://github.com/w3c/webrtc-stats/issues/736#issuecomment-1452556494 for how the concepts differ.

Action items:
1. I count 4 hits for _"Only defined"_, which should probably be _"Only [exists](https://infra.spec.whatwg.org/#map-exists)"_ (plural seems better)
2. Most other hits for "defined" seem to be correct (references to where something is _specified_) but I could have missed some.
3. The 14 hits for "undefined" are more suspect. I see phrases like _"Calculated as defined in section 6.4.1. of [[RFC3550](https://w3c.github.io/webrtc-stats/#bib-rfc3550)]. If no [RTCP Receiver Report](https://w3c.github.io/webrtc-stats/#dfn-receiver-report) is received with a DLSR value other than 0, the round trip time is left undefined"_

In the last one, _"defined"_ seems to mean _specified_, whereas _"left undefined"_ I suspect means omitted.

**Comment by henbos** [comment]
> This spec appears to be using these terms interchangeably in some places

We should update all uses of defined/undefined to present/omitted/exists, the usage difference was not on purpose and the libwebrtc stats implementation does not support that distinction.

**Comment by henbos** [comment]
The V8 generated binding based on "dictionary" in .idl files also does not seem to support undefined, Chromium [recently migrated](https://chromium-review.googlesource.com/c/chromium/src/+/4236340) to WebIDL and the generated files ([example](https://source.chromium.org/chromium/chromium/src/+/main:out/Debug/gen/third_party/blink/renderer/bindings/modules/v8/v8_rtc_codec_stats.h)) either has or does not have a value set, there is no "set to undefined"
