### ISSUE TITLE
availableOutgoingBitrate is also available when send-side BWE is not used

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-stats#740]
https://w3c.github.io/webrtc-stats/#dom-rtcicecandidatepairstats-availableoutgoingbitrate
stipulates that
> Implementations that do not calculate a sender-side estimate must leave this undefined.

This is not how Chromium/libwebrtc behave, it exposes the value received by REMB which makes a lot of sense to me.

For the corresponding available incoming bitrate this makes a bit more sense because this value can only be calculated when REMB is used while a send-side BWE does not have the full information.

Using a normative MUST seems overkill in both cases, this calls for "exist". Can fix but after #739 gets merged to avoid confusion.

**Comment by bbaldino** [comment]
> it exposes the value received by REMB which makes a lot of sense to me.

I'd agree having this information even when REMB is in use is very useful.  When debugging media issues, one of the most important things to determine is "what did the browser think it had to work with, in terms of bandwidth?"
