### ISSUE TITLE
RTX and FEC stats are incomplete.

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-stats#751]
While we have statistics about retransmission [packetsSent](https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-retransmittedpacketssent) and [bytesSent](https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-retransmittedbytessent) on [outbound-rtp](https://w3c.github.io/webrtc-stats/#dom-rtcstatstype-outbound-rtp) stats, we lack corresponding `retransmittedPacketsReceived` and `retransmittedBytesReceived` for [inbound-rtp](https://w3c.github.io/webrtc-stats/#dom-rtcstatstype-inbound-rtp).

I *believe* the reason is that without RTX it is not possible to identify retransmissions. However, RTX is available in all browsers these days (for video). When RTX is not used, these should not be present. #735 defines those.

Similarly, for FEC we have `inbound-rtp` stats for [fecPacketsReceived](https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-fecpacketsreceived) and [fecPacketsDiscarded](https://w3c.github.io/webrtc-stats/#dom-rtcinboundrtpstreamstats-fecpacketsdiscarded) but no corresponding `outbound-rtp` `fecPacketsSent` and no `fecBytesSent`. We also lack `fecBytesReceived`.

I *believe* this is due to FEC focusing on opus inband audio fec where the amount of bytes is somewhat hard to calculate *because opus*. For video FEC we have both `ulpfec` and `flexfec` implemented in browsers but don't have good statistics on them.

**Comment by vr000m** [comment]
Correct, we do not have opus-related FEC metrics because it is within the payload and not visible at the RTP level. fecPacketsSent should be there, it might have been moved to the provisional stats as unimplemented stats are implemented there.

Are these metrics implemented somewhere?

Because we have split the spec into at least implemented by one browser (webrtc-stats) or a new stat but not yet implemented (provisional-stats), we should create a template that asks for each issue:
* is this clarifying an existing metric
* is this a bug on an existing metric
* is this metric already implemented or soon to be available
* is this metric yet to be implemented

**Comment by vr000m** [comment]
also related to #238

**Comment by fippo** [comment]
> Are these metrics implemented somewhere? If they are, we should add them here.

New stats (or rather a big gap in the existing modeol?)
I have working code for RTX and plan to do video-FEC this year.

Opus FEC is technically codec-specific but  since track stats got merged into {in|out}bound-rtp should go there.

**Comment by vr000m** [comment]
lets add the rtx ones now to webrtc-stats. The others to provisional stats and when they become a available, we will move those stats to this spec.

**Comment by henbos** [comment]
Fixed by #735

**Comment by henbos** [comment]
Oh that just takes care of RTX, not FEX

**Comment by henbos** [comment]
I consider #755 a drive-by fix related to this issue, fixing an existing inconsistency between send and receive counters.

**Comment by henbos** [comment]
@fippo What's the status here?

**Comment by fippo** [comment]
Hrm... for some reason I can't reopen this. I just happened to see the `rtxSsrc`
https://w3c.github.io/webrtc-provisional-stats/#dom-rtcoutboundrtpstreamstats-rtxssrc
in provisional stats. Can I move it over here (both for inbound-rtp and outbound-rtp)?

**Comment by alvestrand** [comment]
Seems I can reopen it...

**Comment by alvestrand** [comment]
If we have an implementation landed in a browser, I'm happy with moving it here.
