### ISSUE TITLE
RTCAudioSourceStats.audioLevel - what algorithm described in totalAudioEnergy?

### ISSUE THREAD

**Issue by hamishwillee** [w3c/webrtc-stats#757]
The spec on `RTCAudioSourceStats.audioLevel` says [here](https://www.w3.org/TR/webrtc-stats/#dom-rtcaudiosourcestats-audiolevel):

> The [audioLevel](https://www.w3.org/TR/webrtc-stats/#dom-rtcaudiosourcestats-audiolevel) is averaged over some small interval, using the algorithm described under [totalAudioEnergy](https://www.w3.org/TR/webrtc-stats/#dom-rtcaudiosourcestats-totalaudioenergy). The interval used is implementation dependent.

In `totalAudioEnergy` it is not clear what algorithm is meant? Is it that you expect user agents to calculate the value by doing something like: `Math.sqrt((energy2 - energy1)/(duration2 - duration1))` using whatever duration they wish?

**Comment by hamishwillee** [comment]
Since I'm here would it also be correct to assume that there is some kind of underlying accumulator for the associated audio source - so the  RTCAudioSourceStats that you get on request will always be the same or greater than for the previous one for totalAudioEnergy and totalDuration? 

The timestamp is just an indication of the point at which you sampled the underlying accumulator "thing".

**Comment by henbos** [comment]
> Is it that you expect user agents to calculate the value by doing something like: Math.sqrt((energy2 - energy1)/(duration2 - duration1)) using whatever duration they wish?

Yeah pretty much. I'm honestly not sure the implementations use the same algorithms in practise, but the idea is that this is a snapshot of something you could have calculated yourself over a short time interval

**Comment by hamishwillee** [comment]
Thanks!
