### ISSUE TITLE
Discrepancies between RTCRtpCodecParameters and RTCCodecStats naming

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-stats#77]
RTCCodecStats has "codec" and "parameters" whereas RTCRtpCodecParameters has "mimeType" and "sdpFmtpLine" which seem to mean the same things.

If these are indeed expected to contain the same information, it would be nice if the names aligned. I slightly prefer the RTCRtpCodecParameters names; they seem more descriptive.

**Comment by alvestrand** [comment]
We think this was introduced at TPAC in Sapporo. Have to check the minutes.
The CodecParameter names seem very SDP-linked.

**Comment by vr000m** [comment]
@jan-ivar, @aboba Has someone implemented this? and what did you use?

**Comment by alvestrand** [comment]
We also need to check implementations.

**Comment by jan-ivar** [comment]
@vr000m Firefox has implemented neither (there's some webidl in place, but nothing backing it).
