### ISSUE TITLE
Is codec.sdpFmtpLine present when there is no fmtp line in the SDP?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-stats#779]
Which is typically the case for VP8 which has no parameters. In Chrome this leads to
![image](https://github.com/w3c/webrtc-stats/assets/289731/bf56f215-640e-46ba-82a8-8d916baea026)
while sdpFmtpLine is defined as 
```
DOMString     sdpFmtpLine;
```
[here](https://w3c.github.io/webrtc-stats/#codec-dict*).

It seems like this should only exist when the codec has a fmtp line? No code changes required but we might need some WPT updates.

**Comment by alvestrand** [comment]
It's a dictionary, so omitting members is allowed, and I think it should be required to omit it when there is no fmtp line. (If there's "a=fmtp:96:" in the SDP, there should be an empty string there, of course.)

**Comment by fippo** [comment]
oh we have that special-case of empty fmtp line for stats too courtesy of @dontcallmedom!
