### ISSUE TITLE
RTCCodecStats.clockRate - media sampling rate or the codec clock rate?

### ISSUE THREAD

**Issue by hamishwillee** [w3c/webrtc-stats#785]
Spec for `RTCCodecStats.clockRate` says it is the  "media sampling rate". However the parameter that is set is defined in `RTCRtpCodec.clockRate` as _The codec clock rate expressed in Hertz_, which on MDN is documented as "the rate at which the codec's RTP timestamp advances"

I'm largely ignorant of this, but looking around, it seems that these are different things. So I am wondering if `RTCCodecStats.clockRate`  definition is correct, and is expected.

This is for MDN docs update - https://github.com/mdn/content/pull/32452/files#r1503650664

**Comment by vr000m** [comment]
The value should be the same across SDP and RTP -- see IANA entries for different codecs, although webrtc only supports -- H.264, VP8, (also VP9 and AV1), for audio PCM and Opus (some support AMR and G722). 

The values will correspond to the IANA https://www.iana.org/assignments/rtp-parameters/rtp-parameters.xhtml

**Comment by alvestrand** [comment]
The "sampling rate" of 90000 for video was chosen in order to ensure that the common frame rates of 20, 30, 50, 60 and 29.95 fps could all be represented as integers.

"Media sampling rate" is usually the same number for audio, but is an irrelevant concept for video.
