### ISSUE TITLE
Expose protocol used to communicate with TURN server

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-stats#83]
For TURN candidates, it would be useful to see the protocol used to communicate with the TURN server. Either UDP, TCP, or TLS over TCP. The `protocol` field that currently exists is just the protocol of the allocated candidate.

If we add this, it may be worth adding to `RTCIceCandidate` as well. Though it's in a different category from the other attributes, in that it's not something that appears in the candidate SDP.

**Comment by alvestrand** [comment]
From https://tools.ietf.org/html/rfc5928#section-3 it seems that a TURN client-server link can indeed resolve to any protocol (if unspecified), so you can't tell from the URI scheme, which was my first thought.

I'm not clear on when in the process of resolving a candidate this field can be populated - can you help in describing that?

**Comment by fippo** [comment]
this would basically have to expose the local type preference (which is priority >> 24) and then turn that into the transport protocol using a browser-specific mapping.

But wasn't the URL the candidate was gathered from for exactly that purpose? I agree though that this is a more direct solution.

**Comment by alvestrand** [comment]
It turns out a turn url without a transport modifier can end up using any protocol depending on dns config and local capabilities so no, in general you cannot know from the url. Complex stuff!

**Comment by fippo** [comment]
pinging @jan-ivar -- iirc you have a mozlocaltransport already?

**Comment by jan-ivar** [comment]
Yes we have `mozLocalTransport`. You can see it in a dump [here](https://jsfiddle.net/moz71L7h/).

I found [this old comment](https://bugzilla.mozilla.org/show_bug.cgi?id=970690#c8) on it.

**Comment by taylor-b** [comment]
@alvestrand 
> I'm not clear on when in the process of resolving a candidate this field can be populated - can you help in describing that?

Well, it needs to happen before the candidate is allocated ("gathered"), so there's never a situation where it could be unknown at the time of appearing in a stats report.

Of course, this field would only be present for local candidates, not remote candidates.
