### ISSUE TITLE
RTCMediaStreamTrackStats does not have mediaType member.

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#84]
The "RTC[In/Out]boundRTPStreamStats : RTCRTPStreamStats" dictionaries are valid for both audio and video. RTCRTPStreamStats has a DOMString mediaType that is either "audio" or "video" to distinguish the two cases.

RTCMediaStreamTrackStats is also valid for both audio and video, but it has no mediaType member. You'd have to examine the other members (some of which are only valid for audio or video) to deduce if its for audio or video.

We should add "DOMString mediaType" to RTCMediaStreamTrackStats.
- Side-question: Why is this a DOMString and not an enum? Should we change it to enum for both dictionaries?

Alternatively we could split it up into "RTCMediaStream[Audio/Video]TrackStats : RTCMediaStreamTrackStats". Its members are mostly audio- or video-specific so why are all of the members in the same dictionary?

**Comment by alvestrand** [comment]
As long as the RTCMediaStream datatype is one type and not two, I think we should keep the stats in one dictionary too.
The MediaStreamTrack attribute is called "kind", not "mediaType". I think we should keep that name.
