### ISSUE TITLE
Design consideration for inactive SSRCs and inactive transports

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-stats#86]
In #68, it was raised that:

+ ICE restarts will cause new candidate pairs to become active and previously active ones to become inactive, if the call last long, the number of candidate pairs will accumulate.
+ Similarly if SSRCs change, previously active SSRCs will still be reported upon.

Is there something that we can do better?

**Comment by vr000m** [comment]
Copying my comment from the issue #68:

With the frozen timestamps, an app can filter out the older candidates, assuming the app has some idea about how often it queries or when it last queried the stats.

Although one concern I do have (and perhaps could be solved in a different way) is if the ice candidate is currently inactive and was active in the past, we do not really know when it was last active. We perhaps need a lastPacketSentTimestamp, lastPacketReceivedTimestamp or similar

**Comment by alvestrand** [comment]
Would this timestamp be valid for only local candidates, or would we also update the remote candidate of a pair? Or perhaps it's on candidate pairs? (a candidate can't be active without being part of a pair).

**Comment by vr000m** [comment]
I will add the timestamps to the candidate pair stats.
