### ISSUE TITLE
RTCTransportStats not referenced from RTCDataChannelStats or RTCIceCandidatePairStats

### ISSUE THREAD

**Issue by henbos** [w3c/webrtc-stats#88]
RTCDataChannelStats and RTCIceCandidatePairStats doesn't know about their transport, they should have a "transportId" member, just like RTC[In/Out]boundRTPStreamStats does.

Note: RTCTransportStats does have selectedCandidatePairId, but this only covers the selected one and in direction transport->pair, not pair->transport.

**Comment by vr000m** [comment]
Duplicate of #92?

**Comment by alvestrand** [comment]
I think this is solved in #94, so this is a duplicate of #92

**Comment by alvestrand** [comment]
Closing as dup.
