### ISSUE TITLE
We forgot to add RTCRTPStreamStats.mediaType

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-stats#9]
This was proposed to the list [over a year ago](https://lists.w3.org/Archives/Public/public-webrtc/2014May/0241.html) by @alvestrand with favorable response, and has been implemented in Firefox release [since 34 (December)](https://bugzilla.mozilla.org/show_bug.cgi?id=1055378).

**Comment by vr000m** [comment]
Merged.
