### ISSUE TITLE
Not clear how to differentiate between received connectivity checks and consent requests

### ISSUE THREAD

**Issue by taylor-b** [w3c/webrtc-stats#96]
This issue applies to RTCIceCandidatePairStats.requestsReceived and consentRequestsReceived. The actual STUN packet looks the same, so how should an implementation differentiate between the two?

For *sent* requests, we can say that any binding request sent before a response is received is a connectivity check, and any request sent after is a consent request. But we can't do this for received binding requests, because we don't know if the remote peer received a response or not.

**Comment by alvestrand** [comment]
@aboba please comment.
Also: The text isn't clear about whether requestsReceived are supposed to include consentRequestsReceived - the comment in the RoundTripTime stat seems to assume that they are nonoverlapping, but the names sugges that requestsReceived includes all requests.

**Comment by henbos** [comment]
Bump @aboba

**Comment by henbos** [comment]
If we can't differentiate the two we should just remove consentRequestsReceived. I can create a PR if you agree?

Related question: Are we able to differentiate between responsesReceived and retransmissionsReceived? Does the STUN packet say whether it's a retransmission or a normal response? (Speaking out of ignorance): If not we should remove that too.

Is it useful to be able to distinguish between requests/responses and consent requests/responses? Isn't the interesting thing whether or not the counters keep increasing? We already know if we're connected or not though other means. If that is not a useful distinction we could merge all the "consent" ones into the requests/responses ones - but maybe it is?

**Comment by taylor-b** [comment]
> If we can't differentiate the two we should just remove consentRequestsReceived.

I agree, unless someone brings up something I hadn't considered.

> Does the STUN packet say whether it's a retransmission or a normal response?

No, not without a nonstandard attribute to indicate that. However, it would still be reasonable to say "responsesReceived" represents the number of unique transaction IDs received, and "retransmissionsReceived" represents the number of packets received with already-seen transaction IDs. You could infer some information about packet loss from that.

> Is it useful to be able to distinguish between requests/responses and consent requests/responses?

Personally, I don't see much usefulness, and I feel it makes things more confusing, so I'd be fine not differentiating. @aboba, @vr000m, care to weigh in?

**Comment by alvestrand** [comment]
There's a cost in reporting the number of unique transaction IDs in that it requires keeping track of which IDs are already seen - potentially forever. That's a burden.

In the absence of compelling evidence that it's a) possible and b) useful to distinguish between them, I'm going to do a PR that removes "retransmissionsReceived", "consentReqeustsReceived" and "consentResponsesReceived", and change the definition of "requestsReceived" and "responsesReceived" to say that it's the total count of STUN packets of those types received.

I'll make @aboba a reviewer for the PR.
