### ISSUE TITLE
Remove availableIncomingBitrate?

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-stats#97]
In the case of sender-side bitrate control, there is no way for the receiver to estimate the available bitrate.
Since it can't be implemented consistently across all bandwidth control algorithms, its value seems limited; should we delete it?

Ping @aboba

**Comment by vr000m** [comment]
While this is currently true, do we want to limit future implementations from experimenting with receiver side estimation? 

Implementations that do not have a receive side estimate can skip filling in the key.

**Comment by alvestrand** [comment]
We need to add to description that it's only relevant if r-side estimation is implemented.

**Comment by aboba** [comment]
@alvestrand Having bandwidth availability reported only from the sender side is ok.

**Comment by aboba** [comment]
@Alvestrand We are currently using the receiver bandwidth estimate, so I'd prefer it be kept.

**Comment by vr000m** [comment]
@aboba see text in PR #182, does it work for you?
